import React, { useState } from 'react';
import { 
  X, 
  Download, 
  Printer, 
  Play, 
  HelpCircle, 
  CheckCircle2, 
  FileText, 
  BookOpen, 
  Clock, 
  ShieldCheck, 
  Sparkles,
  Share2,
  ChevronDown,
  ChevronUp,
  Globe
} from 'lucide-react';
import { motion } from 'motion/react';
import { PastQuestion } from '../types';
import { useApp } from '../context/AppContext';

interface PastQuestionViewerModalProps {
  pq: PastQuestion | null;
  isOpen: boolean;
  onClose: () => void;
  onStartCbt: (pq: PastQuestion) => void;
  onSearchBrowserForCourse: (courseCode: string) => void;
}

export const PastQuestionViewerModal: React.FC<PastQuestionViewerModalProps> = ({
  pq,
  isOpen,
  onClose,
  onStartCbt,
  onSearchBrowserForCourse
}) => {
  const { addToast } = useApp();
  const [showAnswers, setShowAnswers] = useState(false);
  const [expandedSolutions, setExpandedSolutions] = useState<Record<number, boolean>>({});

  if (!isOpen || !pq) return null;

  const toggleSolution = (idx: number) => {
    setExpandedSolutions(prev => ({ ...prev, [idx]: !prev[idx] }));
  };

  const handleDownloadPaper = () => {
    let paperText = `================================================================================
                    ${pq.institutionName.toUpperCase()}
                   ${pq.faculty.toUpperCase()}
               DEPARTMENT OF ${pq.department.toUpperCase()}
================================================================================
EXAMINATION:      ${pq.sessionYear} ${pq.semester.toUpperCase()}
COURSE CODE:      ${pq.courseCode}
COURSE TITLE:     ${pq.courseTitle}
LEVEL:            ${pq.level}
TIME ALLOWED:     ${pq.timeAllowed || '2 Hours 30 Minutes'}
================================================================================
INSTRUCTIONS:
${pq.instructions || 'Answer ALL questions in SECTION A (Objective) and any THREE (3) questions in SECTION B (Theory). Write legibly and state all assumptions clearly.'}
================================================================================

SECTION A: OBJECTIVE / MULTIPLE CHOICE QUESTIONS
--------------------------------------------------------------------------------
`;

    if (pq.questions && pq.questions.length > 0) {
      pq.questions.forEach((q, idx) => {
        paperText += `\nQ${idx + 1}. ${q.question || q.questionText}\n`;
        if (q.options && q.options.length > 0) {
          q.options.forEach((opt, oIdx) => {
            const letter = String.fromCharCode(65 + oIdx);
            paperText += `   [${letter}] ${opt}\n`;
          });
        }
        if (showAnswers && q.correctOption !== undefined) {
          const correctLetter = String.fromCharCode(65 + (q.correctOption || 0));
          paperText += `   >> Official Correct Option: [${correctLetter}] ${q.options ? q.options[q.correctOption] : ''}\n`;
          if (q.explanation) {
            paperText += `   >> Explanation: ${q.explanation}\n`;
          }
        }
      });
    }

    if (pq.theoryQuestions && pq.theoryQuestions.length > 0) {
      paperText += `\n\n================================================================================
SECTION B: ESSAY & COMPUTATIONAL THEORY QUESTIONS
--------------------------------------------------------------------------------
`;
      pq.theoryQuestions.forEach((tq) => {
        paperText += `\nQUESTION ${tq.questionNumber} [${tq.marks} MARKS]:\n${tq.questionText}\n`;
        if (showAnswers && tq.solutionGuide) {
          paperText += `\n>> Model Marking Guide & Worked Solution:\n${tq.solutionGuide}\n`;
        }
      });
    } else {
      paperText += `\n\n================================================================================
SECTION B: STANDARD DEPARTMENTAL THEORY PROBLEMS
--------------------------------------------------------------------------------
QUESTION 1 [20 Marks]:
(a) Define the fundamental theoretical principles governing this syllabus.
(b) Derive the governing analytical relationship, stating clearly all boundary conditions.
(c) Apply the above formulation to compute standard empirical values.

QUESTION 2 [20 Marks]:
Critically evaluate the core institutional applications within the Nigerian tertiary context. State 3 practical examples and outline potential implementation constraints.
`;
    }

    paperText += `\n\n================================================================================
SOURCE ARCHIVE:   ${pq.source}
COPYRIGHT NOTICE: ${pq.copyrightNotice || 'Fair use educational revision material for tertiary examination preparation.'}
GENERATED BY:     StudentHub NG (Everything Student. One Platform.)
================================================================================`;

    const blob = new Blob([paperText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${pq.courseCode.replace(/\s+/g, '_')}_${pq.sessionYear.replace('/', '-')}_PastQuestion_Paper.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    addToast('Past Question Downloaded', `Successfully downloaded official exam paper for ${pq.courseCode} (${pq.sessionYear}).`, 'success');
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-5 bg-slate-950/80 backdrop-blur-md overflow-y-auto">
      <motion.div
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        exit={{ opacity: 0, scale: 0.95 }}
        className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl shadow-2xl max-w-4xl w-full my-auto overflow-hidden flex flex-col max-h-[92vh]"
      >
        {/* Top Control Bar */}
        <div className="p-4 sm:p-5 bg-slate-900 text-white flex items-center justify-between gap-3 shrink-0 print:hidden">
          <div className="flex items-center gap-2 sm:gap-3">
            <span className="px-3 py-1 rounded-xl bg-blue-600 text-white font-black text-xs sm:text-sm shadow-sm">
              {pq.courseCode}
            </span>
            <div>
              <h3 className="font-extrabold text-sm sm:text-base text-white line-clamp-1">
                {pq.courseTitle}
              </h3>
              <p className="text-[11px] text-slate-400">
                {pq.institutionName} • {pq.sessionYear}
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={() => setShowAnswers(!showAnswers)}
              className={`px-3 py-1.5 rounded-xl text-xs font-bold transition-all flex items-center gap-1.5 ${
                showAnswers
                  ? 'bg-emerald-500 text-slate-950 shadow-sm'
                  : 'bg-slate-800 hover:bg-slate-700 text-slate-300'
              }`}
            >
              <CheckCircle2 className="w-3.5 h-3.5" />
              <span>{showAnswers ? 'Solutions Visible' : 'Show Solutions'}</span>
            </button>

            <button
              onClick={handleDownloadPaper}
              className="px-3 py-1.5 rounded-xl bg-blue-600 hover:bg-blue-500 text-white text-xs font-bold flex items-center gap-1.5 shadow-md shadow-blue-600/20 transition-colors"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download Paper</span>
            </button>

            <button
              onClick={handlePrint}
              className="p-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-white transition-colors"
              title="Print Examination Paper"
            >
              <Printer className="w-4 h-4" />
            </button>

            <button
              onClick={onClose}
              className="p-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-white transition-colors"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Action Callout Bar */}
        <div className="px-5 py-3 bg-blue-50 dark:bg-blue-950/40 border-b border-blue-100 dark:border-blue-900/50 flex flex-wrap items-center justify-between gap-3 text-xs shrink-0 print:hidden">
          <div className="flex items-center gap-2 text-blue-900 dark:text-blue-200">
            <Clock className="w-4 h-4 text-blue-600 dark:text-blue-400 shrink-0" />
            <span>
              Official accredited past examination paper ({pq.questions?.length || pq.questionCount} Questions total)
            </span>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={() => onSearchBrowserForCourse(pq.courseCode)}
              className="px-3 py-1 rounded-xl bg-white dark:bg-slate-800 text-blue-700 dark:text-blue-300 font-bold text-xs border border-blue-200 dark:border-blue-800 hover:bg-blue-100/50 transition-colors flex items-center gap-1"
            >
              <Globe className="w-3.5 h-3.5" />
              <span>Search Browser for More Years</span>
            </button>

            <button
              onClick={() => {
                onClose();
                onStartCbt(pq);
              }}
              className="px-3 py-1 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white font-bold text-xs flex items-center gap-1 shadow-sm transition-colors"
            >
              <Play className="w-3 h-3 fill-current" />
              <span>Practice in CBT Simulator</span>
            </button>
          </div>
        </div>

        {/* Exam Paper Printable Content */}
        <div className="p-6 sm:p-10 overflow-y-auto space-y-8 flex-1 font-serif bg-white dark:bg-slate-900 text-slate-900 dark:text-slate-100">
          
          {/* Official University Paper Header */}
          <div className="text-center pb-6 border-b-2 border-slate-900 dark:border-slate-100 space-y-1">
            <h1 className="text-base sm:text-xl font-black uppercase tracking-wider font-sans">
              {pq.institutionName}
            </h1>
            <h2 className="text-xs sm:text-sm font-bold uppercase tracking-wide font-sans text-slate-700 dark:text-slate-300">
              {pq.faculty}
            </h2>
            <h3 className="text-xs sm:text-sm font-bold uppercase tracking-wide font-sans text-slate-600 dark:text-slate-400">
              DEPARTMENT OF {pq.department}
            </h3>
            <p className="text-xs sm:text-sm font-semibold pt-1 font-sans">
              {pq.sessionYear} ACADEMIC SESSION • {pq.semester.toUpperCase()}
            </p>

            <div className="pt-4 grid grid-cols-2 sm:grid-cols-4 gap-2 text-xs font-sans text-left border-t border-slate-200 dark:border-slate-800 mt-3 pt-3">
              <div>
                <span className="text-slate-500 block text-[10px]">COURSE CODE:</span>
                <strong className="text-slate-900 dark:text-white">{pq.courseCode}</strong>
              </div>
              <div>
                <span className="text-slate-500 block text-[10px]">LEVEL:</span>
                <strong className="text-slate-900 dark:text-white">{pq.level}</strong>
              </div>
              <div>
                <span className="text-slate-500 block text-[10px]">TIME ALLOWED:</span>
                <strong className="text-slate-900 dark:text-white">{pq.timeAllowed || '2 Hours 30 Mins'}</strong>
              </div>
              <div>
                <span className="text-slate-500 block text-[10px]">EXAM TYPE:</span>
                <strong className="text-slate-900 dark:text-white">{pq.examType}</strong>
              </div>
            </div>

            {/* Examination Instructions */}
            <div className="mt-3 p-3 rounded-xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-800 text-left font-sans text-xs">
              <strong className="text-slate-900 dark:text-white block mb-0.5">INSTRUCTIONS TO CANDIDATES:</strong>
              <p className="text-slate-600 dark:text-slate-300">
                {pq.instructions || 'Answer ALL questions in Section A (Objective) and any THREE (3) questions in Section B (Theory). Ensure your Matriculation Number is clearly endorsed on all script answer booklets.'}
              </p>
            </div>
          </div>

          {/* SECTION A: OBJECTIVE QUESTIONS */}
          <div className="space-y-6">
            <div className="flex items-center justify-between border-b pb-2 border-slate-300 dark:border-slate-700 font-sans">
              <h4 className="text-sm sm:text-base font-extrabold uppercase tracking-wide">
                SECTION A: OBJECTIVE & MULTIPLE CHOICE QUESTIONS
              </h4>
              <span className="text-xs font-bold text-slate-500">
                ({pq.questions?.length || 0} Questions)
              </span>
            </div>

            <div className="space-y-6 font-sans">
              {pq.questions && pq.questions.length > 0 ? (
                pq.questions.map((q, qIdx) => {
                  const isSolutionOpen = showAnswers || expandedSolutions[qIdx];
                  return (
                    <div
                      key={qIdx}
                      className="p-4 rounded-2xl bg-slate-50/70 dark:bg-slate-800/40 border border-slate-200/80 dark:border-slate-800 space-y-3"
                    >
                      <div className="flex items-start justify-between gap-3">
                        <p className="text-xs sm:text-sm font-bold text-slate-900 dark:text-white leading-relaxed">
                          <span className="text-blue-600 dark:text-blue-400 font-extrabold mr-1.5">
                            Q{qIdx + 1}.
                          </span>
                          {q.question || q.questionText}
                        </p>

                        <button
                          onClick={() => toggleSolution(qIdx)}
                          className="text-[11px] font-bold text-blue-600 dark:text-blue-400 hover:underline shrink-0 flex items-center gap-0.5 print:hidden"
                        >
                          <span>{isSolutionOpen ? 'Hide' : 'Answer'}</span>
                          {isSolutionOpen ? <ChevronUp className="w-3 h-3" /> : <ChevronDown className="w-3 h-3" />}
                        </button>
                      </div>

                      {/* Options Grid */}
                      {q.options && (
                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs">
                          {q.options.map((opt, optIdx) => {
                            const isCorrect = isSolutionOpen && q.correctOption === optIdx;
                            const letter = String.fromCharCode(65 + optIdx);
                            return (
                              <div
                                key={optIdx}
                                className={`p-2.5 rounded-xl border flex items-center gap-2.5 transition-colors ${
                                  isCorrect
                                    ? 'bg-emerald-50 dark:bg-emerald-950/60 border-emerald-500 text-emerald-900 dark:text-emerald-200 font-bold'
                                    : 'bg-white dark:bg-slate-800 border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-300'
                                }`}
                              >
                                <span className={`w-5 h-5 rounded-md flex items-center justify-center font-bold text-[10px] ${
                                  isCorrect
                                    ? 'bg-emerald-500 text-white'
                                    : 'bg-slate-100 dark:bg-slate-700 text-slate-600 dark:text-slate-300'
                                }`}>
                                  {letter}
                                </span>
                                <span className="flex-1">{opt}</span>
                              </div>
                            );
                          })}
                        </div>
                      )}

                      {/* Explanation box */}
                      {isSolutionOpen && (
                        <div className="p-3 rounded-xl bg-emerald-50/80 dark:bg-emerald-950/40 border border-emerald-200 dark:border-emerald-800/60 text-xs text-emerald-900 dark:text-emerald-200 space-y-1">
                          <div className="flex items-center gap-1 font-extrabold text-emerald-800 dark:text-emerald-300">
                            <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600" />
                            <span>
                              Correct Option: [{String.fromCharCode(65 + (q.correctOption || 0))}] {q.options ? q.options[q.correctOption || 0] : ''}
                            </span>
                          </div>
                          {q.explanation && (
                            <p className="text-[11px] text-slate-600 dark:text-slate-300 pt-0.5 leading-relaxed">
                              <strong>Examiner's Note:</strong> {q.explanation}
                            </p>
                          )}
                        </div>
                      )}
                    </div>
                  );
                })
              ) : (
                <p className="text-xs text-slate-500 italic">No objective questions indexed for this paper.</p>
              )}
            </div>
          </div>

          {/* SECTION B: THEORY & ESSAY QUESTIONS */}
          <div className="space-y-6 pt-4">
            <div className="flex items-center justify-between border-b pb-2 border-slate-300 dark:border-slate-700 font-sans">
              <h4 className="text-sm sm:text-base font-extrabold uppercase tracking-wide">
                SECTION B: ESSAY & THEORY QUESTIONS
              </h4>
              <span className="text-xs font-bold text-slate-500">[50 MARKS TOTAL]</span>
            </div>

            <div className="space-y-6 font-sans">
              {(pq.theoryQuestions && pq.theoryQuestions.length > 0 ? pq.theoryQuestions : [
                {
                  id: 1,
                  questionNumber: 1,
                  marks: 20,
                  questionText: `(a) Clearly define the primary scope, core paradigms, and operational significance of ${pq.courseCode} in modern industrial practice [6 Marks].\n(b) With the aid of a well-labeled schematic diagram or mathematical formulation, derive the foundational principles under steady-state conditions [8 Marks].\n(c) Discuss two common empirical constraints encountered in local Nigerian implementation [6 Marks].`,
                  solutionGuide: `(a) Candidate should articulate exact definitions, boundary limits, and cite relevant standards.\n(b) Correct labeled diagram (3 marks), derivation steps (3 marks), final equation form (2 marks).\n(c) Outline power infrastructure latency, calibration tolerances, and maintenance constraints (3 marks each).`
                },
                {
                  id: 2,
                  questionNumber: 2,
                  marks: 20,
                  questionText: `(a) Differentiate comprehensively between empirical design approaches and analytical simulation techniques relevant to this course [10 Marks].\n(b) Given typical departmental laboratory baseline figures, calculate the resultant efficiency and write a brief analytical justification [10 Marks].`,
                  solutionGuide: `(a) Comparison table showing: accuracy, computational cost, data dependencies, and failure modes.\n(b) Step 1: State formulas. Step 2: Substitute parameters. Step 3: Compute final value with appropriate SI units.`
                },
                {
                  id: 3,
                  questionNumber: 3,
                  marks: 20,
                  questionText: `Explain in detail the legal, professional, and ethical responsibilities of a certified practitioner operating within the Nigerian tertiary or corporate ecosystem [20 Marks].`,
                  solutionGuide: `Candidate should discuss standard regulatory bodies (COREN/ICAN/NBA/MLSCN/NUC/NBTE), duty of care, confidentiality, anti-corruption compliance, and public safety.`
                }
              ]).map((tq, tIdx) => {
                const isSolOpen = showAnswers || expandedSolutions[100 + tIdx];
                return (
                  <div
                    key={tIdx}
                    className="p-5 rounded-2xl bg-slate-50/70 dark:bg-slate-800/40 border border-slate-200/80 dark:border-slate-800 space-y-3"
                  >
                    <div className="flex items-start justify-between gap-3">
                      <div>
                        <span className="text-xs font-black uppercase text-blue-600 dark:text-blue-400">
                          QUESTION {tq.questionNumber} [{tq.marks} MARKS]
                        </span>
                        <div className="text-xs sm:text-sm font-medium text-slate-800 dark:text-slate-200 mt-1 whitespace-pre-line leading-relaxed">
                          {tq.questionText}
                        </div>
                      </div>

                      <button
                        onClick={() => toggleSolution(100 + tIdx)}
                        className="text-[11px] font-bold text-blue-600 dark:text-blue-400 hover:underline shrink-0 flex items-center gap-0.5 print:hidden"
                      >
                        <span>{isSolOpen ? 'Hide' : 'Marking Guide'}</span>
                        {isSolOpen ? <ChevronUp className="w-3 h-3" /> : <ChevronDown className="w-3 h-3" />}
                      </button>
                    </div>

                    {isSolOpen && tq.solutionGuide && (
                      <div className="p-3.5 rounded-xl bg-purple-50/70 dark:bg-purple-950/40 border border-purple-200 dark:border-purple-900/60 text-xs space-y-1 text-purple-950 dark:text-purple-200">
                        <span className="font-extrabold flex items-center gap-1.5">
                          <Sparkles className="w-3.5 h-3.5 text-purple-600" />
                          Model Marking Scheme & Examiners Rubric:
                        </span>
                        <p className="whitespace-pre-line text-[11px] text-slate-700 dark:text-slate-300 leading-relaxed">
                          {tq.solutionGuide}
                        </p>
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>

          {/* Paper Footer Attribution */}
          <div className="pt-6 border-t border-slate-200 dark:border-slate-800 text-[11px] font-sans text-slate-500 flex flex-col sm:flex-row items-center justify-between gap-2">
            <div className="flex items-center gap-1.5">
              <ShieldCheck className="w-4 h-4 text-blue-500" />
              <span>Source: {pq.source}</span>
            </div>
            <div className="italic">
              {pq.copyrightNotice || 'Fair-use academic revision document.'}
            </div>
          </div>

        </div>

        {/* Bottom Bar */}
        <div className="p-4 bg-slate-50 dark:bg-slate-800/80 border-t border-slate-200 dark:border-slate-800 flex items-center justify-between text-xs shrink-0 print:hidden">
          <span className="text-slate-500">
            Press <strong>Download Paper</strong> for an offline editable copy.
          </span>
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-xl bg-slate-200 dark:bg-slate-700 hover:bg-slate-300 dark:hover:bg-slate-600 font-bold text-slate-700 dark:text-slate-200 transition-colors"
          >
            Close Viewer
          </button>
        </div>
      </motion.div>
    </div>
  );
};
