const fs = require('fs');
const path = require('path');

const rawInstitutions = [
  // ==========================================
  // 1. ABIA STATE (South East)
  // ==========================================
  {
    id: 'mouau',
    name: 'Michael Okpara University of Agriculture, Umudike',
    shortName: 'MOUAU',
    type: 'Federal University',
    ownership: 'Federal',
    state: 'Abia',
    city: 'Umudike, Umuahia',
    geopoliticalZone: 'South East',
    establishedYear: 1992,
    motto: 'Knowledge, Food and Security',
    logoColor: '#2e7d32',
    gradingSystem: '5.0',
    websiteUrl: 'https://mouau.edu.ng',
    portalUrl: 'https://portal.mouau.edu.ng',
    regulator: 'NUC',
    accreditationStatus: 'Full Accreditation',
    verificationStatus: 'Verified',
    sourceUrl: 'https://www.nuc.edu.ng/nigerian-univerisities/federal-universities/',
    lastVerified: '2024-06-15',
    isDemo: false,
    description: 'Premier federal specialized agricultural and technological university in South East Nigeria with strong engineering, sciences, veterinary medicine, and management faculties.',
    faculties: [
      'College of Physical and Applied Sciences',
      'College of Engineering and Engineering Technology',
      'College of Agricultural Economics, Rural Sociology and Extension',
      'College of Animal Science and Animal Production',
      'College of Crop and Soil Sciences',
      'College of Veterinary Medicine',
      'College of Management Sciences',
      'College of Education'
    ]
  },
  {
    id: 'absu',
    name: 'Abia State University',
    shortName: 'ABSU',
    type: 'State University',
    ownership: 'State',
    state: 'Abia',
    city: 'Uturu',
    geopoliticalZone: 'South East',
    establishedYear: 1981,
    motto: 'Excellence and Service',
    logoColor: '#004d40',
    gradingSystem: '5.0',
    websiteUrl: 'https://abiastateuniversity.edu.ng',
    portalUrl: 'https://portal.abiastateuniversity.edu.ng',
    regulator: 'NUC',
    accreditationStatus: 'Full Accreditation',
    verificationStatus: 'Verified',
    sourceUrl: 'https://www.nuc.edu.ng/nigerian-univerisities/state-universities/',
    lastVerified: '2024-06-15',
    isDemo: false,
    description: 'Premier state university in Abia State, acclaimed for its college of medicine, law, business administration, optometry, and biological sciences.',
    faculties: [
      'College of Medicine & Health Sciences',
      'Faculty of Law',
      'Faculty of Biological Sciences',
      'Faculty of Physical Sciences',
      'Faculty of Business Administration',
      'Faculty of Social Sciences',
      'Faculty of Environmental Studies',
      'Faculty of Agriculture',
      'Faculty of Education'
    ]
  },
  {
    id: 'gregory_uni',
    name: 'Gregory University, Uturu',
    shortName: 'GUU',
    type: 'Private University',
    ownership: 'Private',
    state: 'Abia',
    city: 'Uturu',
    geopoliticalZone: 'South East',
    establishedYear: 2012,
    motto: 'Knowledge for Tomorrow',
    logoColor: '#1565c0',
    gradingSystem: '5.0',
    websiteUrl: 'https://gregoryuniversity.edu.ng',
    portalUrl: 'https://portal.gregoryuniversity.edu.ng',
    regulator: 'NUC',
    accreditationStatus: 'Full Accreditation',
    verificationStatus: 'Verified',
    sourceUrl: 'https://www.nuc.edu.ng/nigerian-univerisities/private-universities/',
    lastVerified: '2024-06-15',
    isDemo: false,
    description: 'Renowned private university established by the Gregory Iyke Foundation, acclaimed for medicine, engineering, law, and business innovations.',
    faculties: [
      'College of Medicine and Health Sciences',
      'College of Engineering',
      'College of Law',
      'College of Natural and Applied Sciences',
      'College of Social and Management Sciences'
    ]
  },
  {
    id: 'clifford_uni',
    name: 'Clifford University, Owerrinta',
    shortName: 'CLU',
    type: 'Private University',
    ownership: 'Private',
    state: 'Abia',
    city: 'Ihie, Owerrinta',
    geopoliticalZone: 'South East',
    establishedYear: 2013,
    motto: 'Knowledge, Truth and Service',
    logoColor: '#4527a0',
    gradingSystem: '5.0',
    websiteUrl: 'https://clifforduni.edu.ng',
    portalUrl: 'https://portal.clifforduni.edu.ng',
    regulator: 'NUC',
    accreditationStatus: 'Full Accreditation',
    verificationStatus: 'Verified',
    sourceUrl: 'https://www.nuc.edu.ng/nigerian-univerisities/private-universities/',
    lastVerified: '2024-06-15',
    isDemo: false,
    description: 'Seventh-day Adventist private university known for holistic academic character formation, science, and nursing education.',
    faculties: [
      'Faculty of Science and Computing',
      'Faculty of Social and Management Sciences',
      'Faculty of Humanities',
      'Faculty of Basic Medical Sciences'
    ]
  },
  {
    id: 'abia_poly',
    name: 'Abia State Polytechnic, Aba',
    shortName: 'ABIAPOLY',
    type: 'State Polytechnic',
    ownership: 'State',
    state: 'Abia',
    city: 'Aba',
    geopoliticalZone: 'South East',
    establishedYear: 1992,
    motto: 'Technology for Self Reliance',
    logoColor: '#c2185b',
    gradingSystem: '4.0',
    websiteUrl: 'https://abiapoly.edu.ng',
    portalUrl: 'https://portal.abiapoly.edu.ng',
    regulator: 'NBTE',
    accreditationStatus: 'Full Accreditation',
    verificationStatus: 'Verified',
    sourceUrl: 'https://nbte.gov.ng/polytechnics',
    lastVerified: '2024-06-15',
    isDemo: false,
    description: 'Major state polytechnic located in commercial city of Aba, training technologists in engineering, computer science, business studies, and science laboratory technology.',
    faculties: [
      'School of Engineering Technology',
      'School of Science & Industrial Technology',
      'School of Business & Management Studies',
      'School of Environmental Design Technology'
    ]
  },
  {
    id: 'asceta_arochukwu',
    name: 'Abia State College of Education (Technical), Arochukwu',
    shortName: 'ASCETA',
    type: 'State College of Education',
    ownership: 'State',
    state: 'Abia',
    city: 'Arochukwu',
    geopoliticalZone: 'South East',
    establishedYear: 1993,
    motto: 'Teaching for Technological Breakthrough',
    logoColor: '#00796b',
    gradingSystem: '4.0',
    websiteUrl: 'https://asceta.edu.ng',
    regulator: 'NCCE',
    accreditationStatus: 'Accredited',
    verificationStatus: 'Verified',
    sourceUrl: 'https://ncceonline.edu.ng',
    lastVerified: '2024-06-15',
    isDemo: false,
    description: 'Accredited state technical teacher training college offering NCE programmes in vocational and technical education, sciences, and primary education.',
    faculties: [
      'School of Technical Education',
      'School of Vocational Education',
      'School of Sciences',
      'School of Education'
    ]
  },
  {
    id: 'abia_health_aba',
    name: 'Abia State College of Health Sciences and Management Technology',
    shortName: 'ASCOHMAT',
    type: 'College of Health Sciences and Technology',
    ownership: 'State',
    state: 'Abia',
    city: 'Aba',
    geopoliticalZone: 'South East',
    establishedYear: 2007,
    motto: 'Skillful Health Care for Humanity',
    logoColor: '#0288d1',
    gradingSystem: '4.0',
    websiteUrl: 'https://ascoht.edu.ng',
    regulator: 'NBTE',
    accreditationStatus: 'Accredited',
    verificationStatus: 'Verified',
    sourceUrl: 'https://nbte.gov.ng',
    lastVerified: '2024-06-15',
    isDemo: false,
    description: 'Health technology institute in Aba training practitioners in community health, medical laboratory technology, environmental health, and health information management.',
    faculties: [
      'Department of Community Health Sciences',
      'Department of Medical Laboratory Sciences',
      'Department of Environmental Health Sciences',
      'Department of Health Information Management'
    ]
  },

  // ==========================================
  // 2. ADAMAWA STATE (North East)
  // ==========================================
  {
    id: 'mau_yola',
    name: 'Modibbo Adama University, Yola',
    shortName: 'MAU',
    type: 'Federal University',
    ownership: 'Federal',
    state: 'Adamawa',
    city: 'Girei, Yola',
    geopoliticalZone: 'North East',
    establishedYear: 1981,
    motto: 'Technology for Development',
    logoColor: '#1b5e20',
    gradingSystem: '5.0',
    websiteUrl: 'https://mau.edu.ng',
    portalUrl: 'https://portal.mau.edu.ng',
    regulator: 'NUC',
    accreditationStatus: 'Full Accreditation',
    verificationStatus: 'Verified',
    sourceUrl: 'https://www.nuc.edu.ng/nigerian-univerisities/federal-universities/',
    lastVerified: '2024-06-15',
    isDemo: false,
    description: 'Formerly MAUTECH, converted to a comprehensive federal university, leading in engineering, computing, medical sciences, physical sciences, and agriculture.',
    faculties: [
      'Faculty of Engineering',
      'Faculty of Physical Sciences',
      'Faculty of Life Sciences',
      'College of Medical Sciences',
      'Faculty of Agriculture',
      'Faculty of Social and Management Sciences',
      'Faculty of Environmental Sciences',
      'Faculty of Education'
    ]
  },
  {
    id: 'adsu_mubi',
    name: 'Adamawa State University, Mubi',
    shortName: 'ADSU',
    type: 'State University',
    ownership: 'State',
    state: 'Adamawa',
    city: 'Mubi',
    geopoliticalZone: 'North East',
    establishedYear: 2002,
    motto: 'Education for Development',
    logoColor: '#00695c',
    gradingSystem: '5.0',
    websiteUrl: 'https://adsu.edu.ng',
    portalUrl: 'https://adsu.safsrms.com',
    regulator: 'NUC',
    accreditationStatus: 'Full Accreditation',
    verificationStatus: 'Verified',
    sourceUrl: 'https://www.nuc.edu.ng/nigerian-univerisities/state-universities/',
    lastVerified: '2024-06-15',
    isDemo: false,
    description: 'Premier state university in Adamawa State situated in Mubi, delivering courses in computer science, agriculture, pure sciences, and administration.',
    faculties: [
      'Faculty of Science',
      'Faculty of Agriculture',
      'Faculty of Social & Management Sciences',
      'Faculty of Arts and Humanities',
      'Faculty of Education'
    ]
  },
  {
    id: 'aun_yola',
    name: 'American University of Nigeria, Yola',
    shortName: 'AUN',
    type: 'Private University',
    ownership: 'Private',
    state: 'Adamawa',
    city: 'Yola',
    geopoliticalZone: 'North East',
    establishedYear: 2004,
    motto: 'Development University for Africa',
    logoColor: '#0d47a1',
    gradingSystem: '4.0',
    websiteUrl: 'https://aun.edu.ng',
    portalUrl: 'https://open.aun.edu.ng',
    regulator: 'NUC',
    accreditationStatus: 'Full Accreditation',
    verificationStatus: 'Verified',
    sourceUrl: 'https://www.nuc.edu.ng/nigerian-univerisities/private-universities/',
    lastVerified: '2024-06-15',
    isDemo: false,
    description: 'First American-style liberal arts university in Sub-Saharan Africa, offering world-class technology, software engineering, law, and business programmes.',
    faculties: [
      'School of Information Technology & Computing',
      'School of Business & Entrepreneurship',
      'School of Law',
      'School of Arts & Sciences',
      'School of Engineering'
    ]
  },
  {
    id: 'fedpoly_mubi',
    name: 'Federal Polytechnic, Mubi',
    shortName: 'FPM',
    type: 'Federal Polytechnic',
    ownership: 'Federal',
    state: 'Adamawa',
    city: 'Mubi',
    geopoliticalZone: 'North East',
    establishedYear: 1979,
    motto: 'Knowledge and Skill for Service',
    logoColor: '#b71c1c',
    gradingSystem: '4.0',
    websiteUrl: 'https://fpmubionline.edu.ng',
    portalUrl: 'https://portal.fpmubionline.edu.ng',
    regulator: 'NBTE',
    accreditationStatus: 'Full Accreditation',
    verificationStatus: 'Verified',
    sourceUrl: 'https://nbte.gov.ng/polytechnics',
    lastVerified: '2024-06-15',
    isDemo: false,
    description: 'Prominent federal polytechnic in North East Nigeria, offering accredited National Diploma and Higher National Diploma curricula.',
    faculties: [
      'School of Engineering Technology',
      'School of Science and Technology',
      'School of Business and Management Technology',
      'School of Environmental Science and Technology',
      'School of Agricultural Technology'
    ]
  },
  {
    id: 'adamawa_poly_yola',
    name: 'Adamawa State Polytechnic, Yola',
    shortName: 'SPYOLA',
    type: 'State Polytechnic',
    ownership: 'State',
    state: 'Adamawa',
    city: 'Yola',
    geopoliticalZone: 'North East',
    establishedYear: 1991,
    motto: 'Technology for Self Reliance',
    logoColor: '#e65100',
    gradingSystem: '4.0',
    websiteUrl: 'https://adamawapoly.edu.ng',
    regulator: 'NBTE',
    accreditationStatus: 'Accredited',
    verificationStatus: 'Verified',
    sourceUrl: 'https://nbte.gov.ng/polytechnics',
    lastVerified: '2024-06-15',
    isDemo: false,
    description: 'State polytechnic in Yola training students in engineering, computing, administrative studies, and community technology.',
    faculties: [
      'School of Engineering',
      'School of Science and Technology',
      'School of Administration and Business Studies',
      'School of Environmental Studies'
    ]
  },
  {
    id: 'fce_yola',
    name: 'Federal College of Education, Yola',
    shortName: 'FCE Yola',
    type: 'Federal College of Education',
    ownership: 'Federal',
    state: 'Adamawa',
    city: 'Yola',
    geopoliticalZone: 'North East',
    establishedYear: 1974,
    motto: 'Excellence in Teacher Education',
    logoColor: '#303f9f',
    gradingSystem: '4.0',
    websiteUrl: 'https://fceyola.edu.ng',
    regulator: 'NCCE',
    accreditationStatus: 'Full Accreditation',
    verificationStatus: 'Verified',
    sourceUrl: 'https://ncceonline.edu.ng',
    lastVerified: '2024-06-15',
    isDemo: false,
    description: 'Federal teacher education institution in Yola training qualified teachers in sciences, vocational arts, languages, and primary education.',
    faculties: [
      'School of Sciences',
      'School of Vocational Education',
      'School of Languages',
      'School of Arts and Social Sciences',
      'School of Education'
    ]
  },
  {
    id: 'adamawa_nursing_yola',
    name: 'Adamawa State College of Nursing Sciences, Yola',
    shortName: 'ADCONSY',
    type: 'College of Nursing Sciences',
    ownership: 'State',
    state: 'Adamawa',
    city: 'Yola',
    geopoliticalZone: 'North East',
    establishedYear: 1977,
    motto: 'Care with Compassion and Skill',
    logoColor: '#00838f',
    gradingSystem: '4.0',
    websiteUrl: 'https://conmyola.edu.ng',
    regulator: 'NMCN',
    accreditationStatus: 'Accredited',
    verificationStatus: 'Verified',
    sourceUrl: 'https://www.nmcn.gov.ng',
    lastVerified: '2024-06-15',
    isDemo: false,
    description: 'Official state college providing registered nursing (RN) and registered midwifery (RM) training accredited by NMCN.',
    faculties: [
      'Department of General Nursing',
      'Department of Basic Midwifery',
      'Department of Public Health Nursing'
    ]
  },

  // ==========================================
  // 3. AKWA IBOM STATE (South South)
  // ==========================================
  {
    id: 'uniuyo',
    name: 'University of Uyo',
    shortName: 'UNIUYO',
    type: 'Federal University',
    ownership: 'Federal',
    state: 'Akwa Ibom',
    city: 'Uyo',
    geopoliticalZone: 'South South',
    establishedYear: 1991,
    motto: 'Unity, Learning and Service',
    logoColor: '#004d40',
    gradingSystem: '5.0',
    websiteUrl: 'https://uniuyo.edu.ng',
    portalUrl: 'https://uniuyo.edu.ng/eportals',
    regulator: 'NUC',
    accreditationStatus: 'Full Accreditation',
    verificationStatus: 'Verified',
    sourceUrl: 'https://www.nuc.edu.ng/nigerian-univerisities/federal-universities/',
    lastVerified: '2024-06-15',
    isDemo: false,
    description: 'Premier federal university in Akwa Ibom State, acclaimed for engineering, medical sciences, pharmacy, law, arts, and agriculture.',
    faculties: [
      'Faculty of Engineering',
      'Faculty of Science',
      'Faculty of Clinical Sciences',
      'Faculty of Pharmacy',
      'Faculty of Law',
      'Faculty of Management Sciences',
      'Faculty of Social Sciences',
      'Faculty of Agriculture',
      'Faculty of Environmental Studies',
      'Faculty of Arts',
      'Faculty of Education'
    ]
  },
  {
    id: 'aksu',
    name: 'Akwa Ibom State University',
    shortName: 'AKSU',
    type: 'State University',
    ownership: 'State',
    state: 'Akwa Ibom',
    city: 'Ikot Akpaden, Mkpat Enin',
    geopoliticalZone: 'South South',
    establishedYear: 2010,
    motto: 'Excellence in Science and Technology',
    logoColor: '#0d47a1',
    gradingSystem: '5.0',
    websiteUrl: 'https://aksu.edu.ng',
    portalUrl: 'https://portal.aksu.edu.ng',
    regulator: 'NUC',
    accreditationStatus: 'Full Accreditation',
    verificationStatus: 'Verified',
    sourceUrl: 'https://www.nuc.edu.ng/nigerian-univerisities/state-universities/',
    lastVerified: '2024-06-15',
    isDemo: false,
    description: 'Multi-campus state university with campuses at Ikot Akpaden (Main Campus) and Obio Akpa (Arts & Agriculture).',
    faculties: [
      'Faculty of Engineering',
      'Faculty of Physical Sciences',
      'Faculty of Biological Sciences',
      'Faculty of Management Sciences',
      'Faculty of Agriculture',
      'Faculty of Arts',
      'Faculty of Social Sciences',
      'Faculty of Education'
    ]
  },
  {
    id: 'topfaith_uni',
    name: 'Topfaith University, Mkpatak',
    shortName: 'Topfaith',
    type: 'Private University',
    ownership: 'Private',
    state: 'Akwa Ibom',
    city: 'Mkpatak, Essien Udim',
    geopoliticalZone: 'South South',
    establishedYear: 2021,
    motto: 'Discover, Develop, Deploy',
    logoColor: '#6a1b9a',
    gradingSystem: '5.0',
    websiteUrl: 'https://topfaith.edu.ng',
    portalUrl: 'https://portal.topfaith.edu.ng',
    regulator: 'NUC',
    accreditationStatus: 'Accredited',
    verificationStatus: 'Verified',
    sourceUrl: 'https://www.nuc.edu.ng/nigerian-univerisities/private-universities/',
    lastVerified: '2024-06-15',
    isDemo: false,
    description: 'Modern private university in Akwa Ibom recognized for cutting-edge computing, engineering, law, and management curricula.',
    faculties: [
      'Faculty of Computing and Applied Sciences',
      'Faculty of Engineering',
      'Faculty of Law',
      'Faculty of Management and Social Sciences'
    ]
  },
  {
    id: 'fedpoly_ukana',
    name: 'Federal Polytechnic, Ukana',
    shortName: 'FEDPOUK',
    type: 'Federal Polytechnic',
    ownership: 'Federal',
    state: 'Akwa Ibom',
    city: 'Ukana, Essien Udim',
    geopoliticalZone: 'South South',
    establishedYear: 2014,
    motto: 'Technological Excellence for Humanity',
    logoColor: '#b71c1c',
    gradingSystem: '4.0',
    websiteUrl: 'https://fedpolyukana.edu.ng',
    regulator: 'NBTE',
    accreditationStatus: 'Accredited',
    verificationStatus: 'Verified',
    sourceUrl: 'https://nbte.gov.ng/polytechnics',
    lastVerified: '2024-06-15',
    isDemo: false,
    description: 'Federal technical polytechnic delivering accredited ND programmes in computer science, statistics, electrical engineering, and civil technology.',
    faculties: [
      'School of Applied Sciences',
      'School of Engineering Technology',
      'School of Management Studies'
    ]
  },
  {
    id: 'akwa_ibom_poly',
    name: 'Akwa Ibom State Polytechnic, Ikot Osurua',
    shortName: 'AKWAPOLY',
    type: 'State Polytechnic',
    ownership: 'State',
    state: 'Akwa Ibom',
    city: 'Ikot Osurua, Ikot Ekpene',
    geopoliticalZone: 'South South',
    establishedYear: 1991,
    motto: 'Technology for Development',
    logoColor: '#2e7d32',
    gradingSystem: '4.0',
    websiteUrl: 'https://akwaibompoly.edu.ng',
    portalUrl: 'https://portal.akwaibompoly.edu.ng',
    regulator: 'NBTE',
    accreditationStatus: 'Full Accreditation',
    verificationStatus: 'Verified',
    sourceUrl: 'https://nbte.gov.ng/polytechnics',
    lastVerified: '2024-06-15',
    isDemo: false,
    description: 'Premier state polytechnic located in Ikot Ekpene, producing technical leaders in engineering, sciences, and communication.',
    faculties: [
      'School of Applied Sciences',
      'School of Engineering',
      'School of Business Studies',
      'School of Environmental Studies',
      'School of Communication Arts'
    ]
  },
  {
    id: 'man_oron',
    name: 'Maritime Academy of Nigeria',
    shortName: 'MAN Oron',
    type: 'Monotechnic / Specialized Institution',
    ownership: 'Federal',
    state: 'Akwa Ibom',
    city: 'Oron',
    geopoliticalZone: 'South South',
    establishedYear: 1977,
    motto: 'Excellence in Maritime Training',
    logoColor: '#01579b',
    gradingSystem: '4.0',
    websiteUrl: 'https://maritimeacademy.gov.ng',
    portalUrl: 'https://application.maritimeacademy.edu.ng',
    regulator: 'NBTE',
    accreditationStatus: 'Full Accreditation',
    verificationStatus: 'Verified',
    sourceUrl: 'https://nbte.gov.ng/monotechnics',
    lastVerified: '2024-06-15',
    isDemo: false,
    description: 'Apex federal maritime training institution providing specialized nautical science, marine engineering, maritime transport, and logistics programmes.',
    faculties: [
      'School of Nautical Studies',
      'School of Marine Engineering',
      'School of Maritime Transport & Business Studies'
    ]
  },
  {
    id: 'fce_ididep',
    name: 'Federal College of Education, Ididep',
    shortName: 'FCE Ididep',
    type: 'Federal College of Education',
    ownership: 'Federal',
    state: 'Akwa Ibom',
    city: 'Ididep, Ibiono Ibom',
    geopoliticalZone: 'South South',
    establishedYear: 2020,
    motto: 'Excellence and Integrity in Teacher Education',
    logoColor: '#00695c',
    gradingSystem: '4.0',
    websiteUrl: 'https://fceididep.edu.ng',
    regulator: 'NCCE',
    accreditationStatus: 'Accredited',
    verificationStatus: 'Verified',
    sourceUrl: 'https://ncceonline.edu.ng',
    lastVerified: '2024-06-15',
    isDemo: false,
    description: 'Modern federal teacher training institution offering NCE programmes in foundational teaching, vocational disciplines, and STEM education.',
    faculties: [
      'School of Sciences',
      'School of Arts and Social Sciences',
      'School of Vocational and Technical Education',
      'School of Education'
    ]
  },

  // ==========================================
  // 4. ANAMBRA STATE (South East)
  // ==========================================
  {
    id: 'unizik',
    name: 'Nnamdi Azikiwe University, Awka',
    shortName: 'UNIZIK',
    type: 'Federal University',
    ownership: 'Federal',
    state: 'Anambra',
    city: 'Awka',
    geopoliticalZone: 'South East',
    establishedYear: 1991,
    motto: 'Discipline, Self-Reliance and Excellence',
    logoColor: '#e65100',
    gradingSystem: '5.0',
    websiteUrl: 'https://unizik.edu.ng',
    portalUrl: 'https://my.unizik.edu.ng',
    regulator: 'NUC',
    accreditationStatus: 'Full Accreditation',
    verificationStatus: 'Verified',
    sourceUrl: 'https://www.nuc.edu.ng/nigerian-univerisities/federal-universities/',
    lastVerified: '2024-06-15',
    isDemo: false,
    description: 'Named after Nigeria\'s first President Dr. Nnamdi Azikiwe, UNIZIK is a powerhouse for engineering, medicine, pharmacy, law, physical sciences, and management.',
    faculties: [
      'Faculty of Engineering',
      'Faculty of Physical Sciences',
      'Faculty of Biosciences',
      'Faculty of Medicine',
      'Faculty of Pharmaceutical Sciences',
      'Faculty of Law',
      'Faculty of Management Sciences',
      'Faculty of Social Sciences',
      'Faculty of Arts',
      'Faculty of Environmental Sciences',
      'Faculty of Education',
      'Faculty of Agriculture'
    ]
  },
  {
    id: 'coou',
    name: 'Chukwuemeka Odumegwu Ojukwu University, Uli',
    shortName: 'COOU',
    type: 'State University',
    ownership: 'State',
    state: 'Anambra',
    city: 'Uli & Igbariam',
    geopoliticalZone: 'South East',
    establishedYear: 2000,
    motto: 'Knowledge for Self-Reliance',
    logoColor: '#283593',
    gradingSystem: '5.0',
    websiteUrl: 'https://coou.edu.ng',
    portalUrl: 'https://portal.coou.edu.ng',
    regulator: 'NUC',
    accreditationStatus: 'Full Accreditation',
    verificationStatus: 'Verified',
    sourceUrl: 'https://www.nuc.edu.ng/nigerian-univerisities/state-universities/',
    lastVerified: '2024-06-15',
    isDemo: false,
    description: 'Premier state university in Anambra State named after Dim Chukwuemeka Odumegwu Ojukwu, with campuses at Uli, Igbariam, and Amaku Awka.',
    faculties: [
      'Faculty of Engineering',
      'Faculty of Natural Sciences',
      'Faculty of Clinical Medicine',
      'Faculty of Law',
      'Faculty of Management Sciences',
      'Faculty of Social Sciences',
      'Faculty of Agriculture',
      'Faculty of Arts',
      'Faculty of Environmental Sciences',
      'Faculty of Education'
    ]
  },
  {
    id: 'paul_uni',
    name: 'Paul University, Awka',
    shortName: 'PaulUni',
    type: 'Private University',
    ownership: 'Private',
    state: 'Anambra',
    city: 'Awka',
    geopoliticalZone: 'South East',
    establishedYear: 2009,
    motto: 'Academic Excellence and Moral Rectitude',
    logoColor: '#4a148c',
    gradingSystem: '5.0',
    websiteUrl: 'https://pauluniversity.edu.ng',
    portalUrl: 'https://portal.pauluniversity.edu.ng',
    regulator: 'NUC',
    accreditationStatus: 'Accredited',
    verificationStatus: 'Verified',
    sourceUrl: 'https://www.nuc.edu.ng/nigerian-univerisities/private-universities/',
    lastVerified: '2024-06-15',
    isDemo: false,
    description: 'Faith-based private Anglican university in Awka providing high moral standards alongside rigorous science, management, and arts education.',
    faculties: [
      'Faculty of Natural and Applied Sciences',
      'Faculty of Management and Social Sciences',
      'Faculty of Arts'
    ]
  },
  {
    id: 'oko_poly',
    name: 'Federal Polytechnic, Oko',
    shortName: 'OKOPOLY',
    type: 'Federal Polytechnic',
    ownership: 'Federal',
    state: 'Anambra',
    city: 'Oko',
    geopoliticalZone: 'South East',
    establishedYear: 1979,
    motto: 'Technology for Self-Sufficiency',
    logoColor: '#006064',
    gradingSystem: '4.0',
    websiteUrl: 'https://federalpolyoko.edu.ng',
    portalUrl: 'https://portal.federalpolyoko.edu.ng',
    regulator: 'NBTE',
    accreditationStatus: 'Full Accreditation',
    verificationStatus: 'Verified',
    sourceUrl: 'https://nbte.gov.ng/polytechnics',
    lastVerified: '2024-06-15',
    isDemo: false,
    description: 'One of Nigeria\'s largest and most famous polytechnics, founded in Oko Anambra State, excelling in business, engineering, and arts.',
    faculties: [
      'School of Engineering Technology',
      'School of Applied Science',
      'School of Business Studies',
      'School of Environmental Design and Technology',
      'School of Information Technology',
      'School of Financial Studies',
      'School of Arts, Design and Printing'
    ]
  },
  {
    id: 'fcet_umunze',
    name: 'Federal College of Education (Technical), Umunze',
    shortName: 'FCET Umunze',
    type: 'Federal College of Education',
    ownership: 'Federal',
    state: 'Anambra',
    city: 'Umunze',
    geopoliticalZone: 'South East',
    establishedYear: 1989,
    motto: 'Education for Self-Reliance and Technological Advancement',
    logoColor: '#2e7d32',
    gradingSystem: '4.0',
    websiteUrl: 'https://fcetumunze.edu.ng',
    portalUrl: 'https://portal.fcetumunze.edu.ng',
    regulator: 'NCCE',
    accreditationStatus: 'Full Accreditation',
    verificationStatus: 'Verified',
    sourceUrl: 'https://ncceonline.edu.ng',
    lastVerified: '2024-06-15',
    isDemo: false,
    description: 'Premier federal technical teacher training institution in South East Nigeria offering accredited NCE and degree affiliated programmes.',
    faculties: [
      'School of Technical Education',
      'School of Vocational Education',
      'School of Sciences',
      'School of Business Education',
      'School of Computer and Information Sciences',
      'School of Education'
    ]
  },
  {
    id: 'nocen_nsugbe',
    name: 'Nwafor Orizu College of Education, Nsugbe',
    shortName: 'NOCEN',
    type: 'State College of Education',
    ownership: 'State',
    state: 'Anambra',
    city: 'Nsugbe, Onitsha',
    geopoliticalZone: 'South East',
    establishedYear: 1976,
    motto: 'Excellence in Teacher Education',
    logoColor: '#c2185b',
    gradingSystem: '4.0',
    websiteUrl: 'https://nocen.edu.ng',
    portalUrl: 'https://portal.nocen.edu.ng',
    regulator: 'NCCE',
    accreditationStatus: 'Full Accreditation',
    verificationStatus: 'Verified',
    sourceUrl: 'https://ncceonline.edu.ng',
    lastVerified: '2024-06-15',
    isDemo: false,
    description: 'Prestigious state college of education named after Dr. Nwafor Orizu, offering NCE and university degree programmes.',
    faculties: [
      'School of Sciences',
      'School of Vocational Education',
      'School of Arts and Social Sciences',
      'School of Languages',
      'School of Education'
    ]
  },
  {
    id: 'anambra_health_obosi',
    name: 'Anambra State College of Health Technology, Obosi',
    shortName: 'ASCOHTECH Obosi',
    type: 'College of Health Sciences and Technology',
    ownership: 'State',
    state: 'Anambra',
    city: 'Obosi, Idemili North',
    geopoliticalZone: 'South East',
    establishedYear: 1992,
    motto: 'Knowledge, Skill and Service in Health Care',
    logoColor: '#00838f',
    gradingSystem: '4.0',
    websiteUrl: 'https://ascohtech.edu.ng',
    regulator: 'NBTE',
    accreditationStatus: 'Accredited',
    verificationStatus: 'Verified',
    sourceUrl: 'https://nbte.gov.ng',
    lastVerified: '2024-06-15',
    isDemo: false,
    description: 'Specialized health science college producing accredited community health extension workers, pharmacy technicians, and lab technologists.',
    faculties: [
      'Department of Community Health',
      'Department of Pharmacy Technician Studies',
      'Department of Medical Laboratory Technician',
      'Department of Environmental Health'
    ]
  }
];

console.log('Total base loaded:', rawInstitutions.length);
