# SOUTH WEST ZONE: Ekiti, Lagos, Ogun, Ondo, Osun, Oyo

DATA = [
  # ----------------------------------------------------
  # EKITI STATE
  # ----------------------------------------------------
  {
    "id": "fuoye",
    "name": "Federal University, Oye-Ekiti",
    "shortName": "FUOYE",
    "type": "Federal University",
    "ownership": "Federal",
    "state": "Ekiti",
    "city": "Oye-Ekiti & Ikole-Ekiti",
    "geopoliticalZone": "South West",
    "establishedYear": 2011,
    "motto": "Innovation and Character for Transformation",
    "logoColor": "#2e7d32",
    "gradingSystem": "5.0",
    "websiteUrl": "https://fuoye.edu.ng",
    "portalUrl": "https://ecampus.fuoye.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/federal-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Rapidly growing federal university with engineering and agriculture at Ikole campus and sciences, law, pharmacy, and arts at Oye campus.",
    "faculties": [
      "Faculty of Engineering",
      "Faculty of Science",
      "Faculty of Law",
      "Faculty of Pharmacy",
      "Faculty of Management Sciences",
      "Faculty of Social Sciences",
      "Faculty of Agriculture",
      "Faculty of Arts",
      "Faculty of Education",
      "Faculty of Environmental Design"
    ]
  },
  {
    "id": "eksu",
    "name": "Ekiti State University, Ado-Ekiti",
    "shortName": "EKSU",
    "type": "State University",
    "ownership": "State",
    "state": "Ekiti",
    "city": "Ado-Ekiti",
    "geopoliticalZone": "South West",
    "establishedYear": 1982,
    "motto": "Knowledge, Honour and Service",
    "logoColor": "#0d47a1",
    "gradingSystem": "5.0",
    "websiteUrl": "https://eksu.edu.ng",
    "portalUrl": "https://eksuportal.eksu.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/state-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Premier state university in Ekiti State renowned for its medical college, law, sciences, engineering, and education.",
    "faculties": [
      "College of Medicine",
      "Faculty of Law",
      "Faculty of Engineering",
      "Faculty of Science",
      "Faculty of Management Sciences",
      "Faculty of Social Sciences",
      "Faculty of Agricultural Science",
      "Faculty of Arts",
      "Faculty of Education"
    ]
  },
  {
    "id": "abuad",
    "name": "Afe Babalola University, Ado-Ekiti",
    "shortName": "ABUAD",
    "type": "Private University",
    "ownership": "Private",
    "state": "Ekiti",
    "city": "Ado-Ekiti",
    "geopoliticalZone": "South West",
    "establishedYear": 2009,
    "motto": "Laborare, Orare et Discere (Labour, Prayer and Learning)",
    "logoColor": "#b71c1c",
    "gradingSystem": "5.0",
    "websiteUrl": "https://abuad.edu.ng",
    "portalUrl": "https://portal.abuad.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/private-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "World-class private university founded by Aare Afe Babalola (SAN), famous for its ultra-modern multisystem teaching hospital, law, engineering, and pharmacy.",
    "faculties": [
      "College of Medicine and Health Sciences",
      "College of Law",
      "College of Engineering",
      "College of Sciences",
      "College of Social and Management Sciences",
      "College of Pharmacy",
      "College of Agriculture"
    ]
  },
  {
    "id": "fedpoly_ado",
    "name": "Federal Polytechnic, Ado-Ekiti",
    "shortName": "FEDPOLYADO",
    "type": "Federal Polytechnic",
    "ownership": "Federal",
    "state": "Ekiti",
    "city": "Ado-Ekiti",
    "geopoliticalZone": "South West",
    "establishedYear": 1977,
    "motto": "Knowledge for Skill and Service",
    "logoColor": "#e65100",
    "gradingSystem": "4.0",
    "websiteUrl": "https://fedpolyado.edu.ng",
    "portalUrl": "https://students.fedpolyado.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/polytechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Prestigious federal polytechnic offering accredited ND and HND engineering, science technology, and business programmes.",
    "faculties": [
      "School of Engineering",
      "School of Science and Computer Studies",
      "School of Business Studies",
      "School of Environmental Studies",
      "School of Agriculture and Agricultural Technology"
    ]
  },
  {
    "id": "ekiti_poly_ikole",
    "name": "Federal College of Education, Iwoye-Ijesa (Ekiti Border)",
    "shortName": "Ekiti COE",
    "type": "State College of Education",
    "ownership": "State",
    "state": "Ekiti",
    "city": "Ikere-Ekiti",
    "geopoliticalZone": "South West",
    "establishedYear": 1977,
    "motto": "Excellence in Teacher Education",
    "logoColor": "#00796b",
    "gradingSystem": "4.0",
    "websiteUrl": "https://coeikere.edu.ng",
    "regulator": "NCCE",
    "accreditationStatus": "Accredited",
    "verificationStatus": "Verified",
    "sourceUrl": "https://ncceonline.edu.ng",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Historical teacher training institution that produced thousands of certified educators across South West Nigeria.",
    "faculties": [
      "School of Sciences",
      "School of Vocational and Technical Education",
      "School of Arts and Social Sciences",
      "School of Languages",
      "School of Education"
    ]
  },
  {
    "id": "ekiti_health_ijero",
    "name": "Ekiti State College of Health Sciences and Technology, Ijero-Ekiti",
    "shortName": "ESCOHTECH Ijero",
    "type": "College of Health Sciences and Technology",
    "ownership": "State",
    "state": "Ekiti",
    "city": "Ijero-Ekiti",
    "geopoliticalZone": "South West",
    "establishedYear": 1997,
    "motto": "Health is Wealth and Wisdom",
    "logoColor": "#00838f",
    "gradingSystem": "4.0",
    "websiteUrl": "https://esctijero.edu.ng",
    "portalUrl": "https://portal.esctijero.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Leading health science college in South West Nigeria offering community health, medical lab science, pharmacy technician, and dental health.",
    "faculties": [
      "Department of Community Health",
      "Department of Pharmacy Technician",
      "Department of Medical Laboratory Science",
      "Department of Environmental Health",
      "Department of Health Information Management"
    ]
  },

  # ----------------------------------------------------
  # LAGOS STATE
  # ----------------------------------------------------
  {
    "id": "unilag",
    "name": "University of Lagos",
    "shortName": "UNILAG",
    "type": "Federal University",
    "ownership": "Federal",
    "state": "Lagos",
    "city": "Akoka, Yaba, Lagos",
    "geopoliticalZone": "South West",
    "establishedYear": 1962,
    "motto": "In Deed and In Truth",
    "logoColor": "#1565c0",
    "gradingSystem": "5.0",
    "websiteUrl": "https://unilag.edu.ng",
    "portalUrl": "https://studentportal.unilag.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/federal-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "One of Nigeria's foremost first-generation universities, located in the commercial capital, renowned for engineering, law, business administration, medicine (CMUL), and computing.",
    "faculties": [
      "College of Medicine",
      "Faculty of Engineering",
      "Faculty of Science",
      "Faculty of Law",
      "Faculty of Management Sciences",
      "Faculty of Social Sciences",
      "Faculty of Arts",
      "Faculty of Environmental Sciences",
      "Faculty of Education",
      "Faculty of Pharmacy",
      "Faculty of Dental Sciences"
    ]
  },
  {
    "id": "lasu",
    "name": "Lagos State University, Ojo",
    "shortName": "LASU",
    "type": "State University",
    "ownership": "State",
    "state": "Lagos",
    "city": "Ojo, Lagos",
    "geopoliticalZone": "South West",
    "establishedYear": 1983,
    "motto": "For Truth and Service",
    "logoColor": "#004d40",
    "gradingSystem": "5.0",
    "websiteUrl": "https://lasu.edu.ng",
    "portalUrl": "https://lid.lasu.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/state-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Flagship Lagos State university ranked among the best universities in Nigeria, famous for medicine (LASUCOM), law, communication, transport, and science.",
    "faculties": [
      "Lagos State University College of Medicine (LASUCOM)",
      "Faculty of Law",
      "Faculty of Engineering",
      "Faculty of Science",
      "Faculty of Management Sciences",
      "Faculty of Social Sciences",
      "Faculty of Arts",
      "School of Communication",
      "School of Transport and Logistics",
      "Faculty of Education"
    ]
  },
  {
    "id": "lasustech",
    "name": "Lagos State University of Science and Technology, Ikorodu",
    "shortName": "LASUSTECH",
    "type": "State University",
    "ownership": "State",
    "state": "Lagos",
    "city": "Ikorodu, Lagos",
    "geopoliticalZone": "South West",
    "establishedYear": 2022,
    "motto": "Excellence in Science, Technology and Applied Arts",
    "logoColor": "#d84315",
    "gradingSystem": "5.0",
    "websiteUrl": "https://lasustech.edu.ng",
    "portalUrl": "https://portal.lasustech.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/state-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Comprehensive science and technology state university upgraded from the former LASPOTECH, delivering advanced engineering, computing, and agricultural sciences.",
    "faculties": [
      "College of Engineering and Technology",
      "College of Applied Sciences",
      "College of Agriculture",
      "College of Environmental Design and Technology",
      "College of Management and Social Sciences"
    ]
  },
  {
    "id": "lasued",
    "name": "Lagos State University of Education, Oto/Ijanikin",
    "shortName": "LASUED",
    "type": "State University",
    "ownership": "State",
    "state": "Lagos",
    "city": "Oto/Ijanikin & Epe, Lagos",
    "geopoliticalZone": "South West",
    "establishedYear": 2022,
    "motto": "Pedagogical Excellence and Innovation",
    "logoColor": "#303f9f",
    "gradingSystem": "5.0",
    "websiteUrl": "https://lasued.edu.ng",
    "portalUrl": "https://portal.lasued.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/state-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Premier education university in Lagos State, upgraded from AOCOED and MOCPED.",
    "faculties": [
      "College of Science Education",
      "College of Vocational and Technical Education",
      "College of Humanities Education",
      "College of Social Science Education",
      "College of Management Education",
      "College of Languages Education"
    ]
  },
  {
    "id": "pan_atlantic_uni",
    "name": "Pan-Atlantic University, Ibeju-Lekki",
    "shortName": "PAU",
    "type": "Private University",
    "ownership": "Private",
    "state": "Lagos",
    "city": "Ibeju-Lekki, Lagos",
    "geopoliticalZone": "South West",
    "establishedYear": 2002,
    "motto": "Sursum Corda (Lift Up Your Hearts)",
    "logoColor": "#002171",
    "gradingSystem": "5.0",
    "websiteUrl": "https://pau.edu.ng",
    "portalUrl": "https://sims.pau.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/private-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Elite private university housing the world-renowned Lagos Business School (LBS) and School of Media and Communication (SMC).",
    "faculties": [
      "Lagos Business School (LBS)",
      "School of Media and Communication (SMC)",
      "School of Science and Technology",
      "School of Management and Social Sciences"
    ]
  },
  {
    "id": "caleb_uni",
    "name": "Caleb University, Imota",
    "shortName": "CALEB",
    "type": "Private University",
    "ownership": "Private",
    "state": "Lagos",
    "city": "Imota, Ikorodu, Lagos",
    "geopoliticalZone": "South West",
    "establishedYear": 2007,
    "motto": "For God and Humanity",
    "logoColor": "#4a148c",
    "gradingSystem": "5.0",
    "websiteUrl": "https://calebuniversity.edu.ng",
    "portalUrl": "https://portal.calebuniversity.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/private-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Private Christian university offering architecture, computer science, mass communication, and business.",
    "faculties": [
      "College of Environmental Sciences and Management",
      "College of Pure and Applied Sciences",
      "College of Social and Management Sciences",
      "College of Arts, Social Sciences and Education",
      "College of Law"
    ]
  },
  {
    "id": "yabatech",
    "name": "Yaba College of Technology",
    "shortName": "YABATECH",
    "type": "Federal Polytechnic",
    "ownership": "Federal",
    "state": "Lagos",
    "city": "Yaba, Lagos",
    "geopoliticalZone": "South West",
    "establishedYear": 1947,
    "motto": "First and Still the Best",
    "logoColor": "#1b5e20",
    "gradingSystem": "4.0",
    "websiteUrl": "https://yabatech.edu.ng",
    "portalUrl": "https://portal.yabatech.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/polytechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Nigeria's first higher education institution, founded in 1947, renowned for engineering, fine art, computer technology, and business.",
    "faculties": [
      "School of Engineering",
      "School of Science",
      "School of Technology",
      "School of Management and Business Studies",
      "School of Environmental Studies",
      "School of Art, Design and Printing",
      "School of Liberal Studies"
    ]
  },
  {
    "id": "fce_technical_akoka",
    "name": "Federal College of Education (Technical), Akoka",
    "shortName": "FCET Akoka",
    "type": "Federal College of Education",
    "ownership": "Federal",
    "state": "Lagos",
    "city": "Akoka, Yaba, Lagos",
    "geopoliticalZone": "South West",
    "establishedYear": 1967,
    "motto": "Skill for Self-Reliance in Teaching",
    "logoColor": "#b71c1c",
    "gradingSystem": "4.0",
    "websiteUrl": "https://fcetakoka.edu.ng",
    "portalUrl": "https://portal.fcetakoka.edu.ng",
    "regulator": "NCCE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://ncceonline.edu.ng",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Nigeria's premier federal technical college of education, delivering vocational, technical, and sciences teacher credentials.",
    "faculties": [
      "School of Technical Education",
      "School of Vocational Education",
      "School of Science Education",
      "School of Business Education",
      "School of Education"
    ]
  },
  {
    "id": "lagos_health_tech_yaba",
    "name": "Lagos State College of Health Technology, Yaba",
    "shortName": "LASCOHET",
    "type": "College of Health Sciences and Technology",
    "ownership": "State",
    "state": "Lagos",
    "city": "Yaba, Lagos",
    "geopoliticalZone": "South West",
    "establishedYear": 1920,
    "motto": "Health is Life, Education is Light",
    "logoColor": "#00838f",
    "gradingSystem": "4.0",
    "websiteUrl": "https://lascohet.edu.ng",
    "portalUrl": "https://apply.lascohet.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Century-old pioneer health technology institute training community health officers, medical lab technicians, and pharmacy technicians in Lagos.",
    "faculties": [
      "Department of Community Health",
      "Department of Medical Laboratory Technology",
      "Department of Pharmacy Technician Studies",
      "Department of Environmental Health Technology",
      "Department of Health Information Management"
    ]
  },

  # ----------------------------------------------------
  # OGUN STATE
  # ----------------------------------------------------
  {
    "id": "funaab",
    "name": "Federal University of Agriculture, Abeokuta",
    "shortName": "FUNAAB",
    "type": "Federal University",
    "ownership": "Federal",
    "state": "Ogun",
    "city": "Abeokuta",
    "geopoliticalZone": "South West",
    "establishedYear": 1988,
    "motto": "Knowledge for Development",
    "logoColor": "#1b5e20",
    "gradingSystem": "5.0",
    "websiteUrl": "https://funaab.edu.ng",
    "portalUrl": "https://portal.unaab.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/federal-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Pioneering specialized federal university renowned for agricultural sciences, veterinary medicine, physical sciences, and engineering.",
    "faculties": [
      "College of Agricultural Management and Rural Development",
      "College of Animal Science and Livestock Production",
      "College of Environmental Resources Management",
      "College of Natural Sciences",
      "College of Plant Science and Crop Production",
      "College of Veterinary Medicine",
      "College of Engineering",
      "College of Food Science and Human Ecology",
      "College of Management Sciences"
    ]
  },
  {
    "id": "oou_ago_iwoye",
    "name": "Olabisi Onabanjo University, Ago-Iwoye",
    "shortName": "OOU",
    "type": "State University",
    "ownership": "State",
    "state": "Ogun",
    "city": "Ago-Iwoye",
    "geopoliticalZone": "South West",
    "establishedYear": 1982,
    "motto": "Excellentia Humani Generis (Excellence for the Human Race)",
    "logoColor": "#0d47a1",
    "gradingSystem": "5.0",
    "websiteUrl": "https://oouagoiwoye.edu.ng",
    "portalUrl": "https://portal.oouagoiwoye.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/state-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Premier state university in Ogun State with multiple campuses (Ago-Iwoye, Sagamu, Ayetoro, Ibogun), acclaimed for medicine, law, pharmacy, and sciences.",
    "faculties": [
      "Obafemi Awolowo College of Health Sciences (Sagamu)",
      "Faculty of Pharmacy",
      "Faculty of Law",
      "Faculty of Science",
      "Faculty of Engineering and Environmental Studies (Ibogun)",
      "Faculty of Administration and Management Sciences",
      "Faculty of Social Sciences",
      "Faculty of Agricultural Sciences (Ayetoro)",
      "Faculty of Arts",
      "Faculty of Education"
    ]
  },
  {
    "id": "covenant_uni",
    "name": "Covenant University, Ota",
    "shortName": "CU",
    "type": "Private University",
    "ownership": "Private",
    "state": "Ogun",
    "city": "Ota",
    "geopoliticalZone": "South West",
    "establishedYear": 2002,
    "motto": "Raising a New Generation of Leaders",
    "logoColor": "#800020",
    "gradingSystem": "5.0",
    "websiteUrl": "https://covenantuniversity.edu.ng",
    "portalUrl": "https://portal.covenantuniversity.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/private-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Consistently ranked Nigeria's top private university and among Africa's highest ranked by Times Higher Education, renowned for computer science, engineering, and leadership development.",
    "faculties": [
      "College of Engineering",
      "College of Science and Technology",
      "College of Business and Social Sciences",
      "College of Leadership Development Studies"
    ]
  },
  {
    "id": "babcock_uni",
    "name": "Babcock University, Ilishan-Remo",
    "shortName": "BU",
    "type": "Private University",
    "ownership": "Private",
    "state": "Ogun",
    "city": "Ilishan-Remo",
    "geopoliticalZone": "South West",
    "establishedYear": 1999,
    "motto": "Knowledge, Truth, Service",
    "logoColor": "#002171",
    "gradingSystem": "5.0",
    "websiteUrl": "https://babcock.edu.ng",
    "portalUrl": "https://portal.babcock.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/private-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Leading Seventh-day Adventist private university in Nigeria, famous for its Benjamin Carson School of Medicine, nursing, law, computer science, and business.",
    "faculties": [
      "Benjamin S. Carson (Snr.) College of Health and Medical Sciences",
      "School of Law and Security Studies",
      "School of Computing and Engineering Sciences",
      "School of Science and Technology",
      "School of Management Sciences",
      "School of Public and Allied Health",
      "School of Education and Humanities"
    ]
  },
  {
    "id": "mapoly",
    "name": "Moshood Abiola Polytechnic, Abeokuta",
    "shortName": "MAPOLY",
    "type": "State Polytechnic",
    "ownership": "State",
    "state": "Ogun",
    "city": "Ojere, Abeokuta",
    "geopoliticalZone": "South West",
    "establishedYear": 1980,
    "motto": "Technology for Development",
    "logoColor": "#004d40",
    "gradingSystem": "4.0",
    "websiteUrl": "https://mapoly.edu.ng",
    "portalUrl": "https://portal.mapoly.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/polytechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Prestigious state polytechnic located in Abeokuta, famous for mass communication, accounting, engineering, and science laboratory technology.",
    "faculties": [
      "School of Engineering",
      "School of Science and Technology",
      "School of Business and Management Studies",
      "School of Environmental Studies",
      "School of Communication and Information Technology"
    ]
  },
  {
    "id": "fedpoly_ilaro",
    "name": "Federal Polytechnic, Ilaro",
    "shortName": "FPI",
    "type": "Federal Polytechnic",
    "ownership": "Federal",
    "state": "Ogun",
    "city": "Ilaro",
    "geopoliticalZone": "South West",
    "establishedYear": 1979,
    "motto": "Skill for Technological Freedom",
    "logoColor": "#b71c1c",
    "gradingSystem": "4.0",
    "websiteUrl": "https://federalpolyilaro.edu.ng",
    "portalUrl": "https://applications.federalpolyilaro.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/polytechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "One of Nigeria's best-ranked federal polytechnics, famous for academic stability, engineering, computer science, and banking.",
    "faculties": [
      "School of Engineering",
      "School of Pure and Applied Sciences",
      "School of Management Studies",
      "School of Environmental Studies",
      "School of Communication and Information Technology"
    ]
  },
  {
    "id": "tasce_ososa",
    "name": "Tai Solarin College of Education, Omu-Ijebu",
    "shortName": "TASCE",
    "type": "State College of Education",
    "ownership": "State",
    "state": "Ogun",
    "city": "Omu-Ijebu",
    "geopoliticalZone": "South West",
    "establishedYear": 1978,
    "motto": "Education for Freedom and Self-Reliance",
    "logoColor": "#2e7d32",
    "gradingSystem": "4.0",
    "websiteUrl": "https://tasce.edu.ng",
    "portalUrl": "https://portal.tasce.edu.ng",
    "regulator": "NCCE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://ncceonline.edu.ng",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Historic state teacher training college named after educator Dr. Tai Solarin, delivering NCE programmes.",
    "faculties": [
      "School of Sciences",
      "School of Vocational and Technical Education",
      "School of Arts and Social Sciences",
      "School of Languages",
      "School of Education"
    ]
  },

  # ----------------------------------------------------
  # ONDO STATE
  # ----------------------------------------------------
  {
    "id": "futa",
    "name": "Federal University of Technology, Akure",
    "shortName": "FUTA",
    "type": "Federal University",
    "ownership": "Federal",
    "state": "Ondo",
    "city": "Akure",
    "geopoliticalZone": "South West",
    "establishedYear": 1981,
    "motto": "Technology for Self Reliance",
    "logoColor": "#004d40",
    "gradingSystem": "5.0",
    "websiteUrl": "https://futa.edu.ng",
    "portalUrl": "https://portal.futa.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/federal-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Leading technological university in Nigeria, acclaimed nationally and globally for software engineering, computer science, mining, architecture, and agricultural engineering.",
    "faculties": [
      "School of Computing",
      "School of Engineering and Engineering Technology",
      "School of Physical Sciences",
      "School of Life Sciences",
      "School of Environmental Technology",
      "School of Agriculture and Agricultural Technology",
      "School of Earth and Mineral Sciences",
      "School of Health and Health Technology",
      "School of Management Technology"
    ]
  },
  {
    "id": "aaua",
    "name": "Adekunle Ajasin University, Akungba-Akoko",
    "shortName": "AAUA",
    "type": "State University",
    "ownership": "State",
    "state": "Ondo",
    "city": "Akungba-Akoko",
    "geopoliticalZone": "South West",
    "establishedYear": 1999,
    "motto": "For Learning and Character",
    "logoColor": "#1565c0",
    "gradingSystem": "5.0",
    "websiteUrl": "https://aaua.edu.ng",
    "portalUrl": "https://portal.aaua.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/state-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Top-ranked state university in Ondo State, acclaimed for law, physical and biological sciences, business, and education.",
    "faculties": [
      "Faculty of Law",
      "Faculty of Science",
      "Faculty of Administration and Management Sciences",
      "Faculty of Social Sciences",
      "Faculty of Arts",
      "Faculty of Agriculture",
      "Faculty of Education",
      "Faculty of Environmental Design and Management"
    ]
  },
  {
    "id": "unimed_ondo",
    "name": "University of Medical Sciences, Ondo City",
    "shortName": "UNIMED",
    "type": "State University",
    "ownership": "State",
    "state": "Ondo",
    "city": "Ondo City",
    "geopoliticalZone": "South West",
    "establishedYear": 2014,
    "motto": "For Health and Development",
    "logoColor": "#b71c1c",
    "gradingSystem": "5.0",
    "websiteUrl": "https://unimed.edu.ng",
    "portalUrl": "https://portal.unimed.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/state-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Nigeria's first specialized public university of medical sciences, offering medicine, dentistry, physiotherapy, nursing, and biomedical engineering.",
    "faculties": [
      "Faculty of Clinical Sciences",
      "Faculty of Dental Sciences",
      "Faculty of Basic Medical Sciences",
      "Faculty of Allied Health Sciences",
      "Faculty of Pharmacy",
      "Faculty of Medical Rehabilitation",
      "Faculty of Nursing Science",
      "Faculty of Science"
    ]
  },
  {
    "id": "achievers_uni_owo",
    "name": "Achievers University, Owo",
    "shortName": "AUO",
    "type": "Private University",
    "ownership": "Private",
    "state": "Ondo",
    "city": "Owo",
    "geopoliticalZone": "South West",
    "establishedYear": 2007,
    "motto": "Knowledge, Integrity and Leadership",
    "logoColor": "#4a148c",
    "gradingSystem": "5.0",
    "websiteUrl": "https://achievers.edu.ng",
    "portalUrl": "https://portal.achievers.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/private-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Private university in Owo known for medical lab science, nursing, engineering, law, and computing.",
    "faculties": [
      "College of Health Sciences",
      "College of Engineering and Technology",
      "College of Law",
      "College of Natural and Applied Sciences",
      "College of Social and Management Sciences"
    ]
  },
  {
    "id": "rufus_giwa_poly",
    "name": "Rufus Giwa Polytechnic, Owo",
    "shortName": "RUGIPO",
    "type": "State Polytechnic",
    "ownership": "State",
    "state": "Ondo",
    "city": "Owo",
    "geopoliticalZone": "South West",
    "establishedYear": 1979,
    "motto": "Knowledge for Service",
    "logoColor": "#e65100",
    "gradingSystem": "4.0",
    "websiteUrl": "https://rugipo.edu.ng",
    "portalUrl": "https://portal.rugipo.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/polytechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Ondo State polytechnic providing accredited programmes in engineering, science technology, environmental studies, and accounting.",
    "faculties": [
      "Faculty of Engineering Technology",
      "Faculty of Applied Sciences",
      "Faculty of Business Studies",
      "Faculty of Environmental Studies",
      "Faculty of Agricultural Technology"
    ]
  },
  {
    "id": "ace_ondo",
    "name": "Adeyemi Federal University of Education, Ondo City",
    "shortName": "AFUED",
    "type": "Federal University",
    "ownership": "Federal",
    "state": "Ondo",
    "city": "Ondo City",
    "geopoliticalZone": "South West",
    "establishedYear": 1964,
    "motto": "Education for Service",
    "logoColor": "#2e7d32",
    "gradingSystem": "5.0",
    "websiteUrl": "https://aceondo.edu.ng",
    "portalUrl": "https://portal.aceondo.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/federal-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Historic federal teacher training college upgraded to full university status, producing Nigeria's top educators.",
    "faculties": [
      "Faculty of Science Education",
      "Faculty of Vocational and Technical Education",
      "Faculty of Arts and Social Science Education",
      "Faculty of Languages Education",
      "Faculty of Educational Foundation"
    ]
  },

  # ----------------------------------------------------
  # OSUN STATE
  # ----------------------------------------------------
  {
    "id": "oau_ile_ife",
    "name": "Obafemi Awolowo University, Ile-Ife",
    "shortName": "OAU",
    "type": "Federal University",
    "ownership": "Federal",
    "state": "Osun",
    "city": "Ile-Ife",
    "geopoliticalZone": "South West",
    "establishedYear": 1962,
    "motto": "For Learning and Culture",
    "logoColor": "#1565c0",
    "gradingSystem": "5.0",
    "websiteUrl": "https://oauife.edu.ng",
    "portalUrl": "https://eportal.oauife.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/federal-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Acclaimed as 'Great Ife', with Africa's most beautiful campus, world-famous for medicine, pharmacy, law, technology/software engineering, agriculture, and sciences.",
    "faculties": [
      "Faculty of Technology",
      "Faculty of Science",
      "College of Health Sciences",
      "Faculty of Pharmacy",
      "Faculty of Law",
      "Faculty of Administration",
      "Faculty of Social Sciences",
      "Faculty of Arts",
      "Faculty of Environmental Design and Management",
      "Faculty of Agriculture",
      "Faculty of Education",
      "Faculty of Dentistry"
    ]
  },
  {
    "id": "uniosun",
    "name": "Osun State University, Osogbo",
    "shortName": "UNIOSUN",
    "type": "State University",
    "ownership": "State",
    "state": "Osun",
    "city": "Osogbo",
    "geopoliticalZone": "South West",
    "establishedYear": 2006,
    "motto": "Living Springs of Knowledge and Innovation",
    "logoColor": "#004d40",
    "gradingSystem": "5.0",
    "websiteUrl": "https://uniosun.edu.ng",
    "portalUrl": "https://portal.uniosun.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/state-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Multi-campus state university with campuses across Osogbo, Okuku, Ikire, Ejigbo, Ifetedo, and Ipetu-Ijesha, acclaimed for medicine, law, agriculture, and engineering.",
    "faculties": [
      "College of Health Sciences (Osogbo)",
      "College of Law (Ifetedo)",
      "College of Science, Engineering and Technology (Osogbo)",
      "College of Management and Social Sciences (Okuku)",
      "College of Humanities and Culture (Ikire)",
      "College of Agriculture (Ejigbo)",
      "College of Education (Ipetu-Ijesha)"
    ]
  },
  {
    "id": "bowen_uni",
    "name": "Bowen University, Iwo",
    "shortName": "Bowen",
    "type": "Private University",
    "ownership": "Private",
    "state": "Osun",
    "city": "Iwo",
    "geopoliticalZone": "South West",
    "establishedYear": 2001,
    "motto": "Excellence and Godliness",
    "logoColor": "#b71c1c",
    "gradingSystem": "5.0",
    "websiteUrl": "https://bowen.edu.ng",
    "portalUrl": "https://ssb.bowen.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/private-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "First Baptist university in Africa, noted for its college of health sciences, law, agriculture, nursing, and computer science.",
    "faculties": [
      "College of Health Sciences",
      "College of Law",
      "College of Computing and Communication Studies",
      "College of Science",
      "College of Liberal Arts",
      "College of Management and Social Sciences",
      "College of Agriculture"
    ]
  },
  {
    "id": "redeemers_uni",
    "name": "Redeemer's University, Ede",
    "shortName": "RUN",
    "type": "Private University",
    "ownership": "Private",
    "state": "Osun",
    "city": "Ede",
    "geopoliticalZone": "South West",
    "establishedYear": 2005,
    "motto": "Running with a Vision",
    "logoColor": "#303f9f",
    "gradingSystem": "5.0",
    "websiteUrl": "https://run.edu.ng",
    "portalUrl": "https://portal.run.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/private-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Private Christian university housing the World Bank funded ACEGID genomic research center, acclaimed for genomics, medicine, law, and computing.",
    "faculties": [
      "Faculty of Basic Medical Sciences",
      "Faculty of Law",
      "Faculty of Natural Sciences",
      "Faculty of Engineering",
      "Faculty of Management Sciences",
      "Faculty of Social Sciences",
      "Faculty of Humanities"
    ]
  },
  {
    "id": "fedpoly_ede",
    "name": "Federal Polytechnic, Ede",
    "shortName": "FEDPOLYEDE",
    "type": "Federal Polytechnic",
    "ownership": "Federal",
    "state": "Osun",
    "city": "Ede",
    "geopoliticalZone": "South West",
    "establishedYear": 1992,
    "motto": "Knowledge, Skill and Technology",
    "logoColor": "#e65100",
    "gradingSystem": "4.0",
    "websiteUrl": "https://federalpolyede.edu.ng",
    "portalUrl": "https://eportal.federalpolyede.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/polytechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Premier federal polytechnic with strong credentials in computer science, electrical engineering, geology, and business management.",
    "faculties": [
      "School of Engineering Technology",
      "School of Applied Sciences",
      "School of Business Studies",
      "School of Environmental Studies"
    ]
  },
  {
    "id": "osun_poly_iree",
    "name": "Osun State Polytechnic, Iree",
    "shortName": "OSPOLY",
    "type": "State Polytechnic",
    "ownership": "State",
    "state": "Osun",
    "city": "Iree, Boripe",
    "geopoliticalZone": "South West",
    "establishedYear": 1992,
    "motto": "Excellence in Technology and Character",
    "logoColor": "#00796b",
    "gradingSystem": "4.0",
    "websiteUrl": "https://ospoly.edu.ng",
    "portalUrl": "https://portal.ospoly.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/polytechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "State polytechnic offering technical and commercial ND and HND curricula in engineering, computing, and mass communication.",
    "faculties": [
      "Faculty of Engineering",
      "Faculty of Science",
      "Faculty of Financial Studies",
      "Faculty of Management Studies",
      "Faculty of Information and Communication Technology"
    ]
  },
  {
    "id": "fce_iwo",
    "name": "Federal College of Education, Iwo",
    "shortName": "FCE Iwo",
    "type": "Federal College of Education",
    "ownership": "Federal",
    "state": "Osun",
    "city": "Iwo",
    "geopoliticalZone": "South West",
    "establishedYear": 2020,
    "motto": "Integrity and Pedagogical Mastery",
    "logoColor": "#2e7d32",
    "gradingSystem": "4.0",
    "websiteUrl": "https://fceiwo.edu.ng",
    "regulator": "NCCE",
    "accreditationStatus": "Accredited",
    "verificationStatus": "Verified",
    "sourceUrl": "https://ncceonline.edu.ng",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Modern federal teacher education college providing specialized NCE programmes in technical education, sciences, and languages.",
    "faculties": [
      "School of Sciences",
      "School of Vocational and Technical Education",
      "School of Arts and Social Sciences",
      "School of Languages",
      "School of Education"
    ]
  },

  # ----------------------------------------------------
  # OYO STATE
  # ----------------------------------------------------
  {
    "id": "ui_ibadan",
    "name": "University of Ibadan",
    "shortName": "UI",
    "type": "Federal University",
    "ownership": "Federal",
    "state": "Oyo",
    "city": "Ibadan",
    "geopoliticalZone": "South West",
    "establishedYear": 1948,
    "motto": "Recte Sapere Fons (To Think Straight is the Fount of Knowledge)",
    "logoColor": "#1565c0",
    "gradingSystem": "5.0",
    "websiteUrl": "https://ui.edu.ng",
    "portalUrl": "https://portal.ui.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/federal-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Nigeria's premier university (founded in 1948), flagship postgraduate research institution in Sub-Saharan Africa with world-renowned faculties of medicine, sciences, arts, pharmacy, and engineering.",
    "faculties": [
      "College of Medicine",
      "Faculty of Science",
      "Faculty of Technology",
      "Faculty of Pharmacy",
      "Faculty of Law",
      "Faculty of Economics and Management Sciences",
      "Faculty of Social Sciences",
      "Faculty of Arts",
      "Faculty of Agriculture",
      "Faculty of Renewable Natural Resources",
      "Faculty of Veterinary Medicine",
      "Faculty of Education",
      "Faculty of Public Health",
      "Faculty of Dentistry"
    ]
  },
  {
    "id": "lautech_ogbomoso",
    "name": "Ladoke Akintola University of Technology, Ogbomoso",
    "shortName": "LAUTECH",
    "type": "State University",
    "ownership": "State",
    "state": "Oyo",
    "city": "Ogbomoso & Iseyin",
    "geopoliticalZone": "South West",
    "establishedYear": 1990,
    "motto": "Excellence, Integrity and Service",
    "logoColor": "#b71c1c",
    "gradingSystem": "5.0",
    "websiteUrl": "https://lautech.edu.ng",
    "portalUrl": "https://portal.lautech.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/state-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Consistently ranked the best state university in Nigeria by NUC, celebrated for engineering, computer science, medicine, and agricultural sciences.",
    "faculties": [
      "Faculty of Engineering and Technology",
      "Faculty of Computing and Informatics",
      "Faculty of Pure and Applied Sciences",
      "College of Health Sciences",
      "Faculty of Agricultural Sciences (Iseyin)",
      "Faculty of Environmental Sciences",
      "Faculty of Management Sciences",
      "Faculty of Nursing Sciences",
      "Faculty of Food and Consumer Sciences"
    ]
  },
  {
    "id": "tech_u_ibadan",
    "name": "First Technical University, Ibadan",
    "shortName": "Tech-U",
    "type": "State University",
    "ownership": "State",
    "state": "Oyo",
    "city": "Ibadan",
    "geopoliticalZone": "South West",
    "establishedYear": 2017,
    "motto": "Developing Brains, Transforming Hands",
    "logoColor": "#004d40",
    "gradingSystem": "5.0",
    "websiteUrl": "https://tech-u.edu.ng",
    "portalUrl": "https://portal.tech-u.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/state-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "First technical university in Nigeria founded by the Oyo State Government, focused on robotics, cyber security, biomedical engineering, and entrepreneurship.",
    "faculties": [
      "Faculty of Engineering and Technology",
      "Faculty of Natural and Applied Sciences",
      "Faculty of Environmental Sciences"
    ]
  },
  {
    "id": "lead_city_uni",
    "name": "Lead City University, Ibadan",
    "shortName": "LCU",
    "type": "Private University",
    "ownership": "Private",
    "state": "Oyo",
    "city": "Toll Gate, Ibadan",
    "geopoliticalZone": "South West",
    "establishedYear": 2005,
    "motto": "Knowledge for Self-Reliance",
    "logoColor": "#4a148c",
    "gradingSystem": "5.0",
    "websiteUrl": "https://lcu.edu.ng",
    "portalUrl": "https://portal.lcu.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/private-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Popular private university in Ibadan offering medicine, nursing, law, computing, and social sciences.",
    "faculties": [
      "Faculty of Clinical Sciences",
      "Faculty of Basic Medical and Health Sciences",
      "Faculty of Law",
      "Faculty of Sciences",
      "Faculty of Engineering and Technology",
      "Faculty of Social and Management Sciences",
      "Faculty of Arts and Education"
    ]
  },
  {
    "id": "poly_ibadan",
    "name": "The Polytechnic, Ibadan",
    "shortName": "POLYIBADAN",
    "type": "State Polytechnic",
    "ownership": "State",
    "state": "Oyo",
    "city": "Sango, Ibadan",
    "geopoliticalZone": "South West",
    "establishedYear": 1970,
    "motto": "Ise Loogun Ise (Work is the Antidote to Poverty)",
    "logoColor": "#e65100",
    "gradingSystem": "4.0",
    "websiteUrl": "https://polyibadan.edu.ng",
    "portalUrl": "https://portal.polyibadan.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/polytechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Historic and premier state polytechnic in Nigeria, renowned for engineering, architecture, computer science, and mass communication.",
    "faculties": [
      "Faculty of Engineering",
      "Faculty of Science",
      "Faculty of Business and Communication Studies",
      "Faculty of Financial Management Studies",
      "Faculty of Environmental Studies"
    ]
  },
  {
    "id": "fce_special_oyo",
    "name": "Federal College of Education (Special), Oyo",
    "shortName": "SPED Oyo",
    "type": "Federal College of Education",
    "ownership": "Federal",
    "state": "Oyo",
    "city": "Oyo Town",
    "geopoliticalZone": "South West",
    "establishedYear": 1977,
    "motto": "Education for All Persons with Special Needs",
    "logoColor": "#00796b",
    "gradingSystem": "4.0",
    "websiteUrl": "https://fcesoyo.edu.ng",
    "portalUrl": "https://portal.fcesoyo.edu.ng",
    "regulator": "NCCE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://ncceonline.edu.ng",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Only specialized federal college of education in Sub-Saharan Africa training teachers for special needs education, rehabilitation, and general education.",
    "faculties": [
      "School of Special Education",
      "School of Sciences",
      "School of Vocational and Technical Education",
      "School of Arts and Social Sciences",
      "School of Languages",
      "School of Education"
    ]
  },
  {
    "id": "fcf_ibadan",
    "name": "Federal College of Forestry, Ibadan",
    "shortName": "FCF Ibadan",
    "type": "Colleges of Agriculture",
    "ownership": "Federal",
    "state": "Oyo",
    "city": "Jericho, Ibadan",
    "geopoliticalZone": "South West",
    "establishedYear": 1939,
    "motto": "Conserving Nature, Empowering Minds",
    "logoColor": "#2e7d32",
    "gradingSystem": "4.0",
    "websiteUrl": "https://fcfibadan.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Nigeria's oldest specialized monotechnic college dedicated to forestry, agriculture, horticulture, and environmental conservation.",
    "faculties": [
      "Department of Forestry Technology",
      "Department of Agricultural Technology",
      "Department of Horticulture and Landscape Technology",
      "Department of Computer Science"
    ]
  }
]
