# NORTH EAST ZONE: Adamawa, Bauchi, Borno, Gombe, Taraba, Yobe

DATA = [
  # ----------------------------------------------------
  # ADAMAWA STATE
  # ----------------------------------------------------
  {
    "id": "mautech_yola",
    "name": "Modibbo Adama University, Yola",
    "shortName": "MAU Yola",
    "type": "Federal University",
    "ownership": "Federal",
    "state": "Adamawa",
    "city": "Girei, Yola",
    "geopoliticalZone": "North East",
    "establishedYear": 1981,
    "motto": "Knowledge is Light",
    "logoColor": "#1565c0",
    "gradingSystem": "5.0",
    "websiteUrl": "https://mau.edu.ng",
    "portalUrl": "https://portal.mau.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/federal-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Converted from MAUTECH to conventional university status, acclaimed for engineering, medical sciences, computing, and physical sciences.",
    "faculties": [
      "College of Medical Sciences",
      "School of Engineering and Engineering Technology",
      "School of Physical Sciences",
      "School of Life Sciences",
      "School of Management and Information Technology",
      "School of Agriculture and Agricultural Technology",
      "School of Environmental Sciences",
      "School of Social and Management Sciences",
      "School of Education"
    ]
  },
  {
    "id": "adsu_mubi",
    "name": "Adamawa State University, Mubi",
    "shortName": "ADSU",
    "type": "State University",
    "ownership": "State",
    "state": "Adamawa",
    "city": "Mubi",
    "geopoliticalZone": "North East",
    "establishedYear": 2002,
    "motto": "Search for Knowledge",
    "logoColor": "#004d40",
    "gradingSystem": "5.0",
    "websiteUrl": "https://adsu.edu.ng",
    "portalUrl": "https://adsu.safsrms.com",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/state-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "State university located in the commercial town of Mubi, delivering strong programmes in agriculture, science, and administration.",
    "faculties": [
      "Faculty of Science",
      "Faculty of Agriculture",
      "Faculty of Social and Management Sciences",
      "Faculty of Arts",
      "Faculty of Education"
    ]
  },
  {
    "id": "aun_yola",
    "name": "American University of Nigeria, Yola",
    "shortName": "AUN",
    "type": "Private University",
    "ownership": "Private",
    "state": "Adamawa",
    "city": "Yola",
    "geopoliticalZone": "North East",
    "establishedYear": 2003,
    "motto": "Africa's Development University",
    "logoColor": "#880e4f",
    "gradingSystem": "4.0",
    "websiteUrl": "https://aun.edu.ng",
    "portalUrl": "https://canvas.aun.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/private-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Africa's first American-style liberal arts university, founded by Atiku Abubakar, globally renowned for software engineering, cyber security, data analytics, law, and business.",
    "faculties": [
      "School of Information Technology and Computing",
      "School of Law",
      "School of Engineering",
      "School of Business and Entrepreneurship",
      "School of Arts and Sciences"
    ]
  },
  {
    "id": "fedpoly_mubi",
    "name": "Federal Polytechnic, Mubi",
    "shortName": "FPM",
    "type": "Federal Polytechnic",
    "ownership": "Federal",
    "state": "Adamawa",
    "city": "Mubi",
    "geopoliticalZone": "North East",
    "establishedYear": 1979,
    "motto": "Technology for Self-Reliance",
    "logoColor": "#b71c1c",
    "gradingSystem": "4.0",
    "websiteUrl": "https://fpm.edu.ng",
    "portalUrl": "https://portal.fpm.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/polytechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Prominent federal polytechnic in the North East offering accredited engineering, agricultural, environmental, and business ND/HND diplomas.",
    "faculties": [
      "School of Engineering Technology",
      "School of Science and Technology",
      "School of Management Studies",
      "School of Environmental Studies",
      "School of Agricultural Technology"
    ]
  },
  {
    "id": "adamawa_poly_yola",
    "name": "Adamawa State Polytechnic, Yola",
    "shortName": "SPYOLA",
    "type": "State Polytechnic",
    "ownership": "State",
    "state": "Adamawa",
    "city": "Yola & Numan",
    "geopoliticalZone": "North East",
    "establishedYear": 1991,
    "motto": "Work, Skill and Development",
    "logoColor": "#e65100",
    "gradingSystem": "4.0",
    "websiteUrl": "https://adamawapoly.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/polytechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Multi-campus state polytechnic offering technical education, engineering, mass communication, and administrative studies.",
    "faculties": [
      "School of Engineering",
      "School of Science and Technology",
      "School of Business Studies",
      "School of Environmental Studies"
    ]
  },
  {
    "id": "fce_yola",
    "name": "Federal College of Education, Yola",
    "shortName": "FCE Yola",
    "type": "Federal College of Education",
    "ownership": "Federal",
    "state": "Adamawa",
    "city": "Yola",
    "geopoliticalZone": "North East",
    "establishedYear": 1974,
    "motto": "Excellence in Teacher Education",
    "logoColor": "#2e7d32",
    "gradingSystem": "4.0",
    "websiteUrl": "https://fceyola.edu.ng",
    "portalUrl": "https://portal.fceyola.edu.ng",
    "regulator": "NCCE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://ncceonline.edu.ng",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Premier federal teacher training college in Adamawa State offering NCE and undergraduate degree programmes affiliated with UNIMAID.",
    "faculties": [
      "School of Sciences",
      "School of Vocational and Technical Education",
      "School of Arts and Social Sciences",
      "School of Languages",
      "School of Education"
    ]
  },

  # ----------------------------------------------------
  # BAUCHI STATE
  # ----------------------------------------------------
  {
    "id": "atbu_bauchi",
    "name": "Abubakar Tafawa Balewa University, Bauchi",
    "shortName": "ATBU",
    "type": "Federal University",
    "ownership": "Federal",
    "state": "Bauchi",
    "city": "Bauchi",
    "geopoliticalZone": "North East",
    "establishedYear": 1980,
    "motto": "Doctrina Mater Artium (Education is the Mother of the Practical Arts)",
    "logoColor": "#1565c0",
    "gradingSystem": "5.0",
    "websiteUrl": "https://atbu.edu.ng",
    "portalUrl": "https://portal.atbu.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/federal-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Premier federal technological university named after Nigeria's first Prime Minister, famed for engineering, medicine, computing, and environmental design.",
    "faculties": [
      "College of Medical Sciences",
      "Faculty of Engineering and Engineering Technology",
      "Faculty of Science",
      "Faculty of Technology Education",
      "Faculty of Environmental Technology",
      "Faculty of Agriculture and Agricultural Technology",
      "Faculty of Management Sciences"
    ]
  },
  {
    "id": "basu_gadau",
    "name": "Bauchi State University, Gadau",
    "shortName": "BASUG",
    "type": "State University",
    "ownership": "State",
    "state": "Bauchi",
    "city": "Gadau, Itas-Gadau",
    "geopoliticalZone": "North East",
    "establishedYear": 2011,
    "motto": "Knowledge for Advancement",
    "logoColor": "#004d40",
    "gradingSystem": "5.0",
    "websiteUrl": "https://basug.edu.ng",
    "portalUrl": "https://basug.safsrms.com",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/state-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Multi-campus state university with campuses at Gadau (Main), Misau (Law), and Bauchi (Social and Management Sciences).",
    "faculties": [
      "Faculty of Science (Gadau)",
      "Faculty of Basic Medical Sciences (Gadau)",
      "Faculty of Law (Misau)",
      "Faculty of Social and Management Sciences (Bauchi)",
      "Faculty of Arts and Education (Gadau)",
      "Faculty of Agriculture (Gadau)"
    ]
  },
  {
    "id": "fedpoly_bauchi",
    "name": "Federal Polytechnic, Bauchi",
    "shortName": "FPTB",
    "type": "Federal Polytechnic",
    "ownership": "Federal",
    "state": "Bauchi",
    "city": "Gwallameji, Bauchi",
    "geopoliticalZone": "North East",
    "establishedYear": 1979,
    "motto": "Skill, Diligence and Excellence",
    "logoColor": "#b71c1c",
    "gradingSystem": "4.0",
    "websiteUrl": "https://fptb.edu.ng",
    "portalUrl": "https://portal.fptb.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/polytechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "One of Nigeria's largest federal polytechnics, renowned for engineering, hospitality management, computer science, and mass communication.",
    "faculties": [
      "School of Engineering Technology",
      "School of Science and Technology",
      "School of Business Studies",
      "School of Environmental Studies",
      "School of General Studies and Communication Technology"
    ]
  },
  {
    "id": "tatp_bauchi",
    "name": "Abubakar Tatari Ali Polytechnic, Bauchi",
    "shortName": "ATAPOLY",
    "type": "State Polytechnic",
    "ownership": "State",
    "state": "Bauchi",
    "city": "Bauchi",
    "geopoliticalZone": "North East",
    "establishedYear": 1988,
    "motto": "Knowledge for Self Reliance",
    "logoColor": "#e65100",
    "gradingSystem": "4.0",
    "websiteUrl": "https://atapoly-bauchi.edu.ng",
    "portalUrl": "https://portal.atapoly-bauchi.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/polytechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Comprehensive state polytechnic offering technical ND and HND programmes alongside NCE teacher training certifications.",
    "faculties": [
      "School of Engineering Technology",
      "School of Applied Sciences",
      "School of Management Studies",
      "School of Environmental Studies",
      "School of Vocational and Technical Education"
    ]
  },
  {
    "id": "bauchi_health_ningi",
    "name": "Bauchi State College of Health Technology, Ningi",
    "shortName": "COHT Ningi",
    "type": "College of Health Sciences and Technology",
    "ownership": "State",
    "state": "Bauchi",
    "city": "Ningi",
    "geopoliticalZone": "North East",
    "establishedYear": 1978,
    "motto": "Health Service to Humanity",
    "logoColor": "#00838f",
    "gradingSystem": "4.0",
    "websiteUrl": "https://cohtningi.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Accredited",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Premier state health science college in Bauchi State training community health officers, medical lab technicians, and pharmacy technicians.",
    "faculties": [
      "Department of Community Health",
      "Department of Medical Laboratory Sciences",
      "Department of Pharmacy Technician",
      "Department of Environmental Health"
    ]
  },

  # ----------------------------------------------------
  # BORNO STATE
  # ----------------------------------------------------
  {
    "id": "unimaid",
    "name": "University of Maiduguri",
    "shortName": "UNIMAID",
    "type": "Federal University",
    "ownership": "Federal",
    "state": "Borno",
    "city": "Maiduguri",
    "geopoliticalZone": "North East",
    "establishedYear": 1975,
    "motto": "Knowledge is Light",
    "logoColor": "#1565c0",
    "gradingSystem": "5.0",
    "websiteUrl": "https://unimaid.edu.ng",
    "portalUrl": "https://portal.unimaid.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/federal-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Major second-generation federal university and medical powerhouse in the Lake Chad basin, renowned for medicine, veterinary medicine, law, engineering, and agriculture.",
    "faculties": [
      "College of Medical Sciences",
      "Faculty of Veterinary Medicine",
      "Faculty of Pharmaceutical Sciences",
      "Faculty of Law",
      "Faculty of Engineering",
      "Faculty of Science",
      "Faculty of Management Sciences",
      "Faculty of Social Sciences",
      "Faculty of Arts",
      "Faculty of Agriculture",
      "Faculty of Environmental Studies",
      "Faculty of Education",
      "Faculty of Dentistry"
    ]
  },
  {
    "id": "bosu_maiduguri",
    "name": "Borno State University, Maiduguri",
    "shortName": "BOSU",
    "type": "State University",
    "ownership": "State",
    "state": "Borno",
    "city": "Maiduguri",
    "geopoliticalZone": "North East",
    "establishedYear": 2016,
    "motto": "Excellence, Integrity and Service",
    "logoColor": "#004d40",
    "gradingSystem": "5.0",
    "websiteUrl": "https://bosu.edu.ng",
    "portalUrl": "https://portal.bosu.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/state-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Modern state university established by Borno State Government, offering degree programmes in computing, science, social sciences, and education.",
    "faculties": [
      "Faculty of Science",
      "Faculty of Social and Management Sciences",
      "Faculty of Arts and Education",
      "Faculty of Agriculture"
    ]
  },
  {
    "id": "ramat_poly_maiduguri",
    "name": "Ramat Polytechnic, Maiduguri",
    "shortName": "RAMATPOLY",
    "type": "State Polytechnic",
    "ownership": "State",
    "state": "Borno",
    "city": "Maiduguri",
    "geopoliticalZone": "North East",
    "establishedYear": 1978,
    "motto": "Skill, Knowledge and Progress",
    "logoColor": "#e65100",
    "gradingSystem": "4.0",
    "websiteUrl": "https://ramatpoly.edu.ng",
    "portalUrl": "https://portal.ramatpoly.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/polytechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Historic state polytechnic named after General Murtala Ramat Muhammed, delivering engineering, agricultural, environmental, and business courses.",
    "faculties": [
      "School of Engineering",
      "School of Applied Sciences",
      "School of Management Studies",
      "School of Environmental Studies",
      "School of Vocational and Technical Education"
    ]
  },
  {
    "id": "fce_bama",
    "name": "Federal College of Education, Gwoza (formerly Bama)",
    "shortName": "FCE Gwoza",
    "type": "Federal College of Education",
    "ownership": "Federal",
    "state": "Borno",
    "city": "Gwoza",
    "geopoliticalZone": "North East",
    "establishedYear": 2020,
    "motto": "Light of Knowledge and Service",
    "logoColor": "#2e7d32",
    "gradingSystem": "4.0",
    "websiteUrl": "https://fcegwoza.edu.ng",
    "regulator": "NCCE",
    "accreditationStatus": "Accredited",
    "verificationStatus": "Verified",
    "sourceUrl": "https://ncceonline.edu.ng",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Federal teacher education college established to expand educational access and train qualified educators in Borno State.",
    "faculties": [
      "School of Sciences",
      "School of Vocational and Technical Education",
      "School of Arts and Social Sciences",
      "School of Languages",
      "School of Education"
    ]
  },
  {
    "id": "borno_nursing_maiduguri",
    "name": "Borno State College of Nursing and Midwifery, Maiduguri",
    "shortName": "CONM Maiduguri",
    "type": "College of Nursing Sciences",
    "ownership": "State",
    "state": "Borno",
    "city": "Maiduguri",
    "geopoliticalZone": "North East",
    "establishedYear": 1978,
    "motto": "Compassion, Skill and Life",
    "logoColor": "#00838f",
    "gradingSystem": "4.0",
    "websiteUrl": "https://conmmaiduguri.edu.ng",
    "regulator": "NMCN",
    "accreditationStatus": "Accredited",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nmcn.gov.ng",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Major nursing college in Borno State training professional registered nurses, midwives, and public health nursing personnel.",
    "faculties": [
      "Department of Nursing",
      "Department of Midwifery"
    ]
  },

  # ----------------------------------------------------
  # GOMBE STATE
  # ----------------------------------------------------
  {
    "id": "fukashere",
    "name": "Federal University, Kashere",
    "shortName": "FUKASHERE",
    "type": "Federal University",
    "ownership": "Federal",
    "state": "Gombe",
    "city": "Kashere, Akko",
    "geopoliticalZone": "North East",
    "establishedYear": 2011,
    "motto": "Education for Global Excellence",
    "logoColor": "#1565c0",
    "gradingSystem": "5.0",
    "websiteUrl": "https://fukashere.edu.ng",
    "portalUrl": "https://portal.fukashere.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/federal-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Federal university in Gombe State offering comprehensive degree programmes in agriculture, natural sciences, management, and humanities.",
    "faculties": [
      "Faculty of Science",
      "Faculty of Agriculture",
      "Faculty of Management Sciences",
      "Faculty of Social Sciences",
      "Faculty of Humanities",
      "Faculty of Education"
    ]
  },
  {
    "id": "gsu_gombe",
    "name": "Gombe State University, Gombe",
    "shortName": "GSU",
    "type": "State University",
    "ownership": "State",
    "state": "Gombe",
    "city": "Tudun Wada, Gombe",
    "geopoliticalZone": "North East",
    "establishedYear": 2004,
    "motto": "Primus Inter Pares (First Among Equals)",
    "logoColor": "#004d40",
    "gradingSystem": "5.0",
    "websiteUrl": "https://gsu.edu.ng",
    "portalUrl": "https://portal.gsu.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/state-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Consistently recognized as one of the best organized state universities in Northern Nigeria, famous for its medical college, pharmacy, and sciences.",
    "faculties": [
      "College of Medical Sciences",
      "Faculty of Pharmaceutical Sciences",
      "Faculty of Science",
      "Faculty of Arts and Social Sciences",
      "Faculty of Education",
      "Faculty of Law"
    ]
  },
  {
    "id": "fedpoly_kaltungo",
    "name": "Federal Polytechnic, Kaltungo",
    "shortName": "FPK",
    "type": "Federal Polytechnic",
    "ownership": "Federal",
    "state": "Gombe",
    "city": "Kaltungo",
    "geopoliticalZone": "North East",
    "establishedYear": 2019,
    "motto": "Technological Skill and Innovation",
    "logoColor": "#b71c1c",
    "gradingSystem": "4.0",
    "websiteUrl": "https://fedpolykaltungo.edu.ng",
    "portalUrl": "https://portal.fedpolykaltungo.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Accredited",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/polytechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Modern federal polytechnic delivering certified National Diploma courses in engineering, computer science, and business.",
    "faculties": [
      "School of Engineering Technology",
      "School of Applied Sciences",
      "School of Business Studies"
    ]
  },
  {
    "id": "fce_technical_gombe",
    "name": "Federal College of Education (Technical), Gombe",
    "shortName": "FCET Gombe",
    "type": "Federal College of Education",
    "ownership": "Federal",
    "state": "Gombe",
    "city": "Gombe",
    "geopoliticalZone": "North East",
    "establishedYear": 1977,
    "motto": "Skill and Excellence in Technical Education",
    "logoColor": "#2e7d32",
    "gradingSystem": "4.0",
    "websiteUrl": "https://fcetgombe.edu.ng",
    "portalUrl": "https://portal.fcetgombe.edu.ng",
    "regulator": "NCCE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://ncceonline.edu.ng",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Premier federal technical teacher training institution in the North East delivering NCE and university degree affiliations with ATBU.",
    "faculties": [
      "School of Technical Education",
      "School of Vocational Education",
      "School of Science Education",
      "School of Business Education",
      "School of Education"
    ]
  },
  {
    "id": "gombe_health_kaltungo",
    "name": "Gombe State College of Health Sciences and Technology, Kaltungo",
    "shortName": "CHST Kaltungo",
    "type": "College of Health Sciences and Technology",
    "ownership": "State",
    "state": "Gombe",
    "city": "Kaltungo",
    "geopoliticalZone": "North East",
    "establishedYear": 2012,
    "motto": "Service to Humanity",
    "logoColor": "#00838f",
    "gradingSystem": "4.0",
    "websiteUrl": "https://chstkaltungo.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Accredited",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "State health sciences college training community health workers, pharmacy technicians, and environmental health practitioners.",
    "faculties": [
      "Department of Community Health",
      "Department of Pharmacy Technician",
      "Department of Medical Laboratory Science",
      "Department of Environmental Health"
    ]
  },

  # ----------------------------------------------------
  # TARABA STATE
  # ----------------------------------------------------
  {
    "id": "fuwukari",
    "name": "Federal University, Wukari",
    "shortName": "FUWUKARI",
    "type": "Federal University",
    "ownership": "Federal",
    "state": "Taraba",
    "city": "Wukari",
    "geopoliticalZone": "North East",
    "establishedYear": 2011,
    "motto": "Character, Excellence and Service",
    "logoColor": "#1565c0",
    "gradingSystem": "5.0",
    "websiteUrl": "https://fuwukari.edu.ng",
    "portalUrl": "https://portal.fuwukari.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/federal-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Federal university located in ancient Wukari kingdom, renowned for agriculture, natural sciences, engineering, and humanities.",
    "faculties": [
      "Faculty of Pure and Applied Sciences",
      "Faculty of Agriculture and Life Sciences",
      "Faculty of Engineering",
      "Faculty of Humanities, Management and Social Sciences",
      "Faculty of Education"
    ]
  },
  {
    "id": "tsu_jalingo",
    "name": "Taraba State University, Jalingo",
    "shortName": "TSU",
    "type": "State University",
    "ownership": "State",
    "state": "Taraba",
    "city": "Jalingo",
    "geopoliticalZone": "North East",
    "establishedYear": 2008,
    "motto": "Harnessing Nature for Greater Heights",
    "logoColor": "#004d40",
    "gradingSystem": "5.0",
    "websiteUrl": "https://tsuniversity.edu.ng",
    "portalUrl": "https://portal.tsuniversity.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/state-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "State university located in the state capital Jalingo, delivering accredited programmes in health sciences, law, engineering, agriculture, and sciences.",
    "faculties": [
      "Faculty of Science",
      "Faculty of Health Sciences",
      "Faculty of Law",
      "Faculty of Engineering",
      "Faculty of Agriculture",
      "Faculty of Management Sciences",
      "Faculty of Social Sciences",
      "Faculty of Arts",
      "Faculty of Education"
    ]
  },
  {
    "id": "fedpoly_bali",
    "name": "Federal Polytechnic, Bali",
    "shortName": "FEDPOBALI",
    "type": "Federal Polytechnic",
    "ownership": "Federal",
    "state": "Taraba",
    "city": "Bali",
    "geopoliticalZone": "North East",
    "establishedYear": 2007,
    "motto": "Skill for Self-Reliance",
    "logoColor": "#b71c1c",
    "gradingSystem": "4.0",
    "websiteUrl": "https://fedpolybali.edu.ng",
    "portalUrl": "https://portal.fedpolybali.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/polytechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Federal polytechnic providing accredited National Diploma courses in agricultural technology, computer science, statistics, and business.",
    "faculties": [
      "School of Engineering Technology",
      "School of Applied Sciences",
      "School of Management Studies",
      "School of Environmental Studies"
    ]
  },
  {
    "id": "coe_zing",
    "name": "College of Education, Zing",
    "shortName": "COE Zing",
    "type": "State College of Education",
    "ownership": "State",
    "state": "Taraba",
    "city": "Zing",
    "geopoliticalZone": "North East",
    "establishedYear": 1978,
    "motto": "Education for Service",
    "logoColor": "#2e7d32",
    "gradingSystem": "4.0",
    "websiteUrl": "https://coezing.edu.ng",
    "regulator": "NCCE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://ncceonline.edu.ng",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Major state teacher education college offering NCE diplomas in sciences, arts, and vocational education.",
    "faculties": [
      "School of Sciences",
      "School of Vocational and Technical Education",
      "School of Arts and Social Sciences",
      "School of Languages",
      "School of Education"
    ]
  },

  # ----------------------------------------------------
  # YOBE STATE
  # ----------------------------------------------------
  {
    "id": "fu_gashua",
    "name": "Federal University, Gashua",
    "shortName": "FUGASHUA",
    "type": "Federal University",
    "ownership": "Federal",
    "state": "Yobe",
    "city": "Gashua, Bade",
    "geopoliticalZone": "North East",
    "establishedYear": 2013,
    "motto": "Knowledge for Self-Reliance",
    "logoColor": "#1565c0",
    "gradingSystem": "5.0",
    "websiteUrl": "https://fugashua.edu.ng",
    "portalUrl": "https://portal.fugashua.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/federal-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Federal university located in northern Yobe State, acclaimed for agriculture, computing, natural sciences, and management.",
    "faculties": [
      "Faculty of Science",
      "Faculty of Agriculture",
      "Faculty of Management and Social Sciences",
      "Faculty of Arts and Humanities"
    ]
  },
  {
    "id": "ysu_damaturu",
    "name": "Yobe State University, Damaturu",
    "shortName": "YSU",
    "type": "State University",
    "ownership": "State",
    "state": "Yobe",
    "city": "Damaturu",
    "geopoliticalZone": "North East",
    "establishedYear": 2006,
    "motto": "Knowledge is Light",
    "logoColor": "#004d40",
    "gradingSystem": "5.0",
    "websiteUrl": "https://ysu.edu.ng",
    "portalUrl": "https://ysu.safsrms.com",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/state-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "State university located in Damaturu, featuring medical college, law, natural sciences, arts, and education.",
    "faculties": [
      "College of Medical Sciences",
      "Faculty of Law",
      "Faculty of Science",
      "Faculty of Management Sciences",
      "Faculty of Social Sciences",
      "Faculty of Arts and Education"
    ]
  },
  {
    "id": "fedpoly_damaturu",
    "name": "Federal Polytechnic, Damaturu",
    "shortName": "FEDPODAM",
    "type": "Federal Polytechnic",
    "ownership": "Federal",
    "state": "Yobe",
    "city": "Damaturu",
    "geopoliticalZone": "North East",
    "establishedYear": 1993,
    "motto": "Technology for Self-Reliance",
    "logoColor": "#b71c1c",
    "gradingSystem": "4.0",
    "websiteUrl": "https://fedpodam.edu.ng",
    "portalUrl": "https://portal.fedpodam.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/polytechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Federal polytechnic delivering accredited engineering, science technology, computer science, and business diplomas.",
    "faculties": [
      "School of Engineering Technology",
      "School of Science and Technology",
      "School of Management Studies",
      "School of Environmental Studies"
    ]
  },
  {
    "id": "fce_technical_potiskum",
    "name": "Federal College of Education (Technical), Potiskum",
    "shortName": "FCET Potiskum",
    "type": "Federal College of Education",
    "ownership": "Federal",
    "state": "Yobe",
    "city": "Potiskum",
    "geopoliticalZone": "North East",
    "establishedYear": 1986,
    "motto": "Technology for Better Education",
    "logoColor": "#2e7d32",
    "gradingSystem": "4.0",
    "websiteUrl": "https://fcetpotiskum.edu.ng",
    "portalUrl": "https://portal.fcetpotiskum.edu.ng",
    "regulator": "NCCE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://ncceonline.edu.ng",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Federal technical teacher college delivering high-level pedagogical and technical skills for secondary and technical schools.",
    "faculties": [
      "School of Technical Education",
      "School of Vocational Education",
      "School of Science Education",
      "School of Business Education",
      "School of Education"
    ]
  },
  {
    "id": "yobe_health_nguru",
    "name": "Shehu Sule College of Nursing and Midwifery, Damaturu",
    "shortName": "SSCONM",
    "type": "College of Nursing Sciences",
    "ownership": "State",
    "state": "Yobe",
    "city": "Damaturu",
    "geopoliticalZone": "North East",
    "establishedYear": 1993,
    "motto": "Excellence in Nursing Care",
    "logoColor": "#00838f",
    "gradingSystem": "4.0",
    "websiteUrl": "https://ssconm.edu.ng",
    "regulator": "NMCN",
    "accreditationStatus": "Accredited",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nmcn.gov.ng",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "State college training professional registered nurses and midwives with accredited clinical postings.",
    "faculties": [
      "Department of Nursing",
      "Department of Midwifery"
    ]
  }
]
