# NORTH WEST ZONE: Jigawa, Kaduna, Kano, Katsina, Kebbi, Sokoto, Zamfara

DATA = [
  # ----------------------------------------------------
  # JIGAWA STATE
  # ----------------------------------------------------
  {
    "id": "fud_dutse",
    "name": "Federal University, Dutse",
    "shortName": "FUD",
    "type": "Federal University",
    "ownership": "Federal",
    "state": "Jigawa",
    "city": "Dutse",
    "geopoliticalZone": "North West",
    "establishedYear": 2011,
    "motto": "Knowledge, Excellence and Service",
    "logoColor": "#1565c0",
    "gradingSystem": "5.0",
    "websiteUrl": "https://fud.edu.ng",
    "portalUrl": "https://portal.fud.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/federal-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Rapidly advancing federal university with a thriving College of Medicine and Allied Medical Sciences, computing, biotechnology, and agriculture.",
    "faculties": [
      "College of Medicine and Allied Medical Sciences",
      "Faculty of Science",
      "Faculty of Computing",
      "Faculty of Agriculture",
      "Faculty of Management Sciences",
      "Faculty of Arts and Social Sciences",
      "Faculty of Education"
    ]
  },
  {
    "id": "jisu_kafin_hausa",
    "name": "Sule Lamido University, Kafin Hausa",
    "shortName": "SLU",
    "type": "State University",
    "ownership": "State",
    "state": "Jigawa",
    "city": "Kafin Hausa",
    "geopoliticalZone": "North West",
    "establishedYear": 2013,
    "motto": "Knowledge for Advancement",
    "logoColor": "#004d40",
    "gradingSystem": "5.0",
    "websiteUrl": "https://slu.edu.ng",
    "portalUrl": "https://portal.slu.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/state-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Jigawa State university delivering accredited degree programmes in natural and applied sciences, humanities, and education.",
    "faculties": [
      "Faculty of Natural and Applied Sciences",
      "Faculty of Humanities",
      "Faculty of Education",
      "Faculty of Agriculture"
    ]
  },
  {
    "id": "hussaini_adamu_poly",
    "name": "Hussaini Adamu Federal Polytechnic, Kazaure",
    "shortName": "HAFEDPOLY",
    "type": "Federal Polytechnic",
    "ownership": "Federal",
    "state": "Jigawa",
    "city": "Kazaure",
    "geopoliticalZone": "North West",
    "establishedYear": 1991,
    "motto": "Technology for Self Reliance",
    "logoColor": "#b71c1c",
    "gradingSystem": "4.0",
    "websiteUrl": "https://hafedpoly.edu.ng",
    "portalUrl": "https://portal.hafedpoly.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/polytechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Federal polytechnic renowned for engineering, fashion and textile technology, computing, and environmental studies.",
    "faculties": [
      "College of Engineering Technology",
      "College of Science and Technology",
      "College of Environmental Studies",
      "College of Administrative and Business Studies",
      "College of Agricultural Technology"
    ]
  },
  {
    "id": "jigawa_poly_dutse",
    "name": "Binyaminu Usman Polytechnic, Hadejia",
    "shortName": "BUPOLY",
    "type": "State Polytechnic",
    "ownership": "State",
    "state": "Jigawa",
    "city": "Hadejia",
    "geopoliticalZone": "North West",
    "establishedYear": 1992,
    "motto": "Skill, Knowledge and Character",
    "logoColor": "#e65100",
    "gradingSystem": "4.0",
    "websiteUrl": "https://bupoly.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/polytechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "State polytechnic in Hadejia focused on agricultural technology, fisheries, computer science, and management.",
    "faculties": [
      "School of Agricultural Technology",
      "School of Applied Sciences",
      "School of Business and Management Studies"
    ]
  },
  {
    "id": "fce_gumel",
    "name": "Federal College of Education, Gumel",
    "shortName": "FCE Gumel",
    "type": "Federal College of Education",
    "ownership": "Federal",
    "state": "Jigawa",
    "city": "Gumel",
    "geopoliticalZone": "North West",
    "establishedYear": 1976,
    "motto": "Knowledge for Enlightenment",
    "logoColor": "#2e7d32",
    "gradingSystem": "4.0",
    "websiteUrl": "https://fcegumel.edu.ng",
    "portalUrl": "https://portal.fcegumel.edu.ng",
    "regulator": "NCCE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://ncceonline.edu.ng",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Historic federal teacher training college offering NCE and undergraduate degree affiliated courses with BUK.",
    "faculties": [
      "School of Sciences",
      "School of Vocational and Technical Education",
      "School of Arts and Social Sciences",
      "School of Languages",
      "School of Education"
    ]
  },

  # ----------------------------------------------------
  # KADUNA STATE
  # ----------------------------------------------------
  {
    "id": "abu_zaria",
    "name": "Ahmadu Bello University, Zaria",
    "shortName": "ABU",
    "type": "Federal University",
    "ownership": "Federal",
    "state": "Kaduna",
    "city": "Samaru & Kongo, Zaria",
    "geopoliticalZone": "North West",
    "establishedYear": 1962,
    "motto": "The First shall be the First (Ahmadu Bello)",
    "logoColor": "#1b5e20",
    "gradingSystem": "5.0",
    "websiteUrl": "https://abu.edu.ng",
    "portalUrl": "https://portal.abu.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/federal-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Nigeria's largest first-generation federal university and Sub-Saharan Africa's premier institution, world-renowned for medicine, pharmacy, veterinary medicine, engineering, architecture, law (Kongo Campus), and agriculture (IAR).",
    "faculties": [
      "Faculty of Medicine / College of Medical Sciences",
      "Faculty of Pharmaceutical Sciences",
      "Faculty of Veterinary Medicine",
      "Faculty of Engineering",
      "Faculty of Physical Sciences",
      "Faculty of Life Sciences",
      "Faculty of Environmental Design",
      "Faculty of Law (Kongo)",
      "Faculty of Administration (Kongo)",
      "Faculty of Social Sciences",
      "Faculty of Arts",
      "Faculty of Agriculture",
      "Faculty of Education",
      "Faculty of Dental Surgery"
    ]
  },
  {
    "id": "kasu_kaduna",
    "name": "Kaduna State University, Kaduna",
    "shortName": "KASU",
    "type": "State University",
    "ownership": "State",
    "state": "Kaduna",
    "city": "Kaduna & Kafanchan",
    "geopoliticalZone": "North West",
    "establishedYear": 2004,
    "motto": "Knowledge for National Development",
    "logoColor": "#0d47a1",
    "gradingSystem": "5.0",
    "websiteUrl": "https://kasu.edu.ng",
    "portalUrl": "https://portal.kasu.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/state-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Flagship multi-campus state university in Kaduna and Kafanchan, renowned for its college of medicine, pharmacy, computer science, and management.",
    "faculties": [
      "College of Medicine",
      "Faculty of Pharmaceutical Sciences",
      "Faculty of Science",
      "Faculty of Management Sciences",
      "Faculty of Social Sciences",
      "Faculty of Arts",
      "Faculty of Environmental Sciences (Kafanchan)",
      "Faculty of Agriculture (Kafanchan)",
      "Faculty of Education"
    ]
  },
  {
    "id": "nda_kaduna",
    "name": "Nigerian Defence Academy, Kaduna",
    "shortName": "NDA",
    "type": "Federal University",
    "ownership": "Federal",
    "state": "Kaduna",
    "city": "Afaka & Ribadu, Kaduna",
    "geopoliticalZone": "North West",
    "establishedYear": 1964,
    "motto": "Loyalty and Valour",
    "logoColor": "#b71c1c",
    "gradingSystem": "5.0",
    "websiteUrl": "https://nda.edu.ng",
    "portalUrl": "https://portal.nda.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/federal-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Nigeria's premier military university training officer cadets and postgraduates across engineering, military sciences, and security studies.",
    "faculties": [
      "Faculty of Engineering",
      "Faculty of Science",
      "Faculty of Military Science and Interdisciplinary Studies",
      "Faculty of Management Sciences",
      "Faculty of Arts and Social Sciences"
    ]
  },
  {
    "id": "kadpoly",
    "name": "Kaduna Polytechnic, Kaduna",
    "shortName": "KADPOLY",
    "type": "Federal Polytechnic",
    "ownership": "Federal",
    "state": "Kaduna",
    "city": "Tudun Wada, Barnawa, Kaduna",
    "geopoliticalZone": "North West",
    "establishedYear": 1956,
    "motto": "Knowledge, Skill and Service",
    "logoColor": "#e65100",
    "gradingSystem": "4.0",
    "websiteUrl": "https://kadunapoly.edu.ng",
    "portalUrl": "https://portal.kadunapolytechnic.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/polytechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "One of the largest and most prestigious polytechnics in Sub-Saharan Africa, offering world-class engineering, sciences, administrative studies, and environmental design.",
    "faculties": [
      "College of Engineering (COE)",
      "College of Science and Technology (CST)",
      "College of Business and Management Studies (CBMS)",
      "College of Environmental Studies (CES)",
      "College of Administrative Studies and Social Sciences (CASSS)"
    ]
  },
  {
    "id": "ncat_zaria",
    "name": "Nigerian College of Aviation Technology, Zaria",
    "shortName": "NCAT",
    "type": "Monotechnic / Specialized Institution",
    "ownership": "Federal",
    "state": "Kaduna",
    "city": "Zaria",
    "geopoliticalZone": "North West",
    "establishedYear": 1964,
    "motto": "Excellence in Aviation Training",
    "logoColor": "#01579b",
    "gradingSystem": "4.0",
    "websiteUrl": "https://ncat.gov.ng",
    "portalUrl": "https://portal.ncat.gov.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/monotechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "ICAO Regional Training Centre of Excellence, premier aviation training institution in Africa for pilots, aircraft maintenance engineers, and air traffic controllers.",
    "faculties": [
      "Flying School",
      "Aeronautical Telecommunications Engineering School",
      "Aircraft Maintenance Engineering School",
      "Air Traffic Services / Communication School",
      "Aviation Management School"
    ]
  },
  {
    "id": "fce_zaria",
    "name": "Federal College of Education, Zaria",
    "shortName": "FCE Zaria",
    "type": "Federal College of Education",
    "ownership": "Federal",
    "state": "Kaduna",
    "city": "Zaria",
    "geopoliticalZone": "North West",
    "establishedYear": 1962,
    "motto": "Knowledge for Light",
    "logoColor": "#2e7d32",
    "gradingSystem": "4.0",
    "websiteUrl": "https://fcezaria.edu.ng",
    "portalUrl": "https://portal.fcezaria.edu.ng",
    "regulator": "NCCE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://ncceonline.edu.ng",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Historic federal teacher training college offering accredited NCE and degree affiliation programmes with ABU Zaria.",
    "faculties": [
      "School of Sciences",
      "School of Vocational and Technical Education",
      "School of Arts and Social Sciences",
      "School of Languages",
      "School of Education"
    ]
  },
  {
    "id": "nitt_zaria",
    "name": "Nigerian Institute of Transport Technology, Zaria",
    "shortName": "NITT",
    "type": "Monotechnic / Specialized Institution",
    "ownership": "Federal",
    "state": "Kaduna",
    "city": "Basawa, Zaria",
    "geopoliticalZone": "North West",
    "establishedYear": 1986,
    "motto": "Excellence in Transport and Logistics Training",
    "logoColor": "#004d40",
    "gradingSystem": "4.0",
    "websiteUrl": "https://nitt.gov.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/monotechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Apex federal transport, logistics, and supply chain technology research and training institute.",
    "faculties": [
      "Transport Technology and Infrastructure",
      "Logistics and Supply Chain Management",
      "Transport School of Management"
    ]
  },

  # ----------------------------------------------------
  # KANO STATE
  # ----------------------------------------------------
  {
    "id": "buk_kano",
    "name": "Bayero University, Kano",
    "shortName": "BUK",
    "type": "Federal University",
    "ownership": "Federal",
    "state": "Kano",
    "city": "Kano",
    "geopoliticalZone": "North West",
    "establishedYear": 1975,
    "motto": "Wa Fawqa Kulli Dhi Ilmin Alim (And Above Every Possessor of Knowledge, There is One More Knowing)",
    "logoColor": "#1565c0",
    "gradingSystem": "5.0",
    "websiteUrl": "https://buk.edu.ng",
    "portalUrl": "https://mybuk2.buk.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/federal-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Major second-generation federal university, acclaimed for medical sciences, engineering, computing, law, agriculture, Islamic studies, and pharmacy.",
    "faculties": [
      "College of Health Sciences",
      "Faculty of Pharmaceutical Sciences",
      "Faculty of Computer Science and Information Technology",
      "Faculty of Engineering",
      "Faculty of Physical Sciences",
      "Faculty of Life Sciences",
      "Faculty of Law",
      "Faculty of Management Sciences",
      "Faculty of Social Sciences",
      "Faculty of Arts and Islamic Studies",
      "Faculty of Agriculture",
      "Faculty of Earth and Environmental Sciences",
      "Faculty of Education",
      "Faculty of Dentistry"
    ]
  },
  {
    "id": "kust_wudil",
    "name": "Aliko Dangote University of Science and Technology, Wudil (KUST)",
    "shortName": "ADUSTECH / KUST",
    "type": "State University",
    "ownership": "State",
    "state": "Kano",
    "city": "Wudil",
    "geopoliticalZone": "North West",
    "establishedYear": 2001,
    "motto": "Science and Technology for Humanity",
    "logoColor": "#004d40",
    "gradingSystem": "5.0",
    "websiteUrl": "https://kustwudil.edu.ng",
    "portalUrl": "https://portal.kustwudil.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/state-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Pioneering state university of science and technology in Northern Nigeria named after billionaire industrialist Aliko Dangote.",
    "faculties": [
      "Faculty of Engineering",
      "Faculty of Computing and Mathematical Sciences",
      "Faculty of Earth and Environmental Sciences",
      "Faculty of Science",
      "Faculty of Agriculture and Agricultural Technology",
      "Faculty of Science and Technical Education"
    ]
  },
  {
    "id": "yumsu_kano",
    "name": "Yusuf Maitama Sule University, Kano (Northwest University)",
    "shortName": "YUMSUK / NWU",
    "type": "State University",
    "ownership": "State",
    "state": "Kano",
    "city": "Kano",
    "geopoliticalZone": "North West",
    "establishedYear": 2012,
    "motto": "Knowledge for National Development",
    "logoColor": "#b71c1c",
    "gradingSystem": "5.0",
    "websiteUrl": "https://yumsuk.edu.ng",
    "portalUrl": "https://portal.yumsuk.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/state-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Metropolitan state university in Kano with expanding faculties of basic medical sciences, sciences, humanities, and education.",
    "faculties": [
      "Faculty of Basic Medical Sciences",
      "Faculty of Science",
      "Faculty of Humanities",
      "Faculty of Social and Management Sciences",
      "Faculty of Education"
    ]
  },
  {
    "id": "maryam_abacha_uni",
    "name": "Maryam Abacha American University of Nigeria, Kano",
    "shortName": "MAAUN",
    "type": "Private University",
    "ownership": "Private",
    "state": "Kano",
    "city": "Hotoro GRA, Kano",
    "geopoliticalZone": "North West",
    "establishedYear": 2021,
    "motto": "Knowledge, Innovation and Character",
    "logoColor": "#4a148c",
    "gradingSystem": "5.0",
    "websiteUrl": "https://maaun.edu.ng",
    "portalUrl": "https://portal.maaun.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Accredited",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/private-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Leading private international university in Kano featuring modern digital medical, nursing, computing, and business facilities.",
    "faculties": [
      "School of Health Sciences",
      "School of Nursing Sciences",
      "School of Computing",
      "School of Social and Management Sciences",
      "School of Law"
    ]
  },
  {
    "id": "kano_poly_kano",
    "name": "Kano State Polytechnic, Kano",
    "shortName": "KANOPOLY",
    "type": "State Polytechnic",
    "ownership": "State",
    "state": "Kano",
    "city": "Kano",
    "geopoliticalZone": "North West",
    "establishedYear": 1975,
    "motto": "Technology for Economic Emancipation",
    "logoColor": "#e65100",
    "gradingSystem": "4.0",
    "websiteUrl": "https://kanopoly.edu.ng",
    "portalUrl": "https://portal.kanopoly.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/polytechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Major polytechnic comprising the School of Technology, School of Management Studies, and School of Environmental Studies.",
    "faculties": [
      "School of Technology (SOT)",
      "School of Management Studies (SMS)",
      "School of Environmental Studies (SES)",
      "School of General and Liberal Studies"
    ]
  },
  {
    "id": "fce_technical_bichi",
    "name": "Federal College of Education (Technical), Bichi",
    "shortName": "FCET Bichi",
    "type": "Federal College of Education",
    "ownership": "Federal",
    "state": "Kano",
    "city": "Bichi",
    "geopoliticalZone": "North West",
    "establishedYear": 1986,
    "motto": "Work, Skill and Technical Progress",
    "logoColor": "#2e7d32",
    "gradingSystem": "4.0",
    "websiteUrl": "https://fcetbichi.edu.ng",
    "portalUrl": "https://portal.fcetbichi.edu.ng",
    "regulator": "NCCE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://ncceonline.edu.ng",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Federal technical teacher college offering accredited NCE and undergraduate degree affiliation courses in technical education.",
    "faculties": [
      "School of Technical Education",
      "School of Vocational Education",
      "School of Science Education",
      "School of Business Education",
      "School of Education"
    ]
  },
  {
    "id": "fce_katsina_kano",
    "name": "Federal College of Education, Kano",
    "shortName": "FCE Kano",
    "type": "Federal College of Education",
    "ownership": "Federal",
    "state": "Kano",
    "city": "Kano",
    "geopoliticalZone": "North West",
    "establishedYear": 1961,
    "motto": "Knowledge for Enlightenment",
    "logoColor": "#00796b",
    "gradingSystem": "4.0",
    "websiteUrl": "https://fcekano.edu.ng",
    "portalUrl": "https://portal.fcekano.edu.ng",
    "regulator": "NCCE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://ncceonline.edu.ng",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "One of Nigeria's oldest teacher training institutions, offering extensive NCE and degree affiliations with ABU and UNIMAID.",
    "faculties": [
      "School of Sciences",
      "School of Vocational and Technical Education",
      "School of Arts and Social Sciences",
      "School of Languages",
      "School of Education",
      "School of Early Childhood Care and Primary Education"
    ]
  },

  # ----------------------------------------------------
  # KATSINA STATE
  # ----------------------------------------------------
  {
    "id": "fudma_dutsinma",
    "name": "Federal University, Dutsin-Ma",
    "shortName": "FUDMA",
    "type": "Federal University",
    "ownership": "Federal",
    "state": "Katsina",
    "city": "Dutsin-Ma",
    "geopoliticalZone": "North West",
    "establishedYear": 2011,
    "motto": "Integrity, Excellence and Service",
    "logoColor": "#1565c0",
    "gradingSystem": "5.0",
    "websiteUrl": "https://fudutsinma.edu.ng",
    "portalUrl": "https://portal.fudutsinma.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/federal-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Federal university with rapidly growing faculties in health sciences, agriculture, natural sciences, engineering, and education.",
    "faculties": [
      "Faculty of Health Sciences",
      "Faculty of Science",
      "Faculty of Engineering and Technology",
      "Faculty of Agriculture and Agricultural Technology",
      "Faculty of Management Sciences",
      "Faculty of Social Sciences",
      "Faculty of Arts",
      "Faculty of Education"
    ]
  },
  {
    "id": "umyu_katsina",
    "name": "Umaru Musa Yar'adua University, Katsina",
    "shortName": "UMYU",
    "type": "State University",
    "ownership": "State",
    "state": "Katsina",
    "city": "Katsina",
    "geopoliticalZone": "North West",
    "establishedYear": 2006,
    "motto": "To Learn and To Serve",
    "logoColor": "#004d40",
    "gradingSystem": "5.0",
    "websiteUrl": "https://umyu.edu.ng",
    "portalUrl": "https://portal.umyu.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/state-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "State university named after President Umaru Musa Yar'adua, acclaimed for natural and applied sciences, law, humanities, and education.",
    "faculties": [
      "Faculty of Natural and Applied Sciences",
      "Faculty of Law",
      "Faculty of Social and Management Sciences",
      "Faculty of Humanities",
      "Faculty of Education"
    ]
  },
  {
    "id": "al_qalam_uni",
    "name": "Al-Qalam University, Katsina",
    "shortName": "AUK",
    "type": "Private University",
    "ownership": "Private",
    "state": "Katsina",
    "city": "Katsina",
    "geopoliticalZone": "North West",
    "establishedYear": 2005,
    "motto": "Knowledge with Virtue",
    "logoColor": "#b71c1c",
    "gradingSystem": "5.0",
    "websiteUrl": "https://auk.edu.ng",
    "portalUrl": "https://portal.auk.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/private-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Nigeria's first Islamic private university, offering accredited programmes in nursing, computing, natural sciences, humanities, and education.",
    "faculties": [
      "College of Basic Medical Sciences",
      "College of Natural and Applied Sciences",
      "College of Computing",
      "College of Social and Management Sciences",
      "College of Humanities",
      "College of Education"
    ]
  },
  {
    "id": "hassan_usman_katsina_poly",
    "name": "Hassan Usman Katsina Polytechnic, Katsina",
    "shortName": "HUKPOLY",
    "type": "State Polytechnic",
    "ownership": "State",
    "state": "Katsina",
    "city": "Katsina",
    "geopoliticalZone": "North West",
    "establishedYear": 1983,
    "motto": "Skill for Advancement",
    "logoColor": "#e65100",
    "gradingSystem": "4.0",
    "websiteUrl": "https://hukpoly.edu.ng",
    "portalUrl": "https://portal.hukpoly.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/polytechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Leading state polytechnic offering technical ND and HND engineering, computing, agricultural technology, and management courses.",
    "faculties": [
      "College of Engineering",
      "College of Science and Technology",
      "College of Administration and Management Studies",
      "College of Environmental Studies",
      "College of Vocational and Technical Education"
    ]
  },
  {
    "id": "fce_katsina",
    "name": "Federal College of Education, Katsina",
    "shortName": "FCE Katsina",
    "type": "Federal College of Education",
    "ownership": "Federal",
    "state": "Katsina",
    "city": "Katsina",
    "geopoliticalZone": "North West",
    "establishedYear": 1976,
    "motto": "Education for Development",
    "logoColor": "#2e7d32",
    "gradingSystem": "4.0",
    "websiteUrl": "https://fcekatsina.edu.ng",
    "portalUrl": "https://portal.fcekatsina.edu.ng",
    "regulator": "NCCE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://ncceonline.edu.ng",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Major federal teacher training college in Katsina State delivering NCE and university undergraduate degree credentials.",
    "faculties": [
      "School of Sciences",
      "School of Vocational and Technical Education",
      "School of Arts and Social Sciences",
      "School of Languages",
      "School of Education"
    ]
  },

  # ----------------------------------------------------
  # KEBBI STATE
  # ----------------------------------------------------
  {
    "id": "fubk_birnin_kebbi",
    "name": "Federal University, Birnin Kebbi",
    "shortName": "FUBK",
    "type": "Federal University",
    "ownership": "Federal",
    "state": "Kebbi",
    "city": "Birnin Kebbi",
    "geopoliticalZone": "North West",
    "establishedYear": 2013,
    "motto": "Learning, Character and Service",
    "logoColor": "#1565c0",
    "gradingSystem": "5.0",
    "websiteUrl": "https://fubk.edu.ng",
    "portalUrl": "https://portal.fubk.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/federal-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Federal university with medical college, nursing sciences, architectural technology, sciences, and management sciences.",
    "faculties": [
      "College of Health Sciences",
      "Faculty of Science",
      "Faculty of Environmental Sciences",
      "Faculty of Social and Management Sciences",
      "Faculty of Arts and Education"
    ]
  },
  {
    "id": "khasu_aliero",
    "name": "Kebbi State University of Science and Technology, Aliero",
    "shortName": "KSUSTA",
    "type": "State University",
    "ownership": "State",
    "state": "Kebbi",
    "city": "Aliero",
    "geopoliticalZone": "North West",
    "establishedYear": 2006,
    "motto": "Science and Technology for Development",
    "logoColor": "#004d40",
    "gradingSystem": "5.0",
    "websiteUrl": "https://ksusta.edu.ng",
    "portalUrl": "https://portal.ksusta.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/state-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Specialized state science and technology university offering engineering, agriculture, physical and biological sciences.",
    "faculties": [
      "Faculty of Engineering",
      "Faculty of Physical and Computing Sciences",
      "Faculty of Life Sciences",
      "Faculty of Agriculture",
      "Faculty of Education"
    ]
  },
  {
    "id": "fedpoly_kaura_namoda_kebbi",
    "name": "Waziri Umaru Federal Polytechnic, Birnin Kebbi",
    "shortName": "WUFPBK",
    "type": "Federal Polytechnic",
    "ownership": "Federal",
    "state": "Kebbi",
    "city": "Birnin Kebbi",
    "geopoliticalZone": "North West",
    "establishedYear": 1976,
    "motto": "Technology for Development",
    "logoColor": "#b71c1c",
    "gradingSystem": "4.0",
    "websiteUrl": "https://wufpbk.edu.ng",
    "portalUrl": "https://portal.wufpbk.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/polytechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Major federal polytechnic offering engineering, science technology, environmental studies, and management.",
    "faculties": [
      "Directorate of Engineering Technology",
      "Directorate of Science and Technology",
      "Directorate of Management Studies",
      "Directorate of Environmental Studies"
    ]
  },
  {
    "id": "kebbi_nursing_birnin_kebbi",
    "name": "Kebbi State College of Nursing Sciences, Birnin Kebbi",
    "shortName": "KBCON",
    "type": "College of Nursing Sciences",
    "ownership": "State",
    "state": "Kebbi",
    "city": "Birnin Kebbi",
    "geopoliticalZone": "North West",
    "establishedYear": 1982,
    "motto": "Excellence in Healthcare and Humanity",
    "logoColor": "#00838f",
    "gradingSystem": "4.0",
    "websiteUrl": "https://kebbiscon.edu.ng",
    "regulator": "NMCN",
    "accreditationStatus": "Accredited",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nmcn.gov.ng",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Accredited state nursing and midwifery college training registered nurses and certified midwives in Kebbi State.",
    "faculties": [
      "Department of Nursing",
      "Department of Midwifery"
    ]
  },

  # ----------------------------------------------------
  # SOKOTO STATE
  # ----------------------------------------------------
  {
    "id": "udusok",
    "name": "Usmanu Danfodiyo University, Sokoto",
    "shortName": "UDUS",
    "type": "Federal University",
    "ownership": "Federal",
    "state": "Sokoto",
    "city": "Sokoto",
    "geopoliticalZone": "North West",
    "establishedYear": 1975,
    "motto": "Iqra (Read in the Name of thy Lord)",
    "logoColor": "#1565c0",
    "gradingSystem": "5.0",
    "websiteUrl": "https://udusok.edu.ng",
    "portalUrl": "https://misau.udusok.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/federal-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Historic second-generation federal university named after Sheikh Usmanu Danfodiyo, acclaimed for medicine, veterinary medicine, pharmacy, law, agriculture, and sciences.",
    "faculties": [
      "College of Health Sciences",
      "Faculty of Veterinary Medicine",
      "Faculty of Pharmaceutical Sciences",
      "Faculty of Law",
      "Faculty of Physical Sciences",
      "Faculty of Chemical and Life Sciences",
      "Faculty of Engineering and Environmental Design",
      "Faculty of Management Sciences",
      "Faculty of Social Sciences",
      "Faculty of Arts and Islamic Studies",
      "Faculty of Agriculture",
      "Faculty of Education",
      "Faculty of Dental Sciences"
    ]
  },
  {
    "id": "ssu_sokoto",
    "name": "Sokoto State University, Sokoto",
    "shortName": "SSU",
    "type": "State University",
    "ownership": "State",
    "state": "Sokoto",
    "city": "Sokoto",
    "geopoliticalZone": "North West",
    "establishedYear": 2009,
    "motto": "Knowledge for Advancement",
    "logoColor": "#004d40",
    "gradingSystem": "5.0",
    "websiteUrl": "https://ssu.edu.ng",
    "portalUrl": "https://portal.ssu.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/state-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "State university located in the Caliphate city offering degree programmes in science, arts, social sciences, and education.",
    "faculties": [
      "Faculty of Science",
      "Faculty of Social Sciences",
      "Faculty of Arts",
      "Faculty of Education"
    ]
  },
  {
    "id": "sokoto_poly_sokoto",
    "name": "Umaru Ali Shinkafi Polytechnic, Sokoto",
    "shortName": "POLYSOKOTO",
    "type": "State Polytechnic",
    "ownership": "State",
    "state": "Sokoto",
    "city": "Sokoto",
    "geopoliticalZone": "North West",
    "establishedYear": 2002,
    "motto": "Skill and Integrity",
    "logoColor": "#e65100",
    "gradingSystem": "4.0",
    "websiteUrl": "https://uaspoly.edu.ng",
    "portalUrl": "https://portal.uaspoly.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/polytechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "State polytechnic delivering accredited engineering, science technology, computer science, and administrative courses.",
    "faculties": [
      "School of Engineering",
      "School of Applied Sciences",
      "School of Business Studies",
      "School of Environmental Studies"
    ]
  },
  {
    "id": "shehu_shagari_uni_edu",
    "name": "Shehu Shagari University of Education, Sokoto",
    "shortName": "SSUES",
    "type": "State University",
    "ownership": "State",
    "state": "Sokoto",
    "city": "Sokoto",
    "geopoliticalZone": "North West",
    "establishedYear": 1970,
    "motto": "Education for Development and Leadership",
    "logoColor": "#2e7d32",
    "gradingSystem": "5.0",
    "websiteUrl": "https://ssues.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/state-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Historic teacher college upgraded to a specialized state university of education named after President Shehu Shagari.",
    "faculties": [
      "Faculty of Science Education",
      "Faculty of Vocational and Technical Education",
      "Faculty of Arts and Social Science Education",
      "Faculty of Languages Education",
      "Faculty of Educational Foundation"
    ]
  },

  # ----------------------------------------------------
  # ZAMFARA STATE
  # ----------------------------------------------------
  {
    "id": "fugus_gusau",
    "name": "Federal University, Gusau",
    "shortName": "FUGUS",
    "type": "Federal University",
    "ownership": "Federal",
    "state": "Zamfara",
    "city": "Gusau",
    "geopoliticalZone": "North West",
    "establishedYear": 2013,
    "motto": "Knowledge, Innovation and Service",
    "logoColor": "#1565c0",
    "gradingSystem": "5.0",
    "websiteUrl": "https://fugusau.edu.ng",
    "portalUrl": "https://portal.fugusau.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/federal-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Federal university located in Zamfara State, offering accredited programmes in natural sciences, computing, humanities, and education.",
    "faculties": [
      "Faculty of Science",
      "Faculty of Management and Social Sciences",
      "Faculty of Humanities",
      "Faculty of Education"
    ]
  },
  {
    "id": "zamfara_state_uni_talata_mafara",
    "name": "Zamfara State University, Talata Mafara",
    "shortName": "ZAMSUT",
    "type": "State University",
    "ownership": "State",
    "state": "Zamfara",
    "city": "Talata Mafara",
    "geopoliticalZone": "North West",
    "establishedYear": 2018,
    "motto": "Knowledge for Self-Reliance",
    "logoColor": "#004d40",
    "gradingSystem": "5.0",
    "websiteUrl": "https://zamsut.edu.ng",
    "portalUrl": "https://portal.zamsut.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/state-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "State university located in Talata Mafara, offering degrees in health sciences, computing, natural sciences, and humanities.",
    "faculties": [
      "Faculty of Health Sciences",
      "Faculty of Science",
      "Faculty of Social and Management Sciences",
      "Faculty of Arts and Education"
    ]
  },
  {
    "id": "fedpoly_kaura_namoda",
    "name": "Federal Polytechnic, Kaura Namoda",
    "shortName": "FEDPONAM",
    "type": "Federal Polytechnic",
    "ownership": "Federal",
    "state": "Zamfara",
    "city": "Kaura Namoda",
    "geopoliticalZone": "North West",
    "establishedYear": 1977,
    "motto": "Technology for Self-Reliance",
    "logoColor": "#b71c1c",
    "gradingSystem": "4.0",
    "websiteUrl": "https://fedpodam.edu.ng",
    "portalUrl": "https://portal.fedponam.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/polytechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Premier federal polytechnic in Zamfara State delivering accredited engineering, science technology, and business diplomas.",
    "faculties": [
      "School of Engineering Technology",
      "School of Applied Sciences and Technology",
      "School of Business and Management Studies",
      "School of Environmental Studies"
    ]
  },
  {
    "id": "fce_technical_gusau",
    "name": "Federal College of Education (Technical), Gusau",
    "shortName": "FCET Gusau",
    "type": "Federal College of Education",
    "ownership": "Federal",
    "state": "Zamfara",
    "city": "Gusau",
    "geopoliticalZone": "North West",
    "establishedYear": 1989,
    "motto": "Technical Skill for Better Living",
    "logoColor": "#2e7d32",
    "gradingSystem": "4.0",
    "websiteUrl": "https://fcetgusau.edu.ng",
    "portalUrl": "https://portal.fcetgusau.edu.ng",
    "regulator": "NCCE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://ncceonline.edu.ng",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Federal technical teacher college delivering NCE and university degree affiliated courses in technical and vocational education for women.",
    "faculties": [
      "School of Technical Education",
      "School of Vocational Education",
      "School of Science Education",
      "School of Business Education",
      "School of Education"
    ]
  }
]
