# SOUTH SOUTH ZONE: Akwa Ibom, Bayelsa, Cross River, Delta, Edo, Rivers

DATA = [
  # ----------------------------------------------------
  # AKWA IBOM STATE
  # ----------------------------------------------------
  {
    "id": "uniuyo",
    "name": "University of Uyo",
    "shortName": "UNIUYO",
    "type": "Federal University",
    "ownership": "Federal",
    "state": "Akwa Ibom",
    "city": "Uyo",
    "geopoliticalZone": "South South",
    "establishedYear": 1991,
    "motto": "Unity, Learning and Service",
    "logoColor": "#004d40",
    "gradingSystem": "5.0",
    "websiteUrl": "https://uniuyo.edu.ng",
    "portalUrl": "https://uniuyo.edu.ng/eportals",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/federal-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Premier federal university in Akwa Ibom State, acclaimed for engineering, medical sciences, pharmacy, law, arts, and agriculture.",
    "faculties": [
      "Faculty of Engineering",
      "Faculty of Science",
      "Faculty of Clinical Sciences",
      "Faculty of Pharmacy",
      "Faculty of Law",
      "Faculty of Management Sciences",
      "Faculty of Social Sciences",
      "Faculty of Agriculture",
      "Faculty of Environmental Studies",
      "Faculty of Arts",
      "Faculty of Education"
    ]
  },
  {
    "id": "aksu",
    "name": "Akwa Ibom State University",
    "shortName": "AKSU",
    "type": "State University",
    "ownership": "State",
    "state": "Akwa Ibom",
    "city": "Ikot Akpaden, Mkpat Enin",
    "geopoliticalZone": "South South",
    "establishedYear": 2010,
    "motto": "Excellence in Science and Technology",
    "logoColor": "#0d47a1",
    "gradingSystem": "5.0",
    "websiteUrl": "https://aksu.edu.ng",
    "portalUrl": "https://portal.aksu.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/state-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Multi-campus state university with campuses at Ikot Akpaden (Main Campus) and Obio Akpa.",
    "faculties": [
      "Faculty of Engineering",
      "Faculty of Physical Sciences",
      "Faculty of Biological Sciences",
      "Faculty of Management Sciences",
      "Faculty of Agriculture",
      "Faculty of Arts",
      "Faculty of Social Sciences",
      "Faculty of Education"
    ]
  },
  {
    "id": "topfaith_uni",
    "name": "Topfaith University, Mkpatak",
    "shortName": "Topfaith",
    "type": "Private University",
    "ownership": "Private",
    "state": "Akwa Ibom",
    "city": "Mkpatak, Essien Udim",
    "geopoliticalZone": "South South",
    "establishedYear": 2021,
    "motto": "Discover, Develop, Deploy",
    "logoColor": "#6a1b9a",
    "gradingSystem": "5.0",
    "websiteUrl": "https://topfaith.edu.ng",
    "portalUrl": "https://portal.topfaith.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Accredited",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/private-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Modern private university in Akwa Ibom recognized for cutting-edge computing, engineering, law, and management curricula.",
    "faculties": [
      "Faculty of Computing and Applied Sciences",
      "Faculty of Engineering",
      "Faculty of Law",
      "Faculty of Management and Social Sciences"
    ]
  },
  {
    "id": "fedpoly_ukana",
    "name": "Federal Polytechnic, Ukana",
    "shortName": "FEDPOUK",
    "type": "Federal Polytechnic",
    "ownership": "Federal",
    "state": "Akwa Ibom",
    "city": "Ukana, Essien Udim",
    "geopoliticalZone": "South South",
    "establishedYear": 2014,
    "motto": "Technological Excellence for Humanity",
    "logoColor": "#b71c1c",
    "gradingSystem": "4.0",
    "websiteUrl": "https://fedpolyukana.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Accredited",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/polytechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Federal technical polytechnic delivering accredited ND programmes in computer science, statistics, and electrical engineering.",
    "faculties": [
      "School of Applied Sciences",
      "School of Engineering Technology",
      "School of Management Studies"
    ]
  },
  {
    "id": "akwa_ibom_poly",
    "name": "Akwa Ibom State Polytechnic, Ikot Osurua",
    "shortName": "AKWAPOLY",
    "type": "State Polytechnic",
    "ownership": "State",
    "state": "Akwa Ibom",
    "city": "Ikot Osurua, Ikot Ekpene",
    "geopoliticalZone": "South South",
    "establishedYear": 1991,
    "motto": "Technology for Development",
    "logoColor": "#2e7d32",
    "gradingSystem": "4.0",
    "websiteUrl": "https://akwaibompoly.edu.ng",
    "portalUrl": "https://portal.akwaibompoly.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/polytechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Premier state polytechnic located in Ikot Ekpene, producing technical leaders in engineering, sciences, and communication.",
    "faculties": [
      "School of Applied Sciences",
      "School of Engineering",
      "School of Business Studies",
      "School of Environmental Studies",
      "School of Communication Arts"
    ]
  },
  {
    "id": "man_oron",
    "name": "Maritime Academy of Nigeria",
    "shortName": "MAN Oron",
    "type": "Monotechnic / Specialized Institution",
    "ownership": "Federal",
    "state": "Akwa Ibom",
    "city": "Oron",
    "geopoliticalZone": "South South",
    "establishedYear": 1977,
    "motto": "Excellence in Maritime Training",
    "logoColor": "#01579b",
    "gradingSystem": "4.0",
    "websiteUrl": "https://maritimeacademy.gov.ng",
    "portalUrl": "https://application.maritimeacademy.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/monotechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Apex federal maritime training institution providing specialized nautical science, marine engineering, and maritime transport programmes.",
    "faculties": [
      "School of Nautical Studies",
      "School of Marine Engineering",
      "School of Maritime Transport & Business Studies"
    ]
  },
  {
    "id": "fce_ididep",
    "name": "Federal College of Education, Ididep",
    "shortName": "FCE Ididep",
    "type": "Federal College of Education",
    "ownership": "Federal",
    "state": "Akwa Ibom",
    "city": "Ididep, Ibiono Ibom",
    "geopoliticalZone": "South South",
    "establishedYear": 2020,
    "motto": "Excellence and Integrity in Teacher Education",
    "logoColor": "#00695c",
    "gradingSystem": "4.0",
    "websiteUrl": "https://fceididep.edu.ng",
    "regulator": "NCCE",
    "accreditationStatus": "Accredited",
    "verificationStatus": "Verified",
    "sourceUrl": "https://ncceonline.edu.ng",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Modern federal teacher training institution offering NCE programmes in foundational teaching, vocational disciplines, and STEM.",
    "faculties": [
      "School of Sciences",
      "School of Arts and Social Sciences",
      "School of Vocational and Technical Education",
      "School of Education"
    ]
  },

  # ----------------------------------------------------
  # BAYELSA STATE
  # ----------------------------------------------------
  {
    "id": "fuotuoke",
    "name": "Federal University, Otuoke",
    "shortName": "FUOTUOKE",
    "type": "Federal University",
    "ownership": "Federal",
    "state": "Bayelsa",
    "city": "Otuoke, Ogbia",
    "geopoliticalZone": "South South",
    "establishedYear": 2011,
    "motto": "Building Generations for Greatness",
    "logoColor": "#1565c0",
    "gradingSystem": "5.0",
    "websiteUrl": "https://fuotuoke.edu.ng",
    "portalUrl": "https://portal.fuotuoke.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/federal-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Federal university located in the Niger Delta heartland, delivering strong programmes in engineering, sciences, humanities, and management.",
    "faculties": [
      "Faculty of Engineering",
      "Faculty of Science",
      "Faculty of Management Sciences",
      "Faculty of Social Sciences",
      "Faculty of Humanities",
      "Faculty of Education"
    ]
  },
  {
    "id": "ndu_wilberforce",
    "name": "Niger Delta University, Wilberforce Island",
    "shortName": "NDU",
    "type": "State University",
    "ownership": "State",
    "state": "Bayelsa",
    "city": "Wilberforce Island, Amassoma",
    "geopoliticalZone": "South South",
    "establishedYear": 2000,
    "motto": "Creativity, Excellence and Service",
    "logoColor": "#004d40",
    "gradingSystem": "5.0",
    "websiteUrl": "https://ndu.edu.ng",
    "portalUrl": "https://portal.ndu.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/state-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Premier state university in Bayelsa, renowned for engineering, medical sciences, pharmacy, law, and environmental management.",
    "faculties": [
      "Faculty of Engineering",
      "College of Health Sciences",
      "Faculty of Pharmacy",
      "Faculty of Law",
      "Faculty of Science",
      "Faculty of Management Sciences",
      "Faculty of Social Sciences",
      "Faculty of Agricultural Technology",
      "Faculty of Arts",
      "Faculty of Environmental Sciences",
      "Faculty of Education"
    ]
  },
  {
    "id": "uam_bayelsa",
    "name": "University of Africa, Toru-Orua",
    "shortName": "UAT",
    "type": "State University",
    "ownership": "State",
    "state": "Bayelsa",
    "city": "Toru-Orua, Sagbama",
    "geopoliticalZone": "South South",
    "establishedYear": 2016,
    "motto": "Knowledge for Sustainable Development",
    "logoColor": "#b71c1c",
    "gradingSystem": "5.0",
    "websiteUrl": "https://uat.edu.ng",
    "portalUrl": "https://portal.uat.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/state-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Innovative public-private partnership state university offering internationally affiliated programmes.",
    "faculties": [
      "Faculty of Basic and Applied Sciences",
      "Faculty of Social and Management Sciences",
      "Faculty of Arts and Education",
      "Faculty of Agriculture"
    ]
  },
  {
    "id": "by_poly_ekowe",
    "name": "Federal Polytechnic, Ekowe",
    "shortName": "FedPolyEkowe",
    "type": "Federal Polytechnic",
    "ownership": "Federal",
    "state": "Bayelsa",
    "city": "Ekowe, Southern Ijaw",
    "geopoliticalZone": "South South",
    "establishedYear": 2007,
    "motto": "Oil, Gas and Technological Excellence",
    "logoColor": "#e65100",
    "gradingSystem": "4.0",
    "websiteUrl": "https://federalpolyekowe.edu.ng",
    "portalUrl": "https://portal.federalpolyekowe.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/polytechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Specialized federal polytechnic in oil, gas, petroleum engineering, and environmental technologies.",
    "faculties": [
      "School of Oil and Gas Technology",
      "School of Engineering Technology",
      "School of Applied Sciences",
      "School of Management Sciences"
    ]
  },
  {
    "id": "bayelsa_poly_alepo",
    "name": "Bayelsa State Polytechnic, Aleibiri",
    "shortName": "BYSPOLY",
    "type": "State Polytechnic",
    "ownership": "State",
    "state": "Bayelsa",
    "city": "Aleibiri, Ekeremor",
    "geopoliticalZone": "South South",
    "establishedYear": 2014,
    "motto": "Skills and Technological Innovation",
    "logoColor": "#2e7d32",
    "gradingSystem": "4.0",
    "websiteUrl": "https://bayelsapoly.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Accredited",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/polytechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "State polytechnic producing skilled technical workers in engineering, computing, and commerce.",
    "faculties": [
      "School of Engineering Technology",
      "School of Applied Sciences",
      "School of Commerce and Management Studies"
    ]
  },
  {
    "id": "bayelsa_nursing_tombia",
    "name": "Bayelsa State College of Health Technology, Otuogidi",
    "shortName": "BYCOTECH",
    "type": "College of Health Sciences and Technology",
    "ownership": "State",
    "state": "Bayelsa",
    "city": "Otuogidi, Ogbia",
    "geopoliticalZone": "South South",
    "establishedYear": 2004,
    "motto": "Health for all through Technology",
    "logoColor": "#00838f",
    "gradingSystem": "4.0",
    "websiteUrl": "https://bycotech.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Accredited",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "State health sciences college training community health practitioners, medical lab technicians, and pharmacy technicians.",
    "faculties": [
      "Department of Community Health Sciences",
      "Department of Medical Laboratory",
      "Department of Pharmacy Technician",
      "Department of Environmental Health"
    ]
  },

  # ----------------------------------------------------
  # CROSS RIVER STATE
  # ----------------------------------------------------
  {
    "id": "unical",
    "name": "University of Calabar",
    "shortName": "UNICAL",
    "type": "Federal University",
    "ownership": "Federal",
    "state": "Cross River",
    "city": "Calabar",
    "geopoliticalZone": "South South",
    "establishedYear": 1975,
    "motto": "Knowledge for Service",
    "logoColor": "#1565c0",
    "gradingSystem": "5.0",
    "websiteUrl": "https://unical.edu.ng",
    "portalUrl": "https://myunical.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/federal-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Historic federal university acclaimed for medicine, law, medical laboratory science, oceanography, and management.",
    "faculties": [
      "College of Medical Sciences",
      "Faculty of Allied Medical Sciences",
      "Faculty of Law",
      "Faculty of Physical Sciences",
      "Faculty of Biological Sciences",
      "Faculty of Management Sciences",
      "Faculty of Social Sciences",
      "Faculty of Oceanography",
      "Faculty of Agriculture, Forestry and Wildlife Resources",
      "Faculty of Arts",
      "Faculty of Education",
      "Faculty of Engineering"
    ]
  },
  {
    "id": "unicross",
    "name": "University of Cross River State",
    "shortName": "UNICROSS",
    "type": "State University",
    "ownership": "State",
    "state": "Cross River",
    "city": "Calabar",
    "geopoliticalZone": "South South",
    "establishedYear": 2002,
    "motto": "Technology for Development",
    "logoColor": "#b71c1c",
    "gradingSystem": "5.0",
    "websiteUrl": "https://unicross.edu.ng",
    "portalUrl": "https://portal.unicross.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/state-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Multi-campus state university with campuses at Calabar, Ogoja, Okuku, and Obubra.",
    "faculties": [
      "Faculty of Engineering",
      "Faculty of Physical Sciences",
      "Faculty of Biological Sciences",
      "Faculty of Management Sciences",
      "Faculty of Environmental Sciences",
      "Faculty of Agriculture and Forestry",
      "Faculty of Communication Technology",
      "Faculty of Education"
    ]
  },
  {
    "id": "havilla_uni",
    "name": "Havilla University, Nde-Ikom",
    "shortName": "HUNI",
    "type": "Private University",
    "ownership": "Private",
    "state": "Cross River",
    "city": "Nde-Ikom",
    "geopoliticalZone": "South South",
    "establishedYear": 2021,
    "motto": "Wisdom, Integrity and Service",
    "logoColor": "#004d40",
    "gradingSystem": "5.0",
    "websiteUrl": "https://havilla.edu.ng",
    "portalUrl": "https://portal.havilla.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Accredited",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/private-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Private university in central Cross River delivering high quality computing, sciences, and management courses.",
    "faculties": [
      "Faculty of Computing and Applied Sciences",
      "Faculty of Management and Social Sciences"
    ]
  },
  {
    "id": "fce_obudu",
    "name": "Federal College of Education, Obudu",
    "shortName": "FCE Obudu",
    "type": "Federal College of Education",
    "ownership": "Federal",
    "state": "Cross River",
    "city": "Obudu",
    "geopoliticalZone": "South South",
    "establishedYear": 1982,
    "motto": "Knowledge for Self-Reliance",
    "logoColor": "#2e7d32",
    "gradingSystem": "4.0",
    "websiteUrl": "https://fceobudu.edu.ng",
    "portalUrl": "https://portal.fceobudu.edu.ng",
    "regulator": "NCCE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://ncceonline.edu.ng",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Premier federal teacher training institution in Cross River State offering NCE and undergraduate degree programmes.",
    "faculties": [
      "School of Sciences",
      "School of Vocational and Technical Education",
      "School of Arts and Social Sciences",
      "School of Languages",
      "School of Education"
    ]
  },
  {
    "id": "cr_health_mary_slessor",
    "name": "Cross River State College of Nursing and Midwifery Sciences, Calabar",
    "shortName": "CONMS Calabar",
    "type": "College of Nursing Sciences",
    "ownership": "State",
    "state": "Cross River",
    "city": "Calabar",
    "geopoliticalZone": "South South",
    "establishedYear": 1974,
    "motto": "Care and Skill for Humanity",
    "logoColor": "#00838f",
    "gradingSystem": "4.0",
    "websiteUrl": "https://conmscalabar.edu.ng",
    "regulator": "NMCN",
    "accreditationStatus": "Accredited",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nmcn.gov.ng",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "State college training professional registered nurses, midwives, and public health nursing officers.",
    "faculties": [
      "Department of Nursing",
      "Department of Midwifery",
      "Department of Public Health Nursing"
    ]
  },

  # ----------------------------------------------------
  # DELTA STATE
  # ----------------------------------------------------
  {
    "id": "fupre",
    "name": "Federal University of Petroleum Resources, Effurun",
    "shortName": "FUPRE",
    "type": "Federal University",
    "ownership": "Federal",
    "state": "Delta",
    "city": "Effurun, Warri",
    "geopoliticalZone": "South South",
    "establishedYear": 2007,
    "motto": "Excellence in Petroleum and Energy",
    "logoColor": "#b71c1c",
    "gradingSystem": "5.0",
    "websiteUrl": "https://fupre.edu.ng",
    "portalUrl": "https://portal.fupre.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/federal-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Africa's first specialized university of petroleum resources, delivering world-class petroleum, gas, marine, and chemical engineering education.",
    "faculties": [
      "College of Technology",
      "College of Science",
      "College of Petroleum and Energy Studies"
    ]
  },
  {
    "id": "delsu",
    "name": "Delta State University, Abraka",
    "shortName": "DELSU",
    "type": "State University",
    "ownership": "State",
    "state": "Delta",
    "city": "Abraka",
    "geopoliticalZone": "South South",
    "establishedYear": 1992,
    "motto": "Knowledge, Character and Service",
    "logoColor": "#1565c0",
    "gradingSystem": "5.0",
    "websiteUrl": "https://delsu.edu.ng",
    "portalUrl": "https://portal.delsu.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/state-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Multi-campus comprehensive state university in Delta State with prominent faculties of clinical medicine, law, pharmacy, and sciences.",
    "faculties": [
      "College of Health Sciences",
      "Faculty of Pharmacy",
      "Faculty of Law",
      "Faculty of Science",
      "Faculty of Management Sciences",
      "Faculty of Social Sciences",
      "Faculty of Agriculture",
      "Faculty of Arts",
      "Faculty of Education"
    ]
  },
  {
    "id": "unidel_agbor",
    "name": "University of Delta, Agbor",
    "shortName": "UNIDEL",
    "type": "State University",
    "ownership": "State",
    "state": "Delta",
    "city": "Agbor",
    "geopoliticalZone": "South South",
    "establishedYear": 2021,
    "motto": "Knowledge for Excellence and Innovation",
    "logoColor": "#004d40",
    "gradingSystem": "5.0",
    "websiteUrl": "https://unidel.edu.ng",
    "portalUrl": "https://portal.unidel.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/state-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "State university upgraded from the former College of Education Agbor, offering diverse science, computing, computing, arts, and education degrees.",
    "faculties": [
      "Faculty of Computing",
      "Faculty of Science",
      "Faculty of Management and Social Sciences",
      "Faculty of Arts",
      "Faculty of Education"
    ]
  },
  {
    "id": "dsust_ozoro",
    "name": "Delta State University of Science and Technology, Ozoro",
    "shortName": "DSUST",
    "type": "State University",
    "ownership": "State",
    "state": "Delta",
    "city": "Ozoro, Isoko North",
    "geopoliticalZone": "South South",
    "establishedYear": 2021,
    "motto": "Technology for Wealth and Progress",
    "logoColor": "#d84315",
    "gradingSystem": "5.0",
    "websiteUrl": "https://dsust.edu.ng",
    "portalUrl": "https://portal.dsust.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/state-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Specialized state university of science and technology established in Ozoro.",
    "faculties": [
      "Faculty of Engineering",
      "Faculty of Science",
      "Faculty of Environmental Science",
      "Faculty of Agriculture",
      "Faculty of Administration and Management"
    ]
  },
  {
    "id": "western_delta_uni",
    "name": "Western Delta University, Oghara",
    "shortName": "WDU",
    "type": "Private University",
    "ownership": "Private",
    "state": "Delta",
    "city": "Oghara, Ethiope West",
    "geopoliticalZone": "South South",
    "establishedYear": 2007,
    "motto": "Knowledge, Culture and Service",
    "logoColor": "#303f9f",
    "gradingSystem": "5.0",
    "websiteUrl": "https://wdu.edu.ng",
    "portalUrl": "https://portal.wdu.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/private-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Private university in Oghara recognized for computing, law, natural sciences, and social sciences.",
    "faculties": [
      "College of Natural and Applied Sciences",
      "College of Social and Management Sciences",
      "College of Law"
    ]
  },
  {
    "id": "fedpoly_ogwashi_uku",
    "name": "Delta State Polytechnic, Ogwashi-Uku",
    "shortName": "DSPG",
    "type": "State Polytechnic",
    "ownership": "State",
    "state": "Delta",
    "city": "Ogwashi-Uku",
    "geopoliticalZone": "South South",
    "establishedYear": 2002,
    "motto": "Knowledge for Self Reliance",
    "logoColor": "#00796b",
    "gradingSystem": "4.0",
    "websiteUrl": "https://dspg.edu.ng",
    "portalUrl": "https://portal.dspg.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/polytechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "State polytechnic acclaimed for fashion design, art & industrial design, mechanical engineering, and computing.",
    "faculties": [
      "School of Engineering",
      "School of Applied Sciences",
      "School of Business Studies",
      "School of Art and Design"
    ]
  },
  {
    "id": "pti_effurun",
    "name": "Petroleum Training Institute, Effurun",
    "shortName": "PTI",
    "type": "Monotechnic / Specialized Institution",
    "ownership": "Federal",
    "state": "Delta",
    "city": "Effurun, Warri",
    "geopoliticalZone": "South South",
    "establishedYear": 1972,
    "motto": "Skills for Petroleum and Energy Development",
    "logoColor": "#b71c1c",
    "gradingSystem": "4.0",
    "websiteUrl": "https://pti.edu.ng",
    "portalUrl": "https://portal.pti.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/monotechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Nigeria's flagship federal petroleum institute training technicians, drillers, and engineers for the oil and gas industry.",
    "faculties": [
      "School of Petroleum Engineering and Geosciences",
      "School of Industrial Technology",
      "School of Applied Sciences",
      "School of General and Management Studies"
    ]
  },
  {
    "id": "fce_technical_asaba",
    "name": "Federal College of Education (Technical), Asaba",
    "shortName": "FCET Asaba",
    "type": "Federal College of Education",
    "ownership": "Federal",
    "state": "Delta",
    "city": "Asaba",
    "geopoliticalZone": "South South",
    "establishedYear": 1987,
    "motto": "Technological Excellence in Teacher Education",
    "logoColor": "#2e7d32",
    "gradingSystem": "4.0",
    "websiteUrl": "https://fcetasaba.edu.ng",
    "portalUrl": "https://portal.fcetasaba.edu.ng",
    "regulator": "NCCE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://ncceonline.edu.ng",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Federal technical teacher education institution offering NCE and university degree affiliations in technical and vocational fields.",
    "faculties": [
      "School of Technical Education",
      "School of Vocational Education",
      "School of Science Education",
      "School of Business Education",
      "School of Education"
    ]
  },

  # ----------------------------------------------------
  # EDO STATE
  # ----------------------------------------------------
  {
    "id": "uniben",
    "name": "University of Benin",
    "shortName": "UNIBEN",
    "type": "Federal University",
    "ownership": "Federal",
    "state": "Edo",
    "city": "Benin City",
    "geopoliticalZone": "South South",
    "establishedYear": 1970,
    "motto": "Knowledge for Service",
    "logoColor": "#6a1b9a",
    "gradingSystem": "5.0",
    "websiteUrl": "https://uniben.edu",
    "portalUrl": "https://waeup.uniben.edu",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/federal-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "One of Nigeria's first-generation first-class federal universities, famed for medicine, pharmacy, law, engineering, and physical sciences.",
    "faculties": [
      "College of Medical Sciences",
      "Faculty of Pharmacy",
      "Faculty of Engineering",
      "Faculty of Physical Sciences",
      "Faculty of Life Sciences",
      "Faculty of Law",
      "Faculty of Management Sciences",
      "Faculty of Social Sciences",
      "Faculty of Arts",
      "Faculty of Environmental Sciences",
      "Faculty of Agriculture",
      "Faculty of Education",
      "Faculty of Veterinary Medicine",
      "Faculty of Dentistry"
    ]
  },
  {
    "id": "aaue_ekpoma",
    "name": "Ambrose Alli University, Ekpoma",
    "shortName": "AAU",
    "type": "State University",
    "ownership": "State",
    "state": "Edo",
    "city": "Ekpoma",
    "geopoliticalZone": "South South",
    "establishedYear": 1981,
    "motto": "Knowledge for Advancement",
    "logoColor": "#1565c0",
    "gradingSystem": "5.0",
    "websiteUrl": "https://aauekpoma.edu.ng",
    "portalUrl": "https://aaue.waeup.org",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/state-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Historic state university founded by Professor Ambrose Folorunsho Alli, renowned for law, medicine, engineering, and humanities.",
    "faculties": [
      "College of Medicine",
      "Faculty of Law",
      "Faculty of Engineering and Technology",
      "Faculty of Physical Sciences",
      "Faculty of Life Sciences",
      "Faculty of Management Sciences",
      "Faculty of Social Sciences",
      "Faculty of Arts",
      "Faculty of Agriculture",
      "Faculty of Environmental Studies",
      "Faculty of Education"
    ]
  },
  {
    "id": "edo_state_uni_uzairue",
    "name": "Edo State University, Uzairue",
    "shortName": "EDSU",
    "type": "State University",
    "ownership": "State",
    "state": "Edo",
    "city": "Uzairue, Iyamho",
    "geopoliticalZone": "South South",
    "establishedYear": 2016,
    "motto": "Excellence in Quality Teaching, Research and Service",
    "logoColor": "#004d40",
    "gradingSystem": "5.0",
    "websiteUrl": "https://edouniversity.edu.ng",
    "portalUrl": "https://portal.edouniversity.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/state-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "State-of-the-art public university modeled after world-class institutions with digital anatomical tables and smart classrooms.",
    "faculties": [
      "College of Medical Sciences",
      "Faculty of Engineering",
      "Faculty of Law",
      "Faculty of Science",
      "Faculty of Arts, Management and Social Sciences",
      "Faculty of Applied Health Sciences"
    ]
  },
  {
    "id": "igbinedion_uni",
    "name": "Igbinedion University, Okada",
    "shortName": "IUO",
    "type": "Private University",
    "ownership": "Private",
    "state": "Edo",
    "city": "Okada",
    "geopoliticalZone": "South South",
    "establishedYear": 1999,
    "motto": "Knowledge for Excellence",
    "logoColor": "#b71c1c",
    "gradingSystem": "5.0",
    "websiteUrl": "https://iuokada.edu.ng",
    "portalUrl": "https://portal.iuokada.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/private-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Nigeria's first licensed private university, pioneered by Sir Gabriel Igbinedion, famed for medicine, pharmacy, law, and engineering.",
    "faculties": [
      "College of Health Sciences",
      "Dora Akunyili College of Pharmacy",
      "Faculty of Law",
      "Faculty of Engineering",
      "Faculty of Natural and Applied Sciences",
      "Faculty of Business and Management Studies",
      "Faculty of Arts and Social Sciences"
    ]
  },
  {
    "id": "benson_idahosa_uni",
    "name": "Benson Idahosa University, Benin City",
    "shortName": "BIU",
    "type": "Private University",
    "ownership": "Private",
    "state": "Edo",
    "city": "Benin City",
    "geopoliticalZone": "South South",
    "establishedYear": 2002,
    "motto": "Academic Excellence with Godliness",
    "logoColor": "#0d47a1",
    "gradingSystem": "5.0",
    "websiteUrl": "https://biu.edu.ng",
    "portalUrl": "https://portal.biu.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/private-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Private Christian university founded by Archbishop Benson Idahosa, recognized for law, agriculture, engineering, and computing.",
    "faculties": [
      "Faculty of Law",
      "Faculty of Engineering",
      "Faculty of Science",
      "Faculty of Social and Management Sciences",
      "Faculty of Agriculture and Agricultural Technology",
      "Faculty of Arts and Education"
    ]
  },
  {
    "id": "auchi_poly",
    "name": "Auchi Polytechnic, Auchi",
    "shortName": "AUCHIPOLY",
    "type": "Federal Polytechnic",
    "ownership": "Federal",
    "state": "Edo",
    "city": "Auchi",
    "geopoliticalZone": "South South",
    "establishedYear": 1963,
    "motto": "Hands and Brain for Self Reliance",
    "logoColor": "#e65100",
    "gradingSystem": "4.0",
    "websiteUrl": "https://auchipoly.edu.ng",
    "portalUrl": "https://portal.auchipoly.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/polytechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "One of Nigeria's foremost and oldest polytechnics, world-renowned for art & industrial design, engineering, and accountancy.",
    "faculties": [
      "School of Engineering Technology",
      "School of Applied Sciences",
      "School of Business Studies",
      "School of Environmental Studies",
      "School of Art and Industrial Design",
      "School of Information and Communication Technology"
    ]
  },
  {
    "id": "edo_state_poly_usen",
    "name": "Edo State Polytechnic, Usen",
    "shortName": "EDOPOLY",
    "type": "State Polytechnic",
    "ownership": "State",
    "state": "Edo",
    "city": "Usen, Ovia South-West",
    "geopoliticalZone": "South South",
    "establishedYear": 2002,
    "motto": "Technological Excellence for Development",
    "logoColor": "#2e7d32",
    "gradingSystem": "4.0",
    "websiteUrl": "https://edopoly.edu.ng",
    "portalUrl": "https://portal.edopoly.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/polytechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "State polytechnic delivering accredited diplomas in engineering, sciences, computer science, and environmental studies.",
    "faculties": [
      "School of Engineering",
      "School of Applied Sciences",
      "School of Business Studies",
      "School of Environmental Studies"
    ]
  },
  {
    "id": "fce_technical_eha_ebelle",
    "name": "Federal College of Education (Technical), Ekiadolor",
    "shortName": "FCET Ekiadolor",
    "type": "Federal College of Education",
    "ownership": "Federal",
    "state": "Edo",
    "city": "Ekiadolor, Ovia North-East",
    "geopoliticalZone": "South South",
    "establishedYear": 2020,
    "motto": "Excellence in Technical Teacher Education",
    "logoColor": "#00796b",
    "gradingSystem": "4.0",
    "websiteUrl": "https://fcetekiadolor.edu.ng",
    "regulator": "NCCE",
    "accreditationStatus": "Accredited",
    "verificationStatus": "Verified",
    "sourceUrl": "https://ncceonline.edu.ng",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Federal technical teacher college delivering high-level pedagogical training in technical disciplines and vocational arts.",
    "faculties": [
      "School of Technical Education",
      "School of Vocational Education",
      "School of Science Education",
      "School of Education"
    ]
  },

  # ----------------------------------------------------
  # RIVERS STATE
  # ----------------------------------------------------
  {
    "id": "uniport",
    "name": "University of Port Harcourt",
    "shortName": "UNIPORT",
    "type": "Federal University",
    "ownership": "Federal",
    "state": "Rivers",
    "city": "Choba, Port Harcourt",
    "geopoliticalZone": "South South",
    "establishedYear": 1975,
    "motto": "For Enlightenment and Self-Reliance",
    "logoColor": "#0d47a1",
    "gradingSystem": "5.0",
    "websiteUrl": "https://uniport.edu.ng",
    "portalUrl": "https://ecampus.uniport.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/federal-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Premier federal university in the oil capital of Nigeria, acclaimed for petroleum engineering, medical sciences, pharmacy, and humanities.",
    "faculties": [
      "College of Health Sciences",
      "Faculty of Pharmaceutical Sciences",
      "Faculty of Engineering",
      "Faculty of Science",
      "Faculty of Law",
      "Faculty of Management Sciences",
      "Faculty of Social Sciences",
      "Faculty of Humanities",
      "Faculty of Agriculture",
      "Faculty of Education",
      "Faculty of Dentistry"
    ]
  },
  {
    "id": "rsu_nkpolu",
    "name": "Rivers State University, Port Harcourt",
    "shortName": "RSU",
    "type": "State University",
    "ownership": "State",
    "state": "Rivers",
    "city": "Nkpolu-Oroworukwo, Port Harcourt",
    "geopoliticalZone": "South South",
    "establishedYear": 1979,
    "motto": "Excellence and Creativity",
    "logoColor": "#1b5e20",
    "gradingSystem": "5.0",
    "websiteUrl": "https://rsu.edu.ng",
    "portalUrl": "https://ecampus.rsu.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/state-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "First technological state university in Nigeria (formerly UST), renowned for marine engineering, law, medicine, environmental sciences, and agriculture.",
    "faculties": [
      "College of Medical Sciences",
      "Faculty of Engineering",
      "Faculty of Law",
      "Faculty of Science",
      "Faculty of Management Sciences",
      "Faculty of Social Sciences",
      "Faculty of Environmental Sciences",
      "Faculty of Agriculture",
      "Faculty of Humanities",
      "Faculty of Education"
    ]
  },
  {
    "id": "iaue_rumuolumeni",
    "name": "Ignatius Ajuru University of Education, Port Harcourt",
    "shortName": "IAUE",
    "type": "State University",
    "ownership": "State",
    "state": "Rivers",
    "city": "Rumuolumeni, Port Harcourt",
    "geopoliticalZone": "South South",
    "establishedYear": 1971,
    "motto": "Excellence in Teacher Education",
    "logoColor": "#b71c1c",
    "gradingSystem": "5.0",
    "websiteUrl": "https://iaue.edu.ng",
    "portalUrl": "https://iaue.edu.ng/portal",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/state-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Specialized state university producing certified educators across STEM, humanities, and vocational education.",
    "faculties": [
      "Faculty of Natural and Applied Sciences",
      "Faculty of Vocational and Technical Education",
      "Faculty of Management Sciences",
      "Faculty of Social Sciences",
      "Faculty of Humanities",
      "Faculty of Education"
    ]
  },
  {
    "id": "pamo_uni",
    "name": "PAMO University of Medical Sciences, Port Harcourt",
    "shortName": "PUMS",
    "type": "Private University",
    "ownership": "Private",
    "state": "Rivers",
    "city": "Iriebe, Port Harcourt",
    "geopoliticalZone": "South South",
    "establishedYear": 2017,
    "motto": "Excellence in Medical Practice",
    "logoColor": "#004d40",
    "gradingSystem": "5.0",
    "websiteUrl": "https://pums.edu.ng",
    "portalUrl": "https://portal.pums.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/private-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Nigeria's first private university of medical sciences, established by Dr. Peter Odili, excelling in medicine, nursing, and radiography.",
    "faculties": [
      "Faculty of Clinical Sciences",
      "Faculty of Basic Medical Sciences",
      "Faculty of Allied Health Sciences",
      "Faculty of Pharmacy"
    ]
  },
  {
    "id": "captain_elechi_amadi_poly",
    "name": "Captain Elechi Amadi Polytechnic, Rumuola",
    "shortName": "CEAPOLY",
    "type": "State Polytechnic",
    "ownership": "State",
    "state": "Rivers",
    "city": "Rumuola, Port Harcourt",
    "geopoliticalZone": "South South",
    "establishedYear": 1987,
    "motto": "Technology for Economic Emancipation",
    "logoColor": "#e65100",
    "gradingSystem": "4.0",
    "websiteUrl": "https://portharcourtpoly.edu.ng",
    "portalUrl": "https://ecampus.portharcourtpoly.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/polytechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Formerly Port Harcourt Polytechnic, offering accredited National Diploma and Higher National Diploma diplomas in engineering, business, and ICT.",
    "faculties": [
      "School of Engineering Technology",
      "School of Applied Sciences",
      "School of Business Studies",
      "School of Financial Studies",
      "School of Environmental Technology"
    ]
  },
  {
    "id": "fedpoly_oil_gas_bonny",
    "name": "Federal Polytechnic of Oil and Gas, Bonny",
    "shortName": "FPOG Bonny",
    "type": "Federal Polytechnic",
    "ownership": "Federal",
    "state": "Rivers",
    "city": "Bonny Island",
    "geopoliticalZone": "South South",
    "establishedYear": 2014,
    "motto": "Powering Technological Skills for Energy",
    "logoColor": "#01579b",
    "gradingSystem": "4.0",
    "websiteUrl": "https://fedpolybonny.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Accredited",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/polytechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Specialized federal polytechnic located on Bonny Island dedicated to oil, gas, petroleum processing, and marine engineering technology.",
    "faculties": [
      "School of Engineering Technology",
      "School of Applied Sciences",
      "School of Management Studies"
    ]
  },
  {
    "id": "rivers_health_tech",
    "name": "Rivers State College of Health Science and Management Technology",
    "shortName": "RSCHST",
    "type": "College of Health Sciences and Technology",
    "ownership": "State",
    "state": "Rivers",
    "city": "Oro-Owo, Rumueme, Port Harcourt",
    "geopoliticalZone": "South South",
    "establishedYear": 1974,
    "motto": "Health is Wealth",
    "logoColor": "#00838f",
    "gradingSystem": "4.0",
    "websiteUrl": "https://rschst.edu.ng",
    "portalUrl": "https://portal.rschst.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Comprehensive health sciences institute training environmental health officers, community health workers, and dental therapists.",
    "faculties": [
      "School of Community Health",
      "School of Medical Laboratory",
      "School of Environmental Health",
      "School of Health Information Management",
      "School of Dental Health Sciences"
    ]
  }
]
