# NORTH CENTRAL ZONE: Benue, FCT (Abuja), Kogi, Kwara, Nasarawa, Niger, Plateau

DATA = [
  # ----------------------------------------------------
  # BENUE STATE
  # ----------------------------------------------------
  {
    "id": "uam_makurdi",
    "name": "Joseph Sarwuan Tarka University, Makurdi (Federal University of Agriculture)",
    "shortName": "JOSTUM / FUAM",
    "type": "Federal University",
    "ownership": "Federal",
    "state": "Benue",
    "city": "Makurdi",
    "geopoliticalZone": "North Central",
    "establishedYear": 1988,
    "motto": "Innovation, Food Security and Service",
    "logoColor": "#1b5e20",
    "gradingSystem": "5.0",
    "websiteUrl": "https://uam.edu.ng",
    "portalUrl": "https://portal.uam.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/federal-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Named after Senator Joseph Tarka, premier agricultural and engineering federal university in the food basket of the nation.",
    "faculties": [
      "College of Engineering",
      "College of Science",
      "College of Agricultural Economics and Extension",
      "College of Animal Science",
      "College of Agronomy",
      "College of Veterinary Medicine",
      "College of Food Technology and Human Ecology",
      "College of Management Sciences",
      "College of Agricultural and Science Education"
    ]
  },
  {
    "id": "bsu_makurdi",
    "name": "Benue State University, Makurdi",
    "shortName": "BSUM",
    "type": "State University",
    "ownership": "State",
    "state": "Benue",
    "city": "Makurdi",
    "geopoliticalZone": "North Central",
    "establishedYear": 1992,
    "motto": "Scientia Liberatrix Humani (Knowledge Liberates Humanity)",
    "logoColor": "#0d47a1",
    "gradingSystem": "5.0",
    "websiteUrl": "https://bsum.edu.ng",
    "portalUrl": "https://portal.bsum.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/state-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Comprehensive state university in Makurdi, renowned for its college of health sciences, law, environmental science, and management.",
    "faculties": [
      "College of Health Sciences",
      "Faculty of Law",
      "Faculty of Science",
      "Faculty of Management Sciences",
      "Faculty of Social Sciences",
      "Faculty of Environmental Sciences",
      "Faculty of Arts",
      "Faculty of Education"
    ]
  },
  {
    "id": "fedpoly_wanune",
    "name": "Federal Polytechnic, Wannune",
    "shortName": "FPW",
    "type": "Federal Polytechnic",
    "ownership": "Federal",
    "state": "Benue",
    "city": "Wannune, Tarka",
    "geopoliticalZone": "North Central",
    "establishedYear": 2021,
    "motto": "Skill and Technical Prowess",
    "logoColor": "#b71c1c",
    "gradingSystem": "4.0",
    "websiteUrl": "https://fedpolywannune.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Accredited",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/polytechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Federal polytechnic providing vocational, agricultural technology, and engineering diploma courses.",
    "faculties": [
      "School of Engineering Technology",
      "School of Applied Sciences",
      "School of Business Studies"
    ]
  },
  {
    "id": "benue_poly_ugbokolo",
    "name": "Benue State Polytechnic, Ugbokolo",
    "shortName": "BENPOLY",
    "type": "State Polytechnic",
    "ownership": "State",
    "state": "Benue",
    "city": "Ugbokolo, Okpokwu",
    "geopoliticalZone": "North Central",
    "establishedYear": 1977,
    "motto": "Technology for Wealth Creation",
    "logoColor": "#e65100",
    "gradingSystem": "4.0",
    "websiteUrl": "https://benpolyonline.edu.ng",
    "portalUrl": "https://portal.benpolyonline.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/polytechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Major state polytechnic training technologists in engineering, science technology, art and design, and commerce.",
    "faculties": [
      "School of Engineering Technology",
      "School of Technology",
      "School of Business Studies",
      "School of Administrative and Vocational Studies",
      "School of Art and Design"
    ]
  },
  {
    "id": "coe_katsina_ala",
    "name": "College of Education, Katsina-Ala",
    "shortName": "COE Katsina-Ala",
    "type": "State College of Education",
    "ownership": "State",
    "state": "Benue",
    "city": "Katsina-Ala",
    "geopoliticalZone": "North Central",
    "establishedYear": 1976,
    "motto": "Education for Service",
    "logoColor": "#00796b",
    "gradingSystem": "4.0",
    "websiteUrl": "https://coekatsinaala.edu.ng",
    "regulator": "NCCE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://ncceonline.edu.ng",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Historic teacher education college providing NCE programmes and degree affiliation with national universities.",
    "faculties": [
      "School of Sciences",
      "School of Vocational and Technical Education",
      "School of Arts and Social Sciences",
      "School of Languages",
      "School of Education"
    ]
  },

  # ----------------------------------------------------
  # FEDERAL CAPITAL TERRITORY (FCT / ABUJA)
  # ----------------------------------------------------
  {
    "id": "uniabuja",
    "name": "University of Abuja",
    "shortName": "UNIABUJA",
    "type": "Federal University",
    "ownership": "Federal",
    "state": "FCT",
    "city": "Gwagwalada, Abuja",
    "geopoliticalZone": "North Central",
    "establishedYear": 1988,
    "motto": "For Unity and Scholarship",
    "logoColor": "#1b5e20",
    "gradingSystem": "5.0",
    "websiteUrl": "https://uniabuja.edu.ng",
    "portalUrl": "https://portal.uniabuja.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/federal-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Federal university located in the nation's capital, renowned for law, medicine, veterinary medicine, engineering, and distance learning.",
    "faculties": [
      "College of Health Sciences",
      "Faculty of Veterinary Medicine",
      "Faculty of Law",
      "Faculty of Engineering",
      "Faculty of Science",
      "Faculty of Management Sciences",
      "Faculty of Social Sciences",
      "Faculty of Arts",
      "Faculty of Agriculture",
      "Faculty of Environmental Studies",
      "Faculty of Education"
    ]
  },
  {
    "id": "nile_uni_abuja",
    "name": "Nile University of Nigeria, Abuja",
    "shortName": "Nile",
    "type": "Private University",
    "ownership": "Private",
    "state": "FCT",
    "city": "Airport Road, Jabi, Abuja",
    "geopoliticalZone": "North Central",
    "establishedYear": 2009,
    "motto": "Knowledge, Innovation, Excellence",
    "logoColor": "#01579b",
    "gradingSystem": "5.0",
    "websiteUrl": "https://nile.edu.ng",
    "portalUrl": "https://sis.nile.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/private-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Member of Honoris United Universities, offering state-of-the-art medical, law, computing, and engineering education in Abuja.",
    "faculties": [
      "College of Health Sciences",
      "Faculty of Law",
      "Faculty of Engineering",
      "Faculty of Natural and Applied Sciences",
      "Faculty of Management Sciences",
      "Faculty of Arts and Social Sciences"
    ]
  },
  {
    "id": "baze_uni_abuja",
    "name": "Baze University, Abuja",
    "shortName": "BAZE",
    "type": "Private University",
    "ownership": "Private",
    "state": "FCT",
    "city": "Jabi, Abuja",
    "geopoliticalZone": "North Central",
    "establishedYear": 2011,
    "motto": "Building African Zest for Excellence",
    "logoColor": "#880e4f",
    "gradingSystem": "5.0",
    "websiteUrl": "https://bazeuniversity.edu.ng",
    "portalUrl": "https://portal.bazeuniversity.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/private-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Renowned private university established by Senator Datti Baba-Ahmed, offering British standard degrees in law, medicine, computing, and engineering.",
    "faculties": [
      "Faculty of Law",
      "Faculty of Medical Sciences",
      "Faculty of Computing and Applied Sciences",
      "Faculty of Engineering",
      "Faculty of Management and Social Sciences",
      "Faculty of Environmental Sciences"
    ]
  },
  {
    "id": "veritas_uni_abuja",
    "name": "Veritas University, Abuja",
    "shortName": "Veritas",
    "type": "Private University",
    "ownership": "Private",
    "state": "FCT",
    "city": "Bwari, Abuja",
    "geopoliticalZone": "North Central",
    "establishedYear": 2007,
    "motto": "Truth, Virtue, and Moral Excellence",
    "logoColor": "#311b92",
    "gradingSystem": "5.0",
    "websiteUrl": "https://veritas.edu.ng",
    "portalUrl": "https://portal.veritas.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/private-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "The Catholic University of Nigeria, acclaimed for software innovations, sciences, humanities, law, and education.",
    "faculties": [
      "Faculty of Natural and Applied Sciences",
      "Faculty of Law",
      "Faculty of Engineering",
      "Faculty of Management Sciences",
      "Faculty of Social Sciences",
      "Faculty of Humanities",
      "Faculty of Education"
    ]
  },
  {
    "id": "fce_zuba",
    "name": "FCT College of Education, Zuba",
    "shortName": "FCT COE Zuba",
    "type": "State College of Education",
    "ownership": "State",
    "state": "FCT",
    "city": "Zuba, Abuja",
    "geopoliticalZone": "North Central",
    "establishedYear": 1996,
    "motto": "Education for Unity and Development",
    "logoColor": "#00796b",
    "gradingSystem": "4.0",
    "websiteUrl": "https://fctcoezuba.edu.ng",
    "portalUrl": "https://portal.fctcoezuba.edu.ng",
    "regulator": "NCCE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://ncceonline.edu.ng",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Premier teacher training college in the Federal Capital Territory delivering NCE courses in sciences, languages, and vocational education.",
    "faculties": [
      "School of Sciences",
      "School of Vocational and Technical Education",
      "School of Arts and Social Sciences",
      "School of Languages",
      "School of Early Childhood Care and Primary Education"
    ]
  },
  {
    "id": "dorben_poly_abuja",
    "name": "Dorben Polytechnic, Bwari",
    "shortName": "DORBEN",
    "type": "Private Polytechnic",
    "ownership": "Private",
    "state": "FCT",
    "city": "Bwari, Abuja",
    "geopoliticalZone": "North Central",
    "establishedYear": 1995,
    "motto": "Technical Skill for Nation Building",
    "logoColor": "#d84315",
    "gradingSystem": "4.0",
    "websiteUrl": "https://poly.dorben.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/polytechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Pioneering private polytechnic in the Federal Capital Territory delivering engineering, computer science, and business diplomas.",
    "faculties": [
      "School of Engineering",
      "School of Applied Sciences",
      "School of Business Studies",
      "School of Environmental Studies"
    ]
  },

  # ----------------------------------------------------
  # KOGI STATE
  # ----------------------------------------------------
  {
    "id": "fulokoja",
    "name": "Federal University, Lokoja",
    "shortName": "FULOKOJA",
    "type": "Federal University",
    "ownership": "Federal",
    "state": "Kogi",
    "city": "Lokoja & Felele",
    "geopoliticalZone": "North Central",
    "establishedYear": 2011,
    "motto": "Innovation and Leadership for Excellence",
    "logoColor": "#1565c0",
    "gradingSystem": "5.0",
    "websiteUrl": "https://fulokoja.edu.ng",
    "portalUrl": "https://portal.fulokoja.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/federal-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Leading federal university at the confluence of rivers Niger and Benue, with expanding medicine, engineering, computing, and science faculties.",
    "faculties": [
      "College of Health Sciences",
      "Faculty of Science",
      "Faculty of Computing",
      "Faculty of Engineering",
      "Faculty of Management Sciences",
      "Faculty of Social Sciences",
      "Faculty of Arts",
      "Faculty of Education"
    ]
  },
  {
    "id": "ksu_anyigba",
    "name": "Prince Abubakar Audu University, Anyigba (Kogi State University)",
    "shortName": "PAAU / KSU",
    "type": "State University",
    "ownership": "State",
    "state": "Kogi",
    "city": "Anyigba",
    "geopoliticalZone": "North Central",
    "establishedYear": 1999,
    "motto": "Knowledge for Self Reliance",
    "logoColor": "#004d40",
    "gradingSystem": "5.0",
    "websiteUrl": "https://paau.edu.ng",
    "portalUrl": "https://portal.paau.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/state-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Premier state university in Kogi State named after Prince Abubakar Audu, acclaimed for law, agriculture, medicine, and social sciences.",
    "faculties": [
      "Faculty of Law",
      "Faculty of Natural Sciences",
      "Faculty of Agriculture",
      "Faculty of Management Sciences",
      "Faculty of Social Sciences",
      "Faculty of Arts and Humanities",
      "Faculty of Education",
      "Faculty of Health Sciences"
    ]
  },
  {
    "id": "confluence_uni_osara",
    "name": "Confluence University of Science and Technology, Osara",
    "shortName": "CUSTECH",
    "type": "State University",
    "ownership": "State",
    "state": "Kogi",
    "city": "Osara, Okene",
    "geopoliticalZone": "North Central",
    "establishedYear": 2020,
    "motto": "Technology for Transformation",
    "logoColor": "#b71c1c",
    "gradingSystem": "5.0",
    "websiteUrl": "https://custech.edu.ng",
    "portalUrl": "https://portal.custech.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/state-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "State specialized university of science and technology established to drive technological transformation, computing, and mineral development.",
    "faculties": [
      "Faculty of Computing and Informatics",
      "Faculty of Engineering and Technology",
      "Faculty of Science",
      "Faculty of Environmental Technology"
    ]
  },
  {
    "id": "fedpoly_idda",
    "name": "Federal Polytechnic, Idah",
    "shortName": "FPI",
    "type": "Federal Polytechnic",
    "ownership": "Federal",
    "state": "Kogi",
    "city": "Idah",
    "geopoliticalZone": "North Central",
    "establishedYear": 1977,
    "motto": "Technology for Self-Sufficiency",
    "logoColor": "#e65100",
    "gradingSystem": "4.0",
    "websiteUrl": "https://fepoida.edu.ng",
    "portalUrl": "https://portal.fepoida.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/polytechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "One of Nigeria's foremost federal polytechnics, offering engineering, computer science, science laboratory technology, and business studies.",
    "faculties": [
      "School of Engineering",
      "School of Technology",
      "School of Business Studies",
      "School of Environmental Studies",
      "School of General and Administrative Studies"
    ]
  },
  {
    "id": "kogi_poly_lokoja",
    "name": "Kogi State Polytechnic, Lokoja",
    "shortName": "KSP",
    "type": "State Polytechnic",
    "ownership": "State",
    "state": "Kogi",
    "city": "Lokoja & Itakpe",
    "geopoliticalZone": "North Central",
    "establishedYear": 1992,
    "motto": "Knowledge for Self-Reliance",
    "logoColor": "#00796b",
    "gradingSystem": "4.0",
    "websiteUrl": "https://kogistatepolytechnic.edu.ng",
    "portalUrl": "https://portal.kogistatepolytechnic.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/polytechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Multi-campus state polytechnic with main campus in Lokoja and school of engineering at Itakpe.",
    "faculties": [
      "School of Engineering (Itakpe)",
      "School of Applied Sciences",
      "School of Management Studies",
      "School of Art, Design and Printing",
      "School of Environmental Technology"
    ]
  },
  {
    "id": "fce_okene",
    "name": "Federal College of Education, Okene",
    "shortName": "FCE Okene",
    "type": "Federal College of Education",
    "ownership": "Federal",
    "state": "Kogi",
    "city": "Okene",
    "geopoliticalZone": "North Central",
    "establishedYear": 1974,
    "motto": "Excellence in Teacher Education",
    "logoColor": "#2e7d32",
    "gradingSystem": "4.0",
    "websiteUrl": "https://fceokene.edu.ng",
    "portalUrl": "https://portal.fceokene.edu.ng",
    "regulator": "NCCE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://ncceonline.edu.ng",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Federal teacher education college offering NCE and undergraduate degree affiliated programmes in education.",
    "faculties": [
      "School of Sciences",
      "School of Vocational and Technical Education",
      "School of Arts and Social Sciences",
      "School of Languages",
      "School of Education"
    ]
  },

  # ----------------------------------------------------
  # KWARA STATE
  # ----------------------------------------------------
  {
    "id": "unilorin",
    "name": "University of Ilorin",
    "shortName": "UNILORIN",
    "type": "Federal University",
    "ownership": "Federal",
    "state": "Kwara",
    "city": "Ilorin",
    "geopoliticalZone": "North Central",
    "establishedYear": 1975,
    "motto": "Probitas Doctrina (Character and Learning)",
    "logoColor": "#1565c0",
    "gradingSystem": "5.0",
    "websiteUrl": "https://unilorin.edu.ng",
    "portalUrl": "https://portal.unilorin.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/federal-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Nigeria's most sought-after federal university for JAMB applicants, famous for its academic calendar stability, medicine, law, engineering, agriculture, and sciences.",
    "faculties": [
      "College of Health Sciences",
      "Faculty of Pharmaceutical Sciences",
      "Faculty of Veterinary Medicine",
      "Faculty of Law",
      "Faculty of Engineering and Technology",
      "Faculty of Physical Sciences",
      "Faculty of Life Sciences",
      "Faculty of Communication and Information Sciences",
      "Faculty of Management Sciences",
      "Faculty of Social Sciences",
      "Faculty of Arts",
      "Faculty of Agriculture",
      "Faculty of Environmental Sciences",
      "Faculty of Education",
      "Faculty of Basic Medical Sciences",
      "Faculty of Clinical Sciences"
    ]
  },
  {
    "id": "kwasu",
    "name": "Kwara State University, Malete",
    "shortName": "KWASU",
    "type": "State University",
    "ownership": "State",
    "state": "Kwara",
    "city": "Malete, Moro",
    "geopoliticalZone": "North Central",
    "establishedYear": 2009,
    "motto": "Skills and Integrity",
    "logoColor": "#2e7d32",
    "gradingSystem": "5.0",
    "websiteUrl": "https://kwasu.edu.ng",
    "portalUrl": "https://portal.kwasu.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/state-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Pioneering state university with Nigeria's first aeronautical & astronautical engineering programme, alongside strong medical, law, and entrepreneurship faculties.",
    "faculties": [
      "Faculty of Engineering and Technology",
      "Faculty of Pure and Applied Sciences",
      "Faculty of Information and Communication Technology",
      "Faculty of Basic Medical Sciences",
      "Faculty of Law",
      "Faculty of Management and Social Sciences",
      "Faculty of Agriculture",
      "Faculty of Humanities, Management and Social Sciences",
      "Faculty of Education"
    ]
  },
  {
    "id": "al_hikmah_uni",
    "name": "Al-Hikmah University, Ilorin",
    "shortName": "AHU",
    "type": "Private University",
    "ownership": "Private",
    "state": "Kwara",
    "city": "Ilorin",
    "geopoliticalZone": "North Central",
    "establishedYear": 2005,
    "motto": "Learning for Wisdom and Morality",
    "logoColor": "#004d40",
    "gradingSystem": "5.0",
    "websiteUrl": "https://alhikmah.edu.ng",
    "portalUrl": "https://portal.alhikmah.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/private-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Leading Islamic faith-based private university in Ilorin, offering accredited programmes in nursing, law, computing, and health sciences.",
    "faculties": [
      "Faculty of Health Sciences",
      "Faculty of Law",
      "Faculty of Natural and Applied Sciences",
      "Faculty of Management Sciences",
      "Faculty of Humanities and Social Sciences",
      "Faculty of Education",
      "Faculty of Agriculture"
    ]
  },
  {
    "id": "landmark_uni",
    "name": "Landmark University, Omu-Aran",
    "shortName": "LMU",
    "type": "Private University",
    "ownership": "Private",
    "state": "Kwara",
    "city": "Omu-Aran",
    "geopoliticalZone": "North Central",
    "establishedYear": 2011,
    "motto": "Breaking New Grounds in Agriculture and Technology",
    "logoColor": "#1b5e20",
    "gradingSystem": "5.0",
    "websiteUrl": "https://lmu.edu.ng",
    "portalUrl": "https://portal.lmu.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/private-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Leading agrarian and technological private university established by the Living Faith Church, acclaimed for agricultural engineering, robotics, and sciences.",
    "faculties": [
      "College of Agricultural Sciences",
      "College of Engineering",
      "College of Pure and Applied Sciences",
      "College of Business and Social Sciences"
    ]
  },
  {
    "id": "fedpoly_offa",
    "name": "Federal Polytechnic, Offa",
    "shortName": "FEDPOFFA",
    "type": "Federal Polytechnic",
    "ownership": "Federal",
    "state": "Kwara",
    "city": "Offa",
    "geopoliticalZone": "North Central",
    "establishedYear": 1992,
    "motto": "Technology for Self Reliance",
    "logoColor": "#b71c1c",
    "gradingSystem": "4.0",
    "websiteUrl": "https://fpo.edu.ng",
    "portalUrl": "https://portal.fpo.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/polytechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Top-tier federal polytechnic in North Central Nigeria, famous for electrical and mechanical engineering, computer science, and accounting.",
    "faculties": [
      "School of Engineering Technology",
      "School of Applied Sciences and Technology",
      "School of Business and Management Studies",
      "School of Communication and Information Technology",
      "School of Environmental Studies"
    ]
  },
  {
    "id": "kwara_poly_ilorin",
    "name": "Kwara State Polytechnic, Ilorin",
    "shortName": "KWARAPOLY",
    "type": "State Polytechnic",
    "ownership": "State",
    "state": "Kwara",
    "city": "Ilorin",
    "geopoliticalZone": "North Central",
    "establishedYear": 1973,
    "motto": "Technology and Management for Self-Sufficiency",
    "logoColor": "#00796b",
    "gradingSystem": "4.0",
    "websiteUrl": "https://kwarastatepolytechnic.edu.ng",
    "portalUrl": "https://portal.kwarastatepolytechnic.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/polytechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Historic state polytechnic offering expansive technical diploma programmes across engineering, computing, environmental design, and management.",
    "faculties": [
      "Institute of Technology",
      "Institute of Applied Sciences",
      "Institute of Finance and Management Studies",
      "Institute of Environmental Studies",
      "Institute of Information and Communication Technology"
    ]
  },

  # ----------------------------------------------------
  # NASARAWA STATE
  # ----------------------------------------------------
  {
    "id": "fulafia",
    "name": "Federal University of Lafia",
    "shortName": "FULAFIA",
    "type": "Federal University",
    "ownership": "Federal",
    "state": "Nasarawa",
    "city": "Lafia",
    "geopoliticalZone": "North Central",
    "establishedYear": 2011,
    "motto": "Innovation and Integrity",
    "logoColor": "#1b5e20",
    "gradingSystem": "5.0",
    "websiteUrl": "https://fulafia.edu.ng",
    "portalUrl": "https://portal.fulafia.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/federal-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Fast growing federal university in Nasarawa State, featuring college of medicine, computing, sciences, agriculture, and humanities.",
    "faculties": [
      "College of Medicine",
      "Faculty of Science",
      "Faculty of Computing",
      "Faculty of Social Sciences",
      "Faculty of Arts",
      "Faculty of Agriculture",
      "Faculty of Environmental Design",
      "Faculty of Education"
    ]
  },
  {
    "id": "nsuk_keffi",
    "name": "Nasarawa State University, Keffi",
    "shortName": "NSUK",
    "type": "State University",
    "ownership": "State",
    "state": "Nasarawa",
    "city": "Keffi",
    "geopoliticalZone": "North Central",
    "establishedYear": 2001,
    "motto": "Knowledge for Development",
    "logoColor": "#0d47a1",
    "gradingSystem": "5.0",
    "websiteUrl": "https://nsuk.edu.ng",
    "portalUrl": "https://portal.nsuk.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/state-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Premier state university in Nasarawa State, strategically situated near Abuja, renowned for law, natural sciences, administration, and agriculture (Lafia campus).",
    "faculties": [
      "Faculty of Law",
      "Faculty of Natural and Applied Sciences",
      "Faculty of Administration",
      "Faculty of Social Sciences",
      "Faculty of Arts",
      "Faculty of Agriculture (Lafia Campus)",
      "Faculty of Environmental Sciences",
      "Faculty of Education",
      "College of Medical Sciences"
    ]
  },
  {
    "id": "bingham_uni",
    "name": "Bingham University, Karu",
    "shortName": "Bingham",
    "type": "Private University",
    "ownership": "Private",
    "state": "Nasarawa",
    "city": "Karu, New Karu",
    "geopoliticalZone": "North Central",
    "establishedYear": 2005,
    "motto": "Knowledge, Faith and Service",
    "logoColor": "#b71c1c",
    "gradingSystem": "5.0",
    "websiteUrl": "https://binghamuni.edu.ng",
    "portalUrl": "https://portal.binghamuni.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/private-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Private Christian university established by ECWA, acclaimed for its college of health sciences, pharmacy, law, computing, and social sciences.",
    "faculties": [
      "College of Health Sciences",
      "Faculty of Pharmacy",
      "Faculty of Law",
      "Faculty of Science and Technology",
      "Faculty of Administration and Social Sciences",
      "Faculty of Arts",
      "Faculty of Environmental Sciences"
    ]
  },
  {
    "id": "nasarawa_poly_lafia",
    "name": "Isa Mustapha Agwai I Polytechnic, Lafia (Nasarawa State Poly)",
    "shortName": "IMAP / NASPOLY",
    "type": "State Polytechnic",
    "ownership": "State",
    "state": "Nasarawa",
    "city": "Lafia",
    "geopoliticalZone": "North Central",
    "establishedYear": 2000,
    "motto": "Skills and Technology for Self Reliance",
    "logoColor": "#00796b",
    "gradingSystem": "4.0",
    "websiteUrl": "https://imap.edu.ng",
    "portalUrl": "https://portal.imap.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/polytechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "State polytechnic in Lafia providing accredited technical diplomas in engineering, architectural technology, sciences, and business.",
    "faculties": [
      "School of Engineering Technology",
      "School of Applied Sciences",
      "School of Business Studies",
      "School of Environmental Studies"
    ]
  },
  {
    "id": "coe_akwanga",
    "name": "College of Education, Akwanga",
    "shortName": "COE Akwanga",
    "type": "State College of Education",
    "ownership": "State",
    "state": "Nasarawa",
    "city": "Akwanga",
    "geopoliticalZone": "North Central",
    "establishedYear": 1977,
    "motto": "Education for Light and Progress",
    "logoColor": "#2e7d32",
    "gradingSystem": "4.0",
    "websiteUrl": "https://coeakwanga.edu.ng",
    "portalUrl": "https://portal.coeakwanga.edu.ng",
    "regulator": "NCCE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://ncceonline.edu.ng",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Major state teacher education college delivering NCE diplomas and undergraduate degree affiliations with ABU and UNIJOS.",
    "faculties": [
      "School of Sciences",
      "School of Vocational and Technical Education",
      "School of Arts and Social Sciences",
      "School of Languages",
      "School of Education"
    ]
  },

  # ----------------------------------------------------
  # NIGER STATE
  # ----------------------------------------------------
  {
    "id": "futminna",
    "name": "Federal University of Technology, Minna",
    "shortName": "FUTMINNA",
    "type": "Federal University",
    "ownership": "Federal",
    "state": "Niger",
    "city": "Minna",
    "geopoliticalZone": "North Central",
    "establishedYear": 1983,
    "motto": "Technology for Empowerment",
    "logoColor": "#1565c0",
    "gradingSystem": "5.0",
    "websiteUrl": "https://futminna.edu.ng",
    "portalUrl": "https://eportal.futminna.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/federal-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Leading technological federal university in Nigeria, acclaimed for mechatronics, telecommunications, chemical engineering, artificial intelligence, and agriculture.",
    "faculties": [
      "School of Engineering and Engineering Technology",
      "School of Information and Communication Technology",
      "School of Physical Sciences",
      "School of Life Sciences",
      "School of Environmental Technology",
      "School of Agriculture and Agricultural Technology",
      "School of Science and Technology Education",
      "School of Infrastructure, Process Engineering and Technology"
    ]
  },
  {
    "id": "ibbu_lapai",
    "name": "Ibrahim Badamasi Babangida University, Lapai",
    "shortName": "IBBUL",
    "type": "State University",
    "ownership": "State",
    "state": "Niger",
    "city": "Lapai",
    "geopoliticalZone": "North Central",
    "establishedYear": 2005,
    "motto": "Learning for Light",
    "logoColor": "#004d40",
    "gradingSystem": "5.0",
    "websiteUrl": "https://ibbu.edu.ng",
    "portalUrl": "https://portals.ibbu.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/state-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "State university named after General Ibrahim Babangida, recognized for hydrocarbon exploration research, computer science, agriculture, and education.",
    "faculties": [
      "Faculty of Natural Sciences",
      "Faculty of Applied Sciences and Technology",
      "Faculty of Agriculture",
      "Faculty of Management and Social Sciences",
      "Faculty of Languages and Communication Studies",
      "Faculty of Education"
    ]
  },
  {
    "id": "fedpoly_bida",
    "name": "Federal Polytechnic, Bida",
    "shortName": "FPB",
    "type": "Federal Polytechnic",
    "ownership": "Federal",
    "state": "Niger",
    "city": "Bida",
    "geopoliticalZone": "North Central",
    "establishedYear": 1977,
    "motto": "Technology for Self-Reliance",
    "logoColor": "#b71c1c",
    "gradingSystem": "4.0",
    "websiteUrl": "https://fedpolybida.edu.ng",
    "portalUrl": "https://portal.fedpolybida.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/polytechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "One of Nigeria's premier federal polytechnics, offering accredited ND and HND engineering, agricultural technology, and administrative studies.",
    "faculties": [
      "School of Engineering Technology",
      "School of Applied and Natural Sciences",
      "School of Business Administration and Management",
      "School of Financial Studies",
      "School of Environmental Studies"
    ]
  },
  {
    "id": "fce_kontagora",
    "name": "Federal College of Education, Kontagora",
    "shortName": "FCE Kontagora",
    "type": "Federal College of Education",
    "ownership": "Federal",
    "state": "Niger",
    "city": "Kontagora",
    "geopoliticalZone": "North Central",
    "establishedYear": 1978,
    "motto": "Education for Light and Service",
    "logoColor": "#2e7d32",
    "gradingSystem": "4.0",
    "websiteUrl": "https://fcekg.edu.ng",
    "portalUrl": "https://portal.fcekg.edu.ng",
    "regulator": "NCCE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://ncceonline.edu.ng",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Federal teacher education college offering accredited NCE and undergraduate degree affiliation courses in education.",
    "faculties": [
      "School of Sciences",
      "School of Vocational and Technical Education",
      "School of Arts and Social Sciences",
      "School of Languages",
      "School of Education"
    ]
  },
  {
    "id": "niger_nursing_bida",
    "name": "Niger State College of Nursing Sciences, Bida & Kontagora",
    "shortName": "SOM Bida",
    "type": "College of Nursing Sciences",
    "ownership": "State",
    "state": "Niger",
    "city": "Bida & Kontagora",
    "geopoliticalZone": "North Central",
    "establishedYear": 1976,
    "motto": "Care and Knowledge for Health",
    "logoColor": "#00838f",
    "gradingSystem": "4.0",
    "websiteUrl": "https://sommidwiferybida.edu.ng",
    "regulator": "NMCN",
    "accreditationStatus": "Accredited",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nmcn.gov.ng",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Official state college providing registered nursing and registered midwifery training accredited by NMCN.",
    "faculties": [
      "Department of Basic Nursing",
      "Department of Basic Midwifery"
    ]
  },

  # ----------------------------------------------------
  # PLATEAU STATE
  # ----------------------------------------------------
  {
    "id": "unijos",
    "name": "University of Jos",
    "shortName": "UNIJOS",
    "type": "Federal University",
    "ownership": "Federal",
    "state": "Plateau",
    "city": "Jos",
    "geopoliticalZone": "North Central",
    "establishedYear": 1975,
    "motto": "Discipline and Dedication",
    "logoColor": "#0d47a1",
    "gradingSystem": "5.0",
    "websiteUrl": "https://unijos.edu.ng",
    "portalUrl": "https://portal.unijos.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/federal-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Renowned federal university situated on the Jos Plateau, acclaimed for medicine, pharmacy, law, environmental sciences, and natural sciences.",
    "faculties": [
      "Faculty of Medical Sciences",
      "Faculty of Pharmaceutical Sciences",
      "Faculty of Veterinary Medicine",
      "Faculty of Law",
      "Faculty of Natural Sciences",
      "Faculty of Engineering",
      "Faculty of Management Sciences",
      "Faculty of Social Sciences",
      "Faculty of Arts",
      "Faculty of Environmental Sciences",
      "Faculty of Agriculture",
      "Faculty of Education",
      "Faculty of Dental Sciences"
    ]
  },
  {
    "id": "plasu_bokkos",
    "name": "Plateau State University, Bokkos",
    "shortName": "PLASU",
    "type": "State University",
    "ownership": "State",
    "state": "Plateau",
    "city": "Bokkos",
    "geopoliticalZone": "North Central",
    "establishedYear": 2005,
    "motto": "Knowledge, Diligence and Integrity",
    "logoColor": "#004d40",
    "gradingSystem": "5.0",
    "websiteUrl": "https://plasu.edu.ng",
    "portalUrl": "https://portal.plasu.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/state-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "State university located in Bokkos, delivering accredited degree programmes in natural sciences, law, humanities, and social sciences.",
    "faculties": [
      "Faculty of Natural and Applied Sciences",
      "Faculty of Law",
      "Faculty of Management Sciences",
      "Faculty of Social Sciences",
      "Faculty of Arts",
      "Faculty of Environmental Sciences",
      "Faculty of Health Sciences"
    ]
  },
  {
    "id": "karl_kumm_uni",
    "name": "Karl Kumm University, Vom",
    "shortName": "KKU",
    "type": "Private University",
    "ownership": "Private",
    "state": "Plateau",
    "city": "Vom, Jos South",
    "geopoliticalZone": "North Central",
    "establishedYear": 2021,
    "motto": "Truth, Honour and Hard Work",
    "logoColor": "#4a148c",
    "gradingSystem": "5.0",
    "websiteUrl": "https://kku.edu.ng",
    "portalUrl": "https://portal.kku.edu.ng",
    "regulator": "NUC",
    "accreditationStatus": "Accredited",
    "verificationStatus": "Verified",
    "sourceUrl": "https://www.nuc.edu.ng/nigerian-univerisities/private-universities/",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Christian private university established by COCIN in Vom, focused on high academic discipline, science, and computing.",
    "faculties": [
      "Faculty of Science and Computing",
      "Faculty of Management and Social Sciences"
    ]
  },
  {
    "id": "plateau_poly_barkin_ladi",
    "name": "Plateau State Polytechnic, Barkin Ladi",
    "shortName": "PLAPOLY",
    "type": "State Polytechnic",
    "ownership": "State",
    "state": "Plateau",
    "city": "Barkin Ladi & Jos",
    "geopoliticalZone": "North Central",
    "establishedYear": 1978,
    "motto": "Technological Excellence for Humanity",
    "logoColor": "#e65100",
    "gradingSystem": "4.0",
    "websiteUrl": "https://plapoly.edu.ng",
    "portalUrl": "https://portal.plapoly.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/polytechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Multi-campus state polytechnic with main campus in Barkin Ladi and city campus in Jos.",
    "faculties": [
      "School of Engineering Technology",
      "School of Science and Technology",
      "School of Information and Communication Technology",
      "School of Administration and Business Studies",
      "School of Environmental Studies"
    ]
  },
  {
    "id": "fce_pankshin",
    "name": "Federal College of Education, Pankshin",
    "shortName": "FCE Pankshin",
    "type": "Federal College of Education",
    "ownership": "Federal",
    "state": "Plateau",
    "city": "Pankshin",
    "geopoliticalZone": "North Central",
    "establishedYear": 1974,
    "motto": "Excellence in Teacher Education",
    "logoColor": "#2e7d32",
    "gradingSystem": "4.0",
    "websiteUrl": "https://fcepankshin.edu.ng",
    "portalUrl": "https://portal.fcepankshin.edu.ng",
    "regulator": "NCCE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://ncceonline.edu.ng",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Premier federal teacher training college in Plateau State producing certified teachers in sciences, arts, and vocational studies.",
    "faculties": [
      "School of Sciences",
      "School of Vocational and Technical Education",
      "School of Arts and Social Sciences",
      "School of Languages",
      "School of Education"
    ]
  },
  {
    "id": "fcvmlt_vom",
    "name": "Federal College of Veterinary and Medical Laboratory Technology, Vom",
    "shortName": "FCVMLT Vom",
    "type": "Monotechnic / Specialized Institution",
    "ownership": "Federal",
    "state": "Plateau",
    "city": "Vom, Jos South",
    "geopoliticalZone": "North Central",
    "establishedYear": 1956,
    "motto": "Excellence in Veterinary and Medical Laboratory Science",
    "logoColor": "#00796b",
    "gradingSystem": "4.0",
    "websiteUrl": "https://fcvmlt.edu.ng",
    "regulator": "NBTE",
    "accreditationStatus": "Full Accreditation",
    "verificationStatus": "Verified",
    "sourceUrl": "https://nbte.gov.ng/monotechnics",
    "lastVerified": "2024-06-15",
    "isDemo": False,
    "description": "Pioneering federal veterinary and medical laboratory technology monotechnic producing world-class biomedical technicians.",
    "faculties": [
      "Department of Medical Laboratory Science",
      "Department of Veterinary Laboratory Technology",
      "Department of Environmental Health",
      "Department of Computer Science"
    ]
  }
]
