# Part 1: Additional Universities & Polytechnics in Nigeria
# Covers NUC Approved Federal, State & Private Universities, plus NBTE Approved Federal, State & Private Polytechnics

UNIVERSITIES = [
  # Federal & Special Academies
  ("Nigeria Police Academy, Wudil", "POLAC", "Federal University", "Federal", "Kano", "Wudil", 2012, "Knowledge and Security", "#1a237e", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Air Force Institute of Technology, Kaduna", "AFIT", "Federal University", "Federal", "Kaduna", "Kaduna", 1977, "Excellence in Aerospace", "#0d47a1", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Admiralty University of Nigeria, Ibusa", "ADUN", "Federal University", "Federal", "Delta", "Ibusa", 2017, "Excellence and Integrity", "#002171", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Federal University of Health Sciences, Otukpo", "FUHSO", "Federal University", "Federal", "Benue", "Otukpo", 2019, "Health is Wealth", "#004d40", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Federal University of Health Sciences, Ila-Orangun", "FUHSI", "Federal University", "Federal", "Osun", "Ila-Orangun", 2021, "Healing through Knowledge", "#1b5e20", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Federal University of Health Sciences, Azare", "FUHSA", "Federal University", "Federal", "Bauchi", "Azare", 2021, "Service and Healing", "#00695c", "NUC", "Full Accreditation", "Verified", 5.0),
  ("David Umahi Federal University of Health Sciences, Uburu", "DUFUHS", "Federal University", "Federal", "Ebonyi", "Uburu", 2022, "Excellence in Medical Science", "#004d40", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Federal University of Technology, Babura", "FUTB", "Federal University", "Federal", "Jigawa", "Babura", 2021, "Technology for Innovation", "#01579b", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Federal University of Technology, Ikot Abasi", "FUTIA", "Federal University", "Federal", "Akwa Ibom", "Ikot Abasi", 2021, "Innovation and Technology", "#004d40", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Federal University of Agriculture, Zuru", "FUAZ", "Federal University", "Federal", "Kebbi", "Zuru", 2020, "Agriculture for Sustainability", "#2e7d32", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Nigerian Army University, Biu", "NAUB", "Federal University", "Federal", "Borno", "Biu", 2018, "Knowledge, Warfare and Tech", "#1b5e20", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Nigerian Maritime University, Okerenkoko", "NMU", "Federal University", "Federal", "Delta", "Okerenkoko", 2015, "Advancing Maritime Knowledge", "#01579b", "NUC", "Full Accreditation", "Verified", 5.0),

  # State Universities
  ("Lagos State University of Science and Technology", "LASUSTECH", "State University", "State", "Lagos", "Ikorodu", 2022, "Excellence in Applied Science & Tech", "#004d40", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Lagos State University of Education", "LASUED", "State University", "State", "Lagos", "Ijanikin/Epe", 2022, "Education for Transformation", "#1b5e20", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Bamidele Olumilua University of Education, Science and Technology", "BOUESTI", "State University", "State", "Ekiti", "Ikere-Ekiti", 2020, "Building Total Man", "#0277bd", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Confluence University of Science and Technology", "CUSTECH", "State University", "State", "Kogi", "Osara", 2020, "Science and Technology for Nation Building", "#00695c", "NUC", "Full Accreditation", "Verified", 5.0),
  ("University of Delta, Agbor", "UNIDEL", "State University", "State", "Delta", "Agbor", 2021, "Knowledge, Character and Service", "#004d40", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Delta State University of Science and Technology", "DSUST", "State University", "State", "Delta", "Ozoro", 2021, "Skill and Innovation", "#01579b", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Dennis Osadebay University, Asaba", "DOU", "State University", "State", "Delta", "Anwai, Asaba", 2021, "Knowledge, Excellence and Integrity", "#1b5e20", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Kingsley Ozumba Mbadiwe University", "KOMU", "State University", "State", "Imo", "Ogboko, Ideato", 2016, "Excellence and Leadership", "#004d40", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Shehu Shagari University of Education, Sokoto", "SSUES", "State University", "State", "Sokoto", "Sokoto", 2022, "Service and Enlightenment", "#00695c", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Abdulkadir Kure University, Minna", "AKUM", "State University", "State", "Niger", "Minna", 2023, "Knowledge and Character", "#1b5e20", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Kogi State University, Kabba", "KSUK", "State University", "State", "Kogi", "Kabba", 2023, "Knowledge for Self Reliance", "#004d40", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Sa'adatu Rimi University of Education, Kumbotso", "SRUE", "State University", "State", "Kano", "Kumbotso", 2023, "Knowledge, Discipline and Service", "#00695c", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Emmanuel Alayande University of Education, Oyo", "EAUED", "State University", "State", "Oyo", "Oyo", 2022, "Excellence in Teacher Education", "#1b5e20", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Olusegun Agagu University of Science and Technology", "OAUSTECH", "State University", "State", "Ondo", "Okitipupa", 2008, "Technology for Development", "#01579b", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Ignatius Ajuru University of Education", "IAUE", "State University", "State", "Rivers", "Rumuolumeni, Port Harcourt", 2009, "Education for Self Reliance", "#004d40", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Sule Lamido University", "SLU", "State University", "State", "Jigawa", "Kafin Hausa", 2013, "Excellence with Morality", "#00695c", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Yusuf Maitama Sule University", "YUMSUK", "State University", "State", "Kano", "Kano", 2012, "Knowledge for Service", "#004d40", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Aliko Dangote University of Science and Technology", "ADUSTECH", "State University", "State", "Kano", "Wudil", 2001, "Progress through Science and Technology", "#01579b", "NUC", "Full Accreditation", "Verified", 5.0),

  # Private Universities (NUC Approved)
  ("Nile University of Nigeria", "NILE", "Private University", "Private", "FCT", "Jabi, Abuja", 2009, "Knowledge, Innovation and Service", "#0d47a1", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Baze University", "BAZE", "Private University", "Private", "FCT", "Jabi, Abuja", 2011, "Learn to Excel", "#b71c1c", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Veritas University, Abuja", "VERITAS", "Private University", "Private", "FCT", "Bwari, Abuja", 2007, "Truth, Knowledge and Integrity", "#1b5e20", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Philomath University", "PHILOMATH", "Private University", "Private", "FCT", "Kuje, Abuja", 2021, "Passion for Learning", "#004d40", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Canadian University of Nigeria", "CUN", "Private University", "Private", "FCT", "Abuja", 2023, "Global Standards in Education", "#b71c1c", "NUC", "Full Accreditation", "Verified", 5.0),
  ("European University of Nigeria", "EUN", "Private University", "Private", "FCT", "Duboyi, Abuja", 2023, "Innovation and Excellence", "#01579b", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Miva Open University", "MIVA", "Private University", "Private", "FCT", "Abuja", 2023, "Accessible Flexible Learning", "#4a148c", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Prime University, Abuja", "PRIME", "Private University", "Private", "FCT", "Kuje, Abuja", 2023, "Knowledge and Leadership", "#004d40", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Covenant University", "CU", "Private University", "Private", "Ogun", "Ota", 2002, "Raising a new Generation of Leaders", "#4a148c", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Babcock University", "BABCOCK", "Private University", "Private", "Ogun", "Ilishan-Remo", 1999, "Knowledge, Truth, Service", "#0d47a1", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Bells University of Technology", "BELLSTECH", "Private University", "Private", "Ogun", "Ota", 2005, "Technology for Development", "#b71c1c", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Crawford University", "CRAWFORD", "Private University", "Private", "Ogun", "Igbesa", 2005, "Knowledge with Godliness", "#004d40", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Crescent University", "CRESCENT", "Private University", "Private", "Ogun", "Abeokuta", 2005, "Citadel of Academic and Moral Excellence", "#1b5e20", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Mountain Top University", "MTU", "Private University", "Private", "Ogun", "Makogi Oba", 2015, "Empowered for Excellence", "#004d40", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Chrisland University", "CHRISLAND", "Private University", "Private", "Ogun", "Abeokuta", 2015, "Intellectual Radiance", "#311b92", "NUC", "Full Accreditation", "Verified", 5.0),
  ("McPherson University", "MCU", "Private University", "Private", "Ogun", "Seriki Sotayo", 2012, "Knowledge with Godliness", "#00695c", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Southwestern University, Nigeria", "SUN", "Private University", "Private", "Ogun", "Okun Owa", 2012, "Knowledge for Self Reliance", "#0d47a1", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Hallmark University, Ijebu-Itele", "HALLMARK", "Private University", "Private", "Ogun", "Ijebu-Itele", 2015, "Excellence and Integrity", "#b71c1c", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Gerar University of Medical Sciences", "GUMS", "Private University", "Private", "Ogun", "Imope-Ijebu", 2023, "Excellence in Medical Sciences", "#004d40", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Vision University, Ikogbo", "VISION", "Private University", "Private", "Ogun", "Ikogbo", 2023, "Enlightenment through Vision", "#1b5e20", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Pan-Atlantic University", "PAU", "Private University", "Private", "Lagos", "Ibeju-Lekki", 2002, "Nurturing professional excellence", "#0d47a1", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Caleb University", "CALEB", "Private University", "Private", "Lagos", "Imota, Ikorodu", 2007, "For God and Humanity", "#b71c1c", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Anchor University, Lagos", "AUL", "Private University", "Private", "Lagos", "Ayobo, Ipaja", 2014, "Character, Competence, Courage", "#01579b", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Augustine University, Ilara-Epe", "AUI", "Private University", "Private", "Lagos", "Ilara-Epe", 2015, "For Learning and Character", "#004d40", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Trinity University, Yaba", "TU", "Private University", "Private", "Lagos", "Yaba", 2019, "Knowledge, Character, Excellence", "#1b5e20", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Eko University of Medicine and Health Sciences", "EKOMISU", "Private University", "Private", "Lagos", "Ijanikin", 2017, "Healing and Service", "#00695c", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Maranatha University, Lekki", "MARANATHA", "Private University", "Private", "Lagos", "Lekki", 2021, "Truth, Love and Excellence", "#311b92", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Lead City University", "LCU", "Private University", "Private", "Oyo", "Ibadan", 2005, "Knowledge for Self Reliance", "#0d47a1", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Ajayi Crowther University", "ACU", "Private University", "Private", "Oyo", "Oyo", 2005, "Knowledge, Character, Service", "#b71c1c", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Dominican University, Ibadan", "DU", "Private University", "Private", "Oyo", "Ibadan", 2016, "Veritas (Truth)", "#004d40", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Precious Cornerstone University", "PCU", "Private University", "Private", "Oyo", "Ibadan", 2017, "Building Total Man", "#1b5e20", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Dominion University, Ibadan", "DOMINION", "Private University", "Private", "Oyo", "Ibadan", 2019, "Empowering Minds", "#4a148c", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Atiba University, Oyo", "ATIBA", "Private University", "Private", "Oyo", "Oyo", 2017, "Discipline and Excellence", "#00695c", "NUC", "Full Accreditation", "Verified", 5.0),
  ("West Midlands Open University", "WMOU", "Private University", "Private", "Oyo", "Ibadan", 2023, "Global Distance Learning", "#01579b", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Bowen University", "BOWEN", "Private University", "Private", "Osun", "Iwo", 2001, "Excellence and Godliness", "#0d47a1", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Redeemer's University", "RUN", "Private University", "Private", "Osun", "Ede", 2005, "Running with a Vision", "#b71c1c", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Adeleke University", "AU", "Private University", "Private", "Osun", "Ede", 2011, "Education, Excellence and Character", "#004d40", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Fountain University, Osogbo", "FUO", "Private University", "Private", "Osun", "Osogbo", 2007, "Faith, Knowledge and Service", "#1b5e20", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Joseph Ayo Babalola University", "JABU", "Private University", "Private", "Osun", "Ikeji-Arakeji", 2006, "For Knowledge and Godliness", "#311b92", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Kings University, Odeomu", "KU", "Private University", "Private", "Osun", "Odeomu", 2015, "Knowledge for Leadership", "#00695c", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Westland University, Iwo", "WESTLAND", "Private University", "Private", "Osun", "Iwo", 2019, "Knowledge and Innovation", "#01579b", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Mercy Medical University, Iwo", "MMU", "Private University", "Private", "Osun", "Iwo", 2023, "Healing and Compassion", "#004d40", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Minaret University, Ikirun", "MINARET", "Private University", "Private", "Osun", "Ikirun", 2023, "Light through Knowledge", "#1b5e20", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Elizade University", "ELIZADE", "Private University", "Private", "Ondo", "Ilara-Mokin", 2012, "Knowledge, Skill and Character", "#b71c1c", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Achievers University, Owo", "ACHIEVERS", "Private University", "Private", "Ondo", "Owo", 2007, "Knowledge, Integrity and Leadership", "#004d40", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Wesley University, Ondo", "WESLEY", "Private University", "Private", "Ondo", "Ondo City", 2007, "Excellence in Godliness", "#1b5e20", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Afe Babalola University, Ado-Ekiti", "ABUAD", "Private University", "Private", "Ekiti", "Ado-Ekiti", 2009, "Labor, Service and Integrity", "#0d47a1", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Venite University, Iloro-Ekiti", "VENITE", "Private University", "Private", "Ekiti", "Iloro-Ekiti", 2023, "Integrity, Truth and Light", "#00695c", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Igbinedion University, Okada", "IUO", "Private University", "Private", "Edo", "Okada", 1999, "Knowledge, Excellence, Integrity", "#004d40", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Benson Idahosa University", "BIU", "Private University", "Private", "Edo", "Benin City", 2002, "Academic Excellence with Godliness", "#b71c1c", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Wellspring University", "WELLSPRING", "Private University", "Private", "Edo", "Benin City", 2009, "Spring of Knowledge", "#1b5e20", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Lighthouse University, Evbuobanosa", "LU", "Private University", "Private", "Edo", "Evbuobanosa", 2024, "Shining Light of Truth", "#01579b", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Novena University", "NOVENA", "Private University", "Private", "Delta", "Ogume", 2005, "Knowledge for Self Reliance", "#004d40", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Western Delta University", "WDU", "Private University", "Private", "Delta", "Oghara", 2007, "Knowledge and Integrity", "#00695c", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Madonna University, Elele", "MADONNA", "Private University", "Private", "Rivers", "Elele", 1999, "Dignitas in Virtute", "#0d47a1", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Wigwe University", "WIGWE", "Private University", "Private", "Rivers", "Isiokpo", 2023, "Fearless, Visionary, World-Class", "#b71c1c", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Topfaith University", "TOPFAITH", "Private University", "Private", "Akwa Ibom", "Mkpatak", 2021, "Faith in Knowledge", "#1b5e20", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Havilla University, Nde-Ikom", "HAVILLA", "Private University", "Private", "Cross River", "Nde-Ikom", 2021, "Knowledge with Godliness", "#004d40", "NUC", "Full Accreditation", "Verified", 5.0),
  ("British Canadian University, Obudu", "BCU", "Private University", "Private", "Cross River", "Obudu", 2023, "Global Excellence in Learning", "#01579b", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Godfrey Okoye University", "GOUNI", "Private University", "Private", "Enugu", "Ugwuomu-Nike", 2009, "Episteme et Fides", "#4a148c", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Caritas University", "CARITAS", "Private University", "Private", "Enugu", "Amorji-Nike", 2005, "Love and Service", "#004d40", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Renaissance University", "RNU", "Private University", "Private", "Enugu", "Ugbawka", 2005, "Rebirth of Excellence", "#b71c1c", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Maduka University, Ekwegbe", "MADUKA", "Private University", "Private", "Enugu", "Ekwegbe-Nsukka", 2023, "Excellence and Practical Skill", "#1b5e20", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Peaceland University, Enugu", "PEACELAND", "Private University", "Private", "Enugu", "Enugu", 2023, "Peace and Wisdom", "#00695c", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Paul University, Awka", "PUA", "Private University", "Private", "Anambra", "Awka", 2009, "Faith and Wisdom", "#0d47a1", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Tansian University, Umunya", "TANSIAN", "Private University", "Private", "Anambra", "Umunya", 2009, "Scientia Potentia Est", "#004d40", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Shanahan University, Onitsha", "SHANAHAN", "Private University", "Private", "Anambra", "Onitsha", 2023, "Truth, Light and Virtue", "#b71c1c", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Rhema University, Aba", "RHEMA", "Private University", "Private", "Abia", "Aba", 2009, "Equipping for Destiny", "#1b5e20", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Clifford University, Ihie", "CLU", "Private University", "Private", "Abia", "Ihie", 2016, "Excellence in Godliness", "#00695c", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Spiritan University, Nneochi", "SUN", "Private University", "Private", "Abia", "Nneochi", 2017, "Cor Unum et Anima Una", "#01579b", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Amadeus University, Amizi", "AMADEUS", "Private University", "Private", "Abia", "Amizi, Ikwuano", 2024, "Knowledge for the Future", "#004d40", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Claretian University of Nigeria, Nekede", "CUN", "Private University", "Private", "Imo", "Nekede, Owerri", 2021, "Service, Virtue and Excellence", "#b71c1c", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Hezekiah University, Umudi", "UNIHEZ", "Private University", "Private", "Imo", "Umudi, Nkwerre", 2015, "Knowledge for Salvation", "#1b5e20", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Al-Hikmah University, Ilorin", "AL-HIKMAH", "Private University", "Private", "Kwara", "Ilorin", 2005, "Learning for Wisdom and Morality", "#004d40", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Landmark University, Omu-Aran", "LMU", "Private University", "Private", "Kwara", "Omu-Aran", 2011, "Breaking New Grounds in Agriculture", "#2e7d32", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Thomas Adewumi University, Oko", "TAU", "Private University", "Private", "Kwara", "Oko-Irese", 2021, "Knowledge, Innovation, Global Impact", "#0d47a1", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Bingham University, Karu", "BINGHAM", "Private University", "Private", "Nasarawa", "Karu", 2005, "Mission for Knowledge and Service", "#b71c1c", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Mewar International University, Masaka", "MEWAR", "Private University", "Private", "Nasarawa", "Masaka", 2021, "Global Vision, Local Reach", "#004d40", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Ave Maria University, Piyanko", "AMU", "Private University", "Private", "Nasarawa", "Piyanko", 2021, "Truth, Virtue and Light", "#1b5e20", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Phoenix University, Agwada", "PHOENIX", "Private University", "Private", "Nasarawa", "Agwada", 2023, "Rising to Global Heights", "#01579b", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Karl Kumm University, Vom", "KKU", "Private University", "Private", "Plateau", "Vom", 2021, "Light and Knowledge", "#00695c", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Al-Qalam University, Katsina", "AUK", "Private University", "Private", "Katsina", "Katsina", 2005, "Read in the Name of your Lord", "#004d40", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Skyline University Nigeria, Kano", "SUN-KANO", "Private University", "Private", "Kano", "Kano", 2018, "Knowledge, Skills and Value", "#0d47a1", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Maryam Abacha American University of Nigeria", "MAAUN", "Private University", "Private", "Kano", "Kano", 2021, "Excellence in Global Higher Education", "#b71c1c", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Capital City University, Kano", "CCUK", "Private University", "Private", "Kano", "Kano", 2021, "Knowledge for Transformation", "#1b5e20", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Al-Istiqama University, Sumaila", "AUSUM", "Private University", "Private", "Kano", "Sumaila", 2021, "Knowledge with Uprightness", "#004d40", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Khairun University, Kano", "KHAIRUN", "Private University", "Private", "Kano", "Kano", 2023, "Goodness in Learning", "#00695c", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Baba-Ahmed University, Kano", "BAU", "Private University", "Private", "Kano", "Sharada, Kano", 2022, "Excellence in Innovation", "#01579b", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Azman University, Kano", "AZMAN", "Private University", "Private", "Kano", "Kano", 2023, "Flight of Knowledge", "#b71c1c", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Greenfield University, Kaduna", "GFU", "Private University", "Private", "Kaduna", "Kasarami", 2019, "Knowledge for Self Reliance", "#1b5e20", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Franco-British International University", "FBIU", "Private University", "Private", "Kaduna", "Kaduna", 2023, "Bilingual Global Education", "#004d40", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Khadija University, Majia", "KUM", "Private University", "Private", "Jigawa", "Majia", 2021, "Knowledge and Morals", "#00695c", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Rayhaan University, Birnin Kebbi", "RAYHAAN", "Private University", "Private", "Kebbi", "Birnin Kebbi", 2023, "Fragrance of Wisdom", "#01579b", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Saisa University of Medical Sciences, Sokoto", "SAISA", "Private University", "Private", "Sokoto", "Sokoto", 2023, "Service to Humanity", "#004d40", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Iconic Open University, Sokoto", "ICONIC", "Private University", "Private", "Sokoto", "Sokoto", 2023, "Technology-Driven Education", "#b71c1c", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Huda University, Gusau", "HUDA", "Private University", "Private", "Zamfara", "Gusau", 2023, "Guidance through Education", "#1b5e20", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Pen Resource University, Gombe", "PRU", "Private University", "Private", "Gombe", "Gombe", 2022, "Enlightenment for All", "#00695c", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Al-Ansar University, Maiduguri", "AUM", "Private University", "Private", "Borno", "Maiduguri", 2022, "Knowledge with Faith", "#004d40", "NUC", "Full Accreditation", "Verified", 5.0),
  ("American University of Nigeria, Yola", "AUN", "Private University", "Private", "Adamawa", "Yola", 2003, "Africa's Development University", "#0d47a1", "NUC", "Full Accreditation", "Verified", 5.0),
  ("Al-Bayan University, Ankpa", "AL-BAYAN", "Private University", "Private", "Kogi", "Ankpa", 2023, "Clarity in Knowledge", "#1b5e20", "NUC", "Full Accreditation", "Verified", 5.0)
]

POLYTECHNICS = [
  # Additional Federal Polytechnics
  ("Federal Polytechnic, Ayede", "FPAYEDE", "Federal Polytechnic", "Federal", "Oyo", "Ayede, Ogo Oluwa", 2021, "Technology for Empowerment", "#004d40", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Federal Polytechnic, Daura", "FPDAURA", "Federal Polytechnic", "Federal", "Katsina", "Daura", 2019, "Technical Innovation", "#01579b", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Federal Polytechnic, Kaltungo", "FPKALTUNGO", "Federal Polytechnic", "Federal", "Gombe", "Kaltungo", 2019, "Knowledge and Skill", "#1b5e20", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Federal Polytechnic, Monguno", "FPMONGUNO", "Federal Polytechnic", "Federal", "Borno", "Monguno", 2021, "Technology for Development", "#00695c", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Federal Polytechnic, Shendam", "FPSHENDAM", "Federal Polytechnic", "Federal", "Plateau", "Shendam", 2021, "Skill and Character", "#004d40", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Federal Polytechnic, Wannune", "FPWANNUNE", "Federal Polytechnic", "Federal", "Benue", "Wannune", 2021, "Engineering Tomorrow", "#b71c1c", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Federal Polytechnic, Ugep", "FPUGEP", "Federal Polytechnic", "Federal", "Cross River", "Ugep", 2021, "Technology for Growth", "#1b5e20", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Federal Polytechnic, Ohodo", "FPOHODO", "Federal Polytechnic", "Federal", "Enugu", "Ohodo, Igbo-Etiti", 2021, "Excellence in Vocational Tech", "#01579b", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Petroleum Training Institute, Effurun", "PTI", "Federal Polytechnic", "Federal", "Delta", "Effurun", 1972, "Training Petroleum Tech Professionals", "#004d40", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("National Institute of Construction Technology and Management", "NICTM", "Federal Polytechnic", "Federal", "Edo", "Uromi", 2014, "Building the Nation", "#b71c1c", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Hussaini Adamu Federal Polytechnic, Kazaure", "HAFEDPOLY", "Federal Polytechnic", "Federal", "Jigawa", "Kazaure", 1991, "Skill for Self Reliance", "#00695c", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Federal Polytechnic, Ile-Oluji", "FEDPOLEL", "Federal Polytechnic", "Federal", "Ondo", "Ile-Oluji", 2014, "Technology and Progress", "#1b5e20", "NBTE", "Full Accreditation", "Verified", 4.0),

  # Additional State Polytechnics
  ("The Polytechnic, Ibadan", "POLYIBADAN", "State Polytechnic", "State", "Oyo", "Ibadan", 1970, "Ise Loogun Ise", "#0d47a1", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Adeseun Ogundoyin Polytechnic, Eruwa", "AOPE", "State Polytechnic", "State", "Oyo", "Eruwa", 2014, "Work and Progress", "#004d40", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Osun State Polytechnic, Iree", "OSPOLY", "State Polytechnic", "State", "Osun", "Iree", 1992, "Excellence in Technical Education", "#b71c1c", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Osun State College of Technology, Esa-Oke", "OSCOTECH", "State Polytechnic", "State", "Osun", "Esa-Oke", 1992, "Technology for Transformation", "#1b5e20", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Rufus Giwa Polytechnic, Owo", "RUGIPO", "State Polytechnic", "State", "Ondo", "Owo", 1979, "Knowledge, Skill and Character", "#01579b", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Moshood Abiola Polytechnic, Abeokuta", "MAPOLY", "State Polytechnic", "State", "Ogun", "Ojere, Abeokuta", 1980, "Innovation and Knowledge", "#004d40", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Abraham Adesanya Polytechnic, Ijebu-Igbo", "AAPOLY", "State Polytechnic", "State", "Ogun", "Ijebu-Igbo", 2006, "Education for Transformation", "#00695c", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Gateway ICT Polytechnic, Saapade", "GAPOSA", "State Polytechnic", "State", "Ogun", "Saapade", 2006, "ICT for Sustainable Growth", "#4a148c", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Ogun State Institute of Technology, Igbesa", "OGITECH", "State Polytechnic", "State", "Ogun", "Igbesa", 2005, "Building Technological Capacity", "#1b5e20", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("D.S. Adegbenro ICT Polytechnic, Itori", "DSAICT", "State Polytechnic", "State", "Ogun", "Itori, Ewekoro", 2006, "Technology and Ethics", "#b71c1c", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Delta State Polytechnic, Ogwashi-Uku", "DSPG", "State Polytechnic", "State", "Delta", "Ogwashi-Uku", 2002, "Skill and Knowledge", "#004d40", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Delta State Polytechnic, Otefe-Oghara", "DESPO", "State Polytechnic", "State", "Delta", "Otefe-Oghara", 2002, "Technology for Development", "#01579b", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Ken Saro-Wiwa Polytechnic, Bori", "KENPOLY", "State Polytechnic", "State", "Rivers", "Bori", 1988, "Skill and Service", "#00695c", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Captain Elechi Amadi Polytechnic, Port Harcourt", "CEAPOLY", "State Polytechnic", "State", "Rivers", "Rumuola, Port Harcourt", 1987, "Technology for Productivity", "#1b5e20", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Edo State Polytechnic, Usen", "EDOPOLY", "State Polytechnic", "State", "Edo", "Usen", 2002, "Skill and Industry", "#b71c1c", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Institute of Management and Technology, Enugu", "IMT", "State Polytechnic", "State", "Enugu", "Enugu", 1973, "Knowledge and Service", "#004d40", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Enugu State Polytechnic, Iwollo", "ESPOLY", "State Polytechnic", "State", "Enugu", "Iwollo", 2006, "Agricultural & Applied Technology", "#1b5e20", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Abia State Polytechnic, Aba", "ABIAPOLY", "State Polytechnic", "State", "Abia", "Aba", 1992, "Technology for Self Reliance", "#0d47a1", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Benue State Polytechnic, Ugbokolo", "BENPOLY", "State Polytechnic", "State", "Benue", "Ugbokolo", 1977, "Labor and Knowledge", "#00695c", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Plateau State Polytechnic, Barkin Ladi", "PLAPOLY", "State Polytechnic", "State", "Plateau", "Barkin Ladi", 1978, "Technology for National Growth", "#004d40", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Isa Mustapha Agwai I Polytechnic, Lafia", "IMAP", "State Polytechnic", "State", "Nasarawa", "Lafia", 2000, "Education for Productivity", "#b71c1c", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Kogi State Polytechnic, Lokoja", "KSP", "State Polytechnic", "State", "Kogi", "Lokoja", 1992, "Knowledge for Skill", "#1b5e20", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Niger State Polytechnic, Zungeru", "NIGERPOLY", "State Polytechnic", "State", "Niger", "Zungeru", 1977, "Technology for Transformation", "#01579b", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Kano State Polytechnic", "KANOPOLY", "State Polytechnic", "State", "Kano", "Kano", 1975, "Skill, Technology, Service", "#004d40", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Abdu Gusau Polytechnic, Talata Mafara", "AGP", "State Polytechnic", "State", "Zamfara", "Talata Mafara", 1992, "Hard Work and Skill", "#00695c", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Umaru Ali Shinkafi Polytechnic, Sokoto", "SOSPOLY", "State Polytechnic", "State", "Sokoto", "Sokoto", 2002, "Skill and Self Reliance", "#b71c1c", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Kebbi State Polytechnic, Dakingari", "KEBBIPOLY", "State Polytechnic", "State", "Kebbi", "Dakingari", 2014, "Advancing Technical Skills", "#1b5e20", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Hassan Usman Katsina Polytechnic", "HUKPOLY", "State Polytechnic", "State", "Katsina", "Katsina", 1983, "Knowledge and Skill", "#004d40", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Nuhu Bamalli Polytechnic, Zaria", "NUBAPOLY", "State Polytechnic", "State", "Kaduna", "Zaria", 1989, "Technological Prowess", "#01579b", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Binyaminu Usman Polytechnic, Hadejia", "BUPOLY", "State Polytechnic", "State", "Jigawa", "Hadejia", 1992, "Service and Knowledge", "#00695c", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Taraba State Polytechnic, Suntai", "TARABAPOLY", "State Polytechnic", "State", "Taraba", "Suntai/Jalingo", 1991, "Skill for Prosperity", "#1b5e20", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Mai Idris Alooma Polytechnic, Geidam", "MIAP", "State Polytechnic", "State", "Yobe", "Geidam", 2002, "Knowledge and Industry", "#004d40", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Ramat Polytechnic, Maiduguri", "RAMATPOLY", "State Polytechnic", "State", "Borno", "Maiduguri", 1973, "Knowledge and Self Reliance", "#b71c1c", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Abubakar Tatari Ali Polytechnic, Bauchi", "ATAPOLY", "State Polytechnic", "State", "Bauchi", "Bauchi", 1988, "Vocational Skill for Growth", "#01579b", "NBTE", "Full Accreditation", "Verified", 4.0),

  # Approved Private Polytechnics (NBTE Approved)
  ("Dorben Polytechnic, Bwari", "DORBEN", "Private Polytechnic", "Private", "FCT", "Bwari, Abuja", 1995, "Knowledge for Self Reliance", "#0d47a1", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Prime Polytechnic, Jikwoyi", "PRIME-POLY", "Private Polytechnic", "Private", "FCT", "Jikwoyi, Abuja", 2009, "Technology for Tomorrow", "#004d40", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Heritage Polytechnic, Eket", "HERITAGE", "Private Polytechnic", "Private", "Akwa Ibom", "Ikono, Eket", 2001, "Excellence in Technical Training", "#b71c1c", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Trinity Polytechnic, Uyo", "TRINITY-POLY", "Private Polytechnic", "Private", "Akwa Ibom", "Uyo", 2014, "Skill and Godliness", "#1b5e20", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Sure Foundation Polytechnic", "SFP", "Private Polytechnic", "Private", "Akwa Ibom", "Ikot Akpaden", 2015, "Solid Foundation in Tech", "#00695c", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Crown Polytechnic, Ado-Ekiti", "CROWN", "Private Polytechnic", "Private", "Ekiti", "Odo, Ado-Ekiti", 2008, "Innovation for Royalty", "#01579b", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Kings Polytechnic, Ubiaja", "KINGS-POLY", "Private Polytechnic", "Private", "Edo", "Ubiaja", 2006, "Training Leaders in Technology", "#004d40", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Lighthouse Polytechnic, Evbuobanosa", "LIGHTHOUSE", "Private Polytechnic", "Private", "Edo", "Evbuobanosa", 2008, "Guiding Technical Excellence", "#b71c1c", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Shaka Polytechnic, Benin City", "SHAKA", "Private Polytechnic", "Private", "Edo", "Benin City", 1986, "Practical Entrepreneurial Skills", "#1b5e20", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Lens Polytechnic, Offa", "LENS", "Private Polytechnic", "Private", "Kwara", "Offa", 2012, "Focused on Excellence", "#00695c", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Harvard Polytechnic, Ilorin", "HARVARD", "Private Polytechnic", "Private", "Kwara", "Ilorin", 2017, "Global Tech Standard", "#0d47a1", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Covenant Polytechnic, Aba", "COVENANT-POLY", "Private Polytechnic", "Private", "Abia", "Aba", 2005, "Covenant for Innovation", "#004d40", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Temple Gate Polytechnic, Aba", "TEMPLEGATE", "Private Polytechnic", "Private", "Abia", "Aba", 2005, "Gate to Technical Mastery", "#b71c1c", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Valley View Polytechnic, Ohafia", "VALLEYVIEW", "Private Polytechnic", "Private", "Abia", "Ohafia", 2016, "Clear View for Future Tech", "#1b5e20", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Mater Dei Polytechnic, Ugwunagbo", "MATERDEI", "Private Polytechnic", "Private", "Abia", "Ugwunagbo", 2018, "Mother of Good Counsel & Skill", "#01579b", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Uma Ukpai Polytechnic, Asaga Ohafia", "UMAUKPAI", "Private Polytechnic", "Private", "Abia", "Asaga Ohafia", 2017, "Faith and Technological Growth", "#00695c", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Grace Polytechnic, Surulere", "GRACE", "Private Polytechnic", "Private", "Lagos", "Surulere", 1999, "Grace for Excellence", "#004d40", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Coastal Polytechnic, Apapa", "COASTAL", "Private Polytechnic", "Private", "Lagos", "Apapa", 2019, "Navigating Tech Frontiers", "#0d47a1", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Lagos City Polytechnic, Ikeja", "LCP", "Private Polytechnic", "Private", "Lagos", "Ikeja", 1990, "Excellence in Commerce and Tech", "#b71c1c", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Ronik Polytechnic, Ejigbo", "RONIK", "Private Polytechnic", "Private", "Lagos", "Ejigbo", 2001, "Discipline and Technical Prowess", "#1b5e20", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Best Polytechnic, Ikorodu", "BEST-POLY", "Private Polytechnic", "Private", "Lagos", "Ikorodu", 2014, "Excellence and Character", "#00695c", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Speedway Polytechnic, Ojodu", "SPEEDWAY", "Private Polytechnic", "Private", "Lagos", "Ojodu", 2017, "Fast-Track Technical Mastery", "#01579b", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Kalac Christal Polytechnic, Lekki", "KALAC", "Private Polytechnic", "Private", "Lagos", "Lekki", 2018, "Brilliance in Technology", "#4a148c", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Wolex Polytechnic, Iwo", "WOLEX", "Private Polytechnic", "Private", "Osun", "Iwo", 1996, "Skill for Self-Employment", "#004d40", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Interlink Polytechnic, Ijebu-Jesa", "INTERLINK", "Private Polytechnic", "Private", "Osun", "Ijebu-Jesa", 2008, "Connecting Minds to Industry", "#b71c1c", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Citadel Polytechnic, Ikirun", "CITADEL", "Private Polytechnic", "Private", "Osun", "Ikirun", 2017, "Strong Tower of Technology", "#1b5e20", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Villanova Polytechnic, Imesi-Ile", "VILLANOVA", "Private Polytechnic", "Private", "Osun", "Imesi-Ile", 2018, "Knowledge, Industry and Character", "#00695c", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Ipetumodu Polytechnic, Ipetumodu", "IPETPOLY", "Private Polytechnic", "Private", "Osun", "Ipetumodu", 2018, "Technology for Rural and Urban Advancement", "#01579b", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Ibadan City Polytechnic, Ibadan", "ICP", "Private Polytechnic", "Private", "Oyo", "Ibadan", 2015, "Leading Technical Revolution", "#004d40", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Bolmor Polytechnic, Ibadan", "BOLMOR", "Private Polytechnic", "Private", "Oyo", "Ibadan", 2015, "Integrity in Technical Learning", "#b71c1c", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Saf Polytechnic, Iseyin", "SAF-POLY", "Private Polytechnic", "Private", "Oyo", "Iseyin", 2017, "Skill and Innovation", "#1b5e20", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Tower Polytechnic, Ibadan", "TOWER", "Private Polytechnic", "Private", "Oyo", "Ibadan", 2010, "Pinnacle of Technological Mastery", "#00695c", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Timehin Polytechnic, Ibadan", "TIMEHIN", "Private Polytechnic", "Private", "Oyo", "Ibadan", 2018, "Knowledge for Empowerment", "#01579b", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Ambassador Polytechnic, Ota", "AMBASSADOR", "Private Polytechnic", "Private", "Ogun", "Ota", 2017, "Ambassadors of Technology", "#004d40", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Al-Hikma Polytechnic, Karu", "AL-HIKMA-POLY", "Private Polytechnic", "Private", "Nasarawa", "Karu", 2014, "Wisdom in Applied Science", "#1b5e20", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Nacabs Polytechnic, Akwanga", "NACABS", "Private Polytechnic", "Private", "Nasarawa", "Akwanga", 2012, "Technology for Nationhood", "#00695c", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Fidei Polytechnic, Gboko", "FIDEI", "Private Polytechnic", "Private", "Benue", "Gboko", 2007, "Faith and Science", "#0d47a1", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Gboko Polytechnic, Gboko", "GBOKO-POLY", "Private Polytechnic", "Private", "Benue", "Gboko", 2014, "Practical Technical Training", "#b71c1c", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Ashi Polytechnic, Anyiin", "ASHI", "Private Polytechnic", "Private", "Benue", "Anyiin", 2016, "Excellence in Craft and Tech", "#1b5e20", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Harry Pass Polytechnic, Gboko", "HARRYPASS", "Private Polytechnic", "Private", "Benue", "Gboko", 2018, "Gateway to Success", "#004d40", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Calvary Polytechnic, Owa-Oyibu", "CALVARY", "Private Polytechnic", "Private", "Delta", "Owa-Oyibu", 2015, "Power of Technology", "#01579b", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("Bellarks Polytechnic, Kwale", "BELLARKS", "Private Polytechnic", "Private", "Delta", "Kwale", 2019, "Innovating Tomorrow", "#00695c", "NBTE", "Full Accreditation", "Verified", 4.0),
  ("St. Mary Polytechnic, Suleja", "STMARY", "Private Polytechnic", "Private", "Niger", "Kwamba, Suleja", 2014, "Virtue and Knowledge", "#004d40", "NBTE", "Full Accreditation", "Verified", 4.0)
]

print(f"Loaded Part 1: {len(UNIVERSITIES)} Universities, {len(POLYTECHNICS)} Polytechnics.")
