const fs = require('fs');
const path = require('path');

const statesCatalog = {
  "Abia": [
    {
      id: 'mouau',
      name: 'Michael Okpara University of Agriculture, Umudike',
      shortName: 'MOUAU',
      type: 'Federal University',
      ownership: 'Federal',
      city: 'Umudike, Umuahia',
      geopoliticalZone: 'South East',
      establishedYear: 1992,
      motto: 'Knowledge, Food and Security',
      logoColor: '#2e7d32',
      gradingSystem: '5.0',
      websiteUrl: 'https://mouau.edu.ng',
      portalUrl: 'https://portal.mouau.edu.ng',
      regulator: 'NUC',
      accreditationStatus: 'Full Accreditation',
      verificationStatus: 'Verified',
      sourceUrl: 'https://www.nuc.edu.ng/nigerian-univerisities/federal-universities/',
      lastVerified: '2024-06-15',
      isDemo: false,
      description: 'Premier federal specialized agricultural and technological university in South East Nigeria with strong engineering, sciences, veterinary medicine, and management faculties.',
      faculties: [
        'College of Physical and Applied Sciences',
        'College of Engineering and Engineering Technology',
        'College of Agricultural Economics, Rural Sociology and Extension',
        'College of Animal Science and Animal Production',
        'College of Crop and Soil Sciences',
        'College of Veterinary Medicine',
        'College of Management Sciences',
        'College of Education'
      ]
    },
    {
      id: 'absu',
      name: 'Abia State University',
      shortName: 'ABSU',
      type: 'State University',
      ownership: 'State',
      city: 'Uturu',
      geopoliticalZone: 'South East',
      establishedYear: 1981,
      motto: 'Excellence and Service',
      logoColor: '#004d40',
      gradingSystem: '5.0',
      websiteUrl: 'https://abiastateuniversity.edu.ng',
      portalUrl: 'https://portal.abiastateuniversity.edu.ng',
      regulator: 'NUC',
      accreditationStatus: 'Full Accreditation',
      verificationStatus: 'Verified',
      sourceUrl: 'https://www.nuc.edu.ng/nigerian-univerisities/state-universities/',
      lastVerified: '2024-06-15',
      isDemo: false,
      description: 'Premier state university in Abia State, acclaimed for its college of medicine, law, business administration, optometry, and biological sciences.',
      faculties: [
        'College of Medicine & Health Sciences',
        'Faculty of Law',
        'Faculty of Biological Sciences',
        'Faculty of Physical Sciences',
        'Faculty of Business Administration',
        'Faculty of Social Sciences',
        'Faculty of Environmental Studies',
        'Faculty of Agriculture',
        'Faculty of Education'
      ]
    },
    {
      id: 'gregory_uni',
      name: 'Gregory University, Uturu',
      shortName: 'GUU',
      type: 'Private University',
      ownership: 'Private',
      city: 'Uturu',
      geopoliticalZone: 'South East',
      establishedYear: 2012,
      motto: 'Knowledge for Tomorrow',
      logoColor: '#1565c0',
      gradingSystem: '5.0',
      websiteUrl: 'https://gregoryuniversity.edu.ng',
      portalUrl: 'https://portal.gregoryuniversity.edu.ng',
      regulator: 'NUC',
      accreditationStatus: 'Full Accreditation',
      verificationStatus: 'Verified',
      sourceUrl: 'https://www.nuc.edu.ng/nigerian-univerisities/private-universities/',
      lastVerified: '2024-06-15',
      isDemo: false,
      description: 'Renowned private university established by the Gregory Iyke Foundation, acclaimed for medicine, engineering, law, and business innovations.',
      faculties: [
        'College of Medicine and Health Sciences',
        'College of Engineering',
        'College of Law',
        'College of Natural and Applied Sciences',
        'College of Social and Management Sciences'
      ]
    },
    {
      id: 'clifford_uni',
      name: 'Clifford University, Owerrinta',
      shortName: 'CLU',
      type: 'Private University',
      ownership: 'Private',
      city: 'Ihie, Owerrinta',
      geopoliticalZone: 'South East',
      establishedYear: 2013,
      motto: 'Knowledge, Truth and Service',
      logoColor: '#4527a0',
      gradingSystem: '5.0',
      websiteUrl: 'https://clifforduni.edu.ng',
      portalUrl: 'https://portal.clifforduni.edu.ng',
      regulator: 'NUC',
      accreditationStatus: 'Full Accreditation',
      verificationStatus: 'Verified',
      sourceUrl: 'https://www.nuc.edu.ng/nigerian-univerisities/private-universities/',
      lastVerified: '2024-06-15',
      isDemo: false,
      description: 'Seventh-day Adventist private university known for holistic academic character formation, science, and nursing education.',
      faculties: [
        'Faculty of Science and Computing',
        'Faculty of Social and Management Sciences',
        'Faculty of Humanities',
        'Faculty of Basic Medical Sciences'
      ]
    },
    {
      id: 'abia_poly',
      name: 'Abia State Polytechnic, Aba',
      shortName: 'ABIAPOLY',
      type: 'State Polytechnic',
      ownership: 'State',
      city: 'Aba',
      geopoliticalZone: 'South East',
      establishedYear: 1992,
      motto: 'Technology for Self Reliance',
      logoColor: '#c2185b',
      gradingSystem: '4.0',
      websiteUrl: 'https://abiapoly.edu.ng',
      portalUrl: 'https://portal.abiapoly.edu.ng',
      regulator: 'NBTE',
      accreditationStatus: 'Full Accreditation',
      verificationStatus: 'Verified',
      sourceUrl: 'https://nbte.gov.ng/polytechnics',
      lastVerified: '2024-06-15',
      isDemo: false,
      description: 'Major state polytechnic located in commercial city of Aba, training technologists in engineering, computer science, business studies, and science laboratory technology.',
      faculties: [
        'School of Engineering Technology',
        'School of Science & Industrial Technology',
        'School of Business & Management Studies',
        'School of Environmental Design Technology'
      ]
    },
    {
      id: 'asceta_arochukwu',
      name: 'Abia State College of Education (Technical), Arochukwu',
      shortName: 'ASCETA',
      type: 'State College of Education',
      ownership: 'State',
      city: 'Arochukwu',
      geopoliticalZone: 'South East',
      establishedYear: 1993,
      motto: 'Teaching for Technological Breakthrough',
      logoColor: '#00796b',
      gradingSystem: '4.0',
      websiteUrl: 'https://asceta.edu.ng',
      regulator: 'NCCE',
      accreditationStatus: 'Accredited',
      verificationStatus: 'Verified',
      sourceUrl: 'https://ncceonline.edu.ng',
      lastVerified: '2024-06-15',
      isDemo: false,
      description: 'Accredited state technical teacher training college offering NCE programmes in vocational and technical education, sciences, and primary education.',
      faculties: [
        'School of Technical Education',
        'School of Vocational Education',
        'School of Sciences',
        'School of Education'
      ]
    },
    {
      id: 'abia_health_aba',
      name: 'Abia State College of Health Sciences and Management Technology',
      shortName: 'ASCOHMAT',
      type: 'College of Health Sciences and Technology',
      ownership: 'State',
      city: 'Aba',
      geopoliticalZone: 'South East',
      establishedYear: 2007,
      motto: 'Skillful Health Care for Humanity',
      logoColor: '#0288d1',
      gradingSystem: '4.0',
      websiteUrl: 'https://ascoht.edu.ng',
      regulator: 'NBTE',
      accreditationStatus: 'Accredited',
      verificationStatus: 'Verified',
      sourceUrl: 'https://nbte.gov.ng',
      lastVerified: '2024-06-15',
      isDemo: false,
      description: 'Health technology institute in Aba training practitioners in community health, medical laboratory technology, environmental health, and health information management.',
      faculties: [
        'Department of Community Health Sciences',
        'Department of Medical Laboratory Sciences',
        'Department of Environmental Health Sciences',
        'Department of Health Information Management'
      ]
    }
  ],

  "Adamawa": [
    {
      id: 'mau_yola',
      name: 'Modibbo Adama University, Yola',
      shortName: 'MAU',
      type: 'Federal University',
      ownership: 'Federal',
      city: 'Girei, Yola',
      geopoliticalZone: 'North East',
      establishedYear: 1981,
      motto: 'Technology for Development',
      logoColor: '#1b5e20',
      gradingSystem: '5.0',
      websiteUrl: 'https://mau.edu.ng',
      portalUrl: 'https://portal.mau.edu.ng',
      regulator: 'NUC',
      accreditationStatus: 'Full Accreditation',
      verificationStatus: 'Verified',
      sourceUrl: 'https://www.nuc.edu.ng/nigerian-univerisities/federal-universities/',
      lastVerified: '2024-06-15',
      isDemo: false,
      description: 'Formerly MAUTECH, converted to a comprehensive federal university, leading in engineering, computing, medical sciences, physical sciences, and agriculture.',
      faculties: [
        'Faculty of Engineering',
        'Faculty of Physical Sciences',
        'Faculty of Life Sciences',
        'College of Medical Sciences',
        'Faculty of Agriculture',
        'Faculty of Social and Management Sciences',
        'Faculty of Environmental Sciences',
        'Faculty of Education'
      ]
    },
    {
      id: 'adsu_mubi',
      name: 'Adamawa State University, Mubi',
      shortName: 'ADSU',
      type: 'State University',
      ownership: 'State',
      city: 'Mubi',
      geopoliticalZone: 'North East',
      establishedYear: 2002,
      motto: 'Education for Development',
      logoColor: '#00695c',
      gradingSystem: '5.0',
      websiteUrl: 'https://adsu.edu.ng',
      portalUrl: 'https://adsu.safsrms.com',
      regulator: 'NUC',
      accreditationStatus: 'Full Accreditation',
      verificationStatus: 'Verified',
      sourceUrl: 'https://www.nuc.edu.ng/nigerian-univerisities/state-universities/',
      lastVerified: '2024-06-15',
      isDemo: false,
      description: 'Premier state university in Adamawa State situated in Mubi, delivering courses in computer science, agriculture, pure sciences, and administration.',
      faculties: [
        'Faculty of Science',
        'Faculty of Agriculture',
        'Faculty of Social & Management Sciences',
        'Faculty of Arts and Humanities',
        'Faculty of Education'
      ]
    },
    {
      id: 'aun_yola',
      name: 'American University of Nigeria, Yola',
      shortName: 'AUN',
      type: 'Private University',
      ownership: 'Private',
      city: 'Yola',
      geopoliticalZone: 'North East',
      establishedYear: 2004,
      motto: 'Development University for Africa',
      logoColor: '#0d47a1',
      gradingSystem: '4.0',
      websiteUrl: 'https://aun.edu.ng',
      portalUrl: 'https://open.aun.edu.ng',
      regulator: 'NUC',
      accreditationStatus: 'Full Accreditation',
      verificationStatus: 'Verified',
      sourceUrl: 'https://www.nuc.edu.ng/nigerian-univerisities/private-universities/',
      lastVerified: '2024-06-15',
      isDemo: false,
      description: 'First American-style liberal arts university in Sub-Saharan Africa, offering world-class technology, software engineering, law, and business programmes.',
      faculties: [
        'School of Information Technology & Computing',
        'School of Business & Entrepreneurship',
        'School of Law',
        'School of Arts & Sciences',
        'School of Engineering'
      ]
    },
    {
      id: 'fedpoly_mubi',
      name: 'Federal Polytechnic, Mubi',
      shortName: 'FPM',
      type: 'Federal Polytechnic',
      ownership: 'Federal',
      city: 'Mubi',
      geopoliticalZone: 'North East',
      establishedYear: 1979,
      motto: 'Knowledge and Skill for Service',
      logoColor: '#b71c1c',
      gradingSystem: '4.0',
      websiteUrl: 'https://fpmubionline.edu.ng',
      portalUrl: 'https://portal.fpmubionline.edu.ng',
      regulator: 'NBTE',
      accreditationStatus: 'Full Accreditation',
      verificationStatus: 'Verified',
      sourceUrl: 'https://nbte.gov.ng/polytechnics',
      lastVerified: '2024-06-15',
      isDemo: false,
      description: 'Prominent federal polytechnic in North East Nigeria, offering accredited National Diploma and Higher National Diploma curricula.',
      faculties: [
        'School of Engineering Technology',
        'School of Science and Technology',
        'School of Business and Management Technology',
        'School of Environmental Science and Technology',
        'School of Agricultural Technology'
      ]
    },
    {
      id: 'adamawa_poly_yola',
      name: 'Adamawa State Polytechnic, Yola',
      shortName: 'SPYOLA',
      type: 'State Polytechnic',
      ownership: 'State',
      city: 'Yola',
      geopoliticalZone: 'North East',
      establishedYear: 1991,
      motto: 'Technology for Self Reliance',
      logoColor: '#e65100',
      gradingSystem: '4.0',
      websiteUrl: 'https://adamawapoly.edu.ng',
      regulator: 'NBTE',
      accreditationStatus: 'Accredited',
      verificationStatus: 'Verified',
      sourceUrl: 'https://nbte.gov.ng/polytechnics',
      lastVerified: '2024-06-15',
      isDemo: false,
      description: 'State polytechnic in Yola training students in engineering, computing, administrative studies, and community technology.',
      faculties: [
        'School of Engineering',
        'School of Science and Technology',
        'School of Administration and Business Studies',
        'School of Environmental Studies'
      ]
    },
    {
      id: 'fce_yola',
      name: 'Federal College of Education, Yola',
      shortName: 'FCE Yola',
      type: 'Federal College of Education',
      ownership: 'Federal',
      city: 'Yola',
      geopoliticalZone: 'North East',
      establishedYear: 1974,
      motto: 'Excellence in Teacher Education',
      logoColor: '#303f9f',
      gradingSystem: '4.0',
      websiteUrl: 'https://fceyola.edu.ng',
      regulator: 'NCCE',
      accreditationStatus: 'Full Accreditation',
      verificationStatus: 'Verified',
      sourceUrl: 'https://ncceonline.edu.ng',
      lastVerified: '2024-06-15',
      isDemo: false,
      description: 'Federal teacher education institution in Yola training qualified teachers in sciences, vocational arts, languages, and primary education.',
      faculties: [
        'School of Sciences',
        'School of Vocational Education',
        'School of Languages',
        'School of Arts and Social Sciences',
        'School of Education'
      ]
    },
    {
      id: 'adamawa_nursing_yola',
      name: 'Adamawa State College of Nursing Sciences, Yola',
      shortName: 'ADCONSY',
      type: 'College of Nursing Sciences',
      ownership: 'State',
      city: 'Yola',
      geopoliticalZone: 'North East',
      establishedYear: 1977,
      motto: 'Care with Compassion and Skill',
      logoColor: '#00838f',
      gradingSystem: '4.0',
      websiteUrl: 'https://conmyola.edu.ng',
      regulator: 'NMCN',
      accreditationStatus: 'Accredited',
      verificationStatus: 'Verified',
      sourceUrl: 'https://www.nmcn.gov.ng',
      lastVerified: '2024-06-15',
      isDemo: false,
      description: 'Official state college providing registered nursing (RN) and registered midwifery (RM) training accredited by NMCN.',
      faculties: [
        'Department of General Nursing',
        'Department of Basic Midwifery',
        'Department of Public Health Nursing'
      ]
    }
  ]
};

console.log('Registered base states:', Object.keys(statesCatalog).length);
